// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer used to parametrize an iterated local search (ILS) approach.
// ILS is an iterative metaheuristic in which every iteration consists in
// performing a perturbation followed by an improvement step on a reference
// solution to generate a neighbor solution.
// The neighbor solution is accepted as the new reference solution according
// to an acceptance criterion.
// The best found solution is eventually returned.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ortools/constraint_solver/routing_ils.proto

package constraintsolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuinCompositionStrategy_Value int32

const (
	// Unspecified value.
	RuinCompositionStrategy_UNSET RuinCompositionStrategy_Value = 0
	// Execute all ruin strategies sequentially in the same order provided in
	// input.
	RuinCompositionStrategy_RUN_ALL_SEQUENTIALLY RuinCompositionStrategy_Value = 1
	// Execute all ruin strategies in a random order.
	RuinCompositionStrategy_RUN_ALL_RANDOMLY RuinCompositionStrategy_Value = 2
	// Execute a randomly selected ruin.
	RuinCompositionStrategy_RUN_ONE_RANDOMLY RuinCompositionStrategy_Value = 3
)

// Enum value maps for RuinCompositionStrategy_Value.
var (
	RuinCompositionStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "RUN_ALL_SEQUENTIALLY",
		2: "RUN_ALL_RANDOMLY",
		3: "RUN_ONE_RANDOMLY",
	}
	RuinCompositionStrategy_Value_value = map[string]int32{
		"UNSET":                0,
		"RUN_ALL_SEQUENTIALLY": 1,
		"RUN_ALL_RANDOMLY":     2,
		"RUN_ONE_RANDOMLY":     3,
	}
)

func (x RuinCompositionStrategy_Value) Enum() *RuinCompositionStrategy_Value {
	p := new(RuinCompositionStrategy_Value)
	*p = x
	return p
}

func (x RuinCompositionStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuinCompositionStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[0].Descriptor()
}

func (RuinCompositionStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[0]
}

func (x RuinCompositionStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuinCompositionStrategy_Value.Descriptor instead.
func (RuinCompositionStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{6, 0}
}

type PerturbationStrategy_Value int32

const (
	// Unspecified value.
	PerturbationStrategy_UNSET PerturbationStrategy_Value = 0
	// Performs a perturbation in a ruin and recreate fashion.
	PerturbationStrategy_RUIN_AND_RECREATE PerturbationStrategy_Value = 1
)

// Enum value maps for PerturbationStrategy_Value.
var (
	PerturbationStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "RUIN_AND_RECREATE",
	}
	PerturbationStrategy_Value_value = map[string]int32{
		"UNSET":             0,
		"RUIN_AND_RECREATE": 1,
	}
)

func (x PerturbationStrategy_Value) Enum() *PerturbationStrategy_Value {
	p := new(PerturbationStrategy_Value)
	*p = x
	return p
}

func (x PerturbationStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PerturbationStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[1].Descriptor()
}

func (PerturbationStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[1]
}

func (x PerturbationStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PerturbationStrategy_Value.Descriptor instead.
func (PerturbationStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{8, 0}
}

type CoolingScheduleStrategy_Value int32

const (
	// Unspecified value.
	CoolingScheduleStrategy_UNSET CoolingScheduleStrategy_Value = 0
	// Exponentially decreases the temperature as the search progresses.
	// More precisely, t = t0 * (t1/t0)^p.
	CoolingScheduleStrategy_EXPONENTIAL CoolingScheduleStrategy_Value = 1
	// Linearly decreases the temperature as the search progresses.
	// More precisely, t = t0 - p * (t0 - t1).
	CoolingScheduleStrategy_LINEAR CoolingScheduleStrategy_Value = 2
)

// Enum value maps for CoolingScheduleStrategy_Value.
var (
	CoolingScheduleStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "EXPONENTIAL",
		2: "LINEAR",
	}
	CoolingScheduleStrategy_Value_value = map[string]int32{
		"UNSET":       0,
		"EXPONENTIAL": 1,
		"LINEAR":      2,
	}
)

func (x CoolingScheduleStrategy_Value) Enum() *CoolingScheduleStrategy_Value {
	p := new(CoolingScheduleStrategy_Value)
	*p = x
	return p
}

func (x CoolingScheduleStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoolingScheduleStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[2].Descriptor()
}

func (CoolingScheduleStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[2]
}

func (x CoolingScheduleStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoolingScheduleStrategy_Value.Descriptor instead.
func (CoolingScheduleStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{9, 0}
}

// Ruin strategy that removes a number of spatially close routes.
type SpatiallyCloseRoutesRuinStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of spatially close routes ruined at each ruin application.
	NumRuinedRoutes *uint32 `protobuf:"varint,3,opt,name=num_ruined_routes,json=numRuinedRoutes,proto3,oneof" json:"num_ruined_routes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SpatiallyCloseRoutesRuinStrategy) Reset() {
	*x = SpatiallyCloseRoutesRuinStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpatiallyCloseRoutesRuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatiallyCloseRoutesRuinStrategy) ProtoMessage() {}

func (x *SpatiallyCloseRoutesRuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatiallyCloseRoutesRuinStrategy.ProtoReflect.Descriptor instead.
func (*SpatiallyCloseRoutesRuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{0}
}

func (x *SpatiallyCloseRoutesRuinStrategy) GetNumRuinedRoutes() uint32 {
	if x != nil && x.NumRuinedRoutes != nil {
		return *x.NumRuinedRoutes
	}
	return 0
}

// Ruin strategy that removes a number of nodes by performing a random walk
// on the underlying routing solution. More precisely, starting from a randomly
// selected seed visit, the walk is extended by either moving within the
// same route or by jumping to a visit served by a different neighboring
// route. Every active visit encountered along this random walk is made
// unperformed.
type RandomWalkRuinStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of visits removed during a ruin application defined on visits.
	// Note that pickup and delivery pairs are considered as a single entity,
	// i.e., the removal of a pickup (respectively delivery) causes the removal of
	// the associated delivery (respectively pickup) and it counts as a single
	// removal.
	NumRemovedVisits *uint32 `protobuf:"varint,7,opt,name=num_removed_visits,json=numRemovedVisits,proto3,oneof" json:"num_removed_visits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RandomWalkRuinStrategy) Reset() {
	*x = RandomWalkRuinStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomWalkRuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomWalkRuinStrategy) ProtoMessage() {}

func (x *RandomWalkRuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomWalkRuinStrategy.ProtoReflect.Descriptor instead.
func (*RandomWalkRuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{1}
}

func (x *RandomWalkRuinStrategy) GetNumRemovedVisits() uint32 {
	if x != nil && x.NumRemovedVisits != nil {
		return *x.NumRemovedVisits
	}
	return 0
}

// Ruin strategy based on the "Slack Induction by String Removals for Vehicle
// Routing Problems" by Jan Christiaens and Greet Vanden Berghe, Transportation
// Science 2020.
//
// Note that, in this implementation, the notion of "string" is replaced by
// "sequence".
//
// The main idea of this ruin is to remove a number of geographically close
// sequences of nodes. In particular, at every ruin application, a maximum
// number max_ruined_routes of routes are disrupted. The value for
// max_ruined_routes is defined as
//
//	(4 * avg_num_removed_visits) / (1 + max_sequence_size) + 1
//
// with
//   - avg_num_removed_visits: user-defined parameter ruling the average number of
//     visits that are removed in face of several ruin applications (see also the
//     proto message below)
//   - max_sequence_size is defined as
//     min{max_removed_sequence_size, average_route_size}
//     with
//   - max_removed_sequence_size: user-defined parameter that specifies
//     the maximum number of visits removed from a single route (see also the
//     proto message below)
//   - average_route_size: the average size of a non-empty route in the current
//     solution
//
// The actual number of ruined routes is then obtained as
//
//	floor(U(1, max_ruined_routes + 1))
//
// where U is a continuous uniform distribution of real values in the given
// interval.
//
// The routes affected by the ruin procedure are selected as follows.
// First, a non start/end seed node is randomly selected. The route serving this
// node is the first ruined route. Then, until the required number of routes has
// been ruined, neighbor nodes of the initial seed node are scanned and the
// associated not yet ruined routes are disrupted. Nodes defining the selected
// routes are designated as seed nodes for the "sequence" and "split sequence"
// removal procedures described below.
//
// For every selected route, a maximum number route_max_sequence_size of nodes
// are removed. In particular, route_max_sequence_size is defined as
//
//	min{route_size, max_sequence_size}
//
// with route_size being the size of the current route.
//
// Then, the actual number of removed nodes num_removed_nodes is defined as
//
//	floor(U(1, route_max_sequence_size + 1))
//
// where U is a continuous uniform distribution of real values in the given
// interval.
//
// As mentioned above, the selected num_removed_nodes number of nodes is removed
// either via the "sequence" removal or "split sequence" removal procedures. The
// two removal procedures are executed with equal probabilities.
//
// The "sequence" removal procedure removes a randomly selected sequence of size
// num_removed_nodes that includes the seed node.
//
// The "split sequence" removal procedure also removes a randomly selected
// sequence of size num_removed_nodes that includes the seed node, but it can
// possibly preserve a subsequence of contiguous nodes.
// In particular, the procedure first selects a sequence of size
// num_removed_nodes + num_bypassed, then num_bypassed contiguous nodes in the
// selected sequence are preserved while the others removed.
//
// The definition of num_bypassed is as follows. First num_bypassed = 1. The
// current value of num_bypassed is maintaned if
//
//	U(0, 1) < bypass_factor * U(0, 1)
//
// or the maximum value for num_bypassed, equal to
//
//	route_size - num_removed_nodes
//
// is reached. The value is incremented of a unit otherwise,
// and the process is repeated. The value assigned to bypass_factor affects the
// number of preserved visits (see also the proto message below).
type SISRRuinStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of removed visits per sequence. The parameter name in the
	// paper is L^{max} and the suggested value is 10.
	MaxRemovedSequenceSize *uint32 `protobuf:"varint,1,opt,name=max_removed_sequence_size,json=maxRemovedSequenceSize,proto3,oneof" json:"max_removed_sequence_size,omitempty"`
	// Number of visits that are removed on average. The parameter name in the
	// paper is \bar{c} and the suggested value is 10.
	AvgNumRemovedVisits *uint32 `protobuf:"varint,2,opt,name=avg_num_removed_visits,json=avgNumRemovedVisits,proto3,oneof" json:"avg_num_removed_visits,omitempty"`
	// Value in [0, 1] ruling the number of preserved nodes in the split
	// sequence removal. The parameter name in the paper is \alpha and the
	// suggested value is 0.01.
	BypassFactor  *float64 `protobuf:"fixed64,3,opt,name=bypass_factor,json=bypassFactor,proto3,oneof" json:"bypass_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SISRRuinStrategy) Reset() {
	*x = SISRRuinStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SISRRuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SISRRuinStrategy) ProtoMessage() {}

func (x *SISRRuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SISRRuinStrategy.ProtoReflect.Descriptor instead.
func (*SISRRuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{2}
}

func (x *SISRRuinStrategy) GetMaxRemovedSequenceSize() uint32 {
	if x != nil && x.MaxRemovedSequenceSize != nil {
		return *x.MaxRemovedSequenceSize
	}
	return 0
}

func (x *SISRRuinStrategy) GetAvgNumRemovedVisits() uint32 {
	if x != nil && x.AvgNumRemovedVisits != nil {
		return *x.AvgNumRemovedVisits
	}
	return 0
}

func (x *SISRRuinStrategy) GetBypassFactor() float64 {
	if x != nil && x.BypassFactor != nil {
		return *x.BypassFactor
	}
	return 0
}

// Ruin strategies, used in perturbation based on ruin and recreate approaches.
type RuinStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Strategy:
	//
	//	*RuinStrategy_SpatiallyCloseRoutes
	//	*RuinStrategy_RandomWalk
	//	*RuinStrategy_Sisr
	Strategy      isRuinStrategy_Strategy `protobuf_oneof:"strategy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuinStrategy) Reset() {
	*x = RuinStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinStrategy) ProtoMessage() {}

func (x *RuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinStrategy.ProtoReflect.Descriptor instead.
func (*RuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{3}
}

func (x *RuinStrategy) GetStrategy() isRuinStrategy_Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *RuinStrategy) GetSpatiallyCloseRoutes() *SpatiallyCloseRoutesRuinStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*RuinStrategy_SpatiallyCloseRoutes); ok {
			return x.SpatiallyCloseRoutes
		}
	}
	return nil
}

func (x *RuinStrategy) GetRandomWalk() *RandomWalkRuinStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*RuinStrategy_RandomWalk); ok {
			return x.RandomWalk
		}
	}
	return nil
}

func (x *RuinStrategy) GetSisr() *SISRRuinStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*RuinStrategy_Sisr); ok {
			return x.Sisr
		}
	}
	return nil
}

type isRuinStrategy_Strategy interface {
	isRuinStrategy_Strategy()
}

type RuinStrategy_SpatiallyCloseRoutes struct {
	SpatiallyCloseRoutes *SpatiallyCloseRoutesRuinStrategy `protobuf:"bytes,1,opt,name=spatially_close_routes,json=spatiallyCloseRoutes,proto3,oneof"`
}

type RuinStrategy_RandomWalk struct {
	RandomWalk *RandomWalkRuinStrategy `protobuf:"bytes,2,opt,name=random_walk,json=randomWalk,proto3,oneof"`
}

type RuinStrategy_Sisr struct {
	Sisr *SISRRuinStrategy `protobuf:"bytes,3,opt,name=sisr,proto3,oneof"`
}

func (*RuinStrategy_SpatiallyCloseRoutes) isRuinStrategy_Strategy() {}

func (*RuinStrategy_RandomWalk) isRuinStrategy_Strategy() {}

func (*RuinStrategy_Sisr) isRuinStrategy_Strategy() {}

// Parameters to customize a recreate strategy.
type RecreateParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Parameters:
	//
	//	*RecreateParameters_LocalCheapestInsertion
	//	*RecreateParameters_Savings
	//	*RecreateParameters_GlobalCheapestInsertion
	Parameters    isRecreateParameters_Parameters `protobuf_oneof:"parameters"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecreateParameters) Reset() {
	*x = RecreateParameters{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecreateParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecreateParameters) ProtoMessage() {}

func (x *RecreateParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecreateParameters.ProtoReflect.Descriptor instead.
func (*RecreateParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{4}
}

func (x *RecreateParameters) GetParameters() isRecreateParameters_Parameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *RecreateParameters) GetLocalCheapestInsertion() *LocalCheapestInsertionParameters {
	if x != nil {
		if x, ok := x.Parameters.(*RecreateParameters_LocalCheapestInsertion); ok {
			return x.LocalCheapestInsertion
		}
	}
	return nil
}

func (x *RecreateParameters) GetSavings() *SavingsParameters {
	if x != nil {
		if x, ok := x.Parameters.(*RecreateParameters_Savings); ok {
			return x.Savings
		}
	}
	return nil
}

func (x *RecreateParameters) GetGlobalCheapestInsertion() *GlobalCheapestInsertionParameters {
	if x != nil {
		if x, ok := x.Parameters.(*RecreateParameters_GlobalCheapestInsertion); ok {
			return x.GlobalCheapestInsertion
		}
	}
	return nil
}

type isRecreateParameters_Parameters interface {
	isRecreateParameters_Parameters()
}

type RecreateParameters_LocalCheapestInsertion struct {
	LocalCheapestInsertion *LocalCheapestInsertionParameters `protobuf:"bytes,1,opt,name=local_cheapest_insertion,json=localCheapestInsertion,proto3,oneof"`
}

type RecreateParameters_Savings struct {
	Savings *SavingsParameters `protobuf:"bytes,2,opt,name=savings,proto3,oneof"`
}

type RecreateParameters_GlobalCheapestInsertion struct {
	GlobalCheapestInsertion *GlobalCheapestInsertionParameters `protobuf:"bytes,3,opt,name=global_cheapest_insertion,json=globalCheapestInsertion,proto3,oneof"`
}

func (*RecreateParameters_LocalCheapestInsertion) isRecreateParameters_Parameters() {}

func (*RecreateParameters_Savings) isRecreateParameters_Parameters() {}

func (*RecreateParameters_GlobalCheapestInsertion) isRecreateParameters_Parameters() {}

// Strategy defining how a solution is recreated.
type RecreateStrategy struct {
	state     protoimpl.MessageState       `protogen:"open.v1"`
	Heuristic *FirstSolutionStrategy_Value `protobuf:"varint,1,opt,name=heuristic,proto3,enum=operations_research.FirstSolutionStrategy_Value,oneof" json:"heuristic,omitempty"`
	// The selected parameters should match the chosen recreate heuristic.
	// If not set, the default parameters from the RoutingModel are used.
	Parameters    *RecreateParameters `protobuf:"bytes,2,opt,name=parameters,proto3,oneof" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecreateStrategy) Reset() {
	*x = RecreateStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecreateStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecreateStrategy) ProtoMessage() {}

func (x *RecreateStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecreateStrategy.ProtoReflect.Descriptor instead.
func (*RecreateStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{5}
}

func (x *RecreateStrategy) GetHeuristic() FirstSolutionStrategy_Value {
	if x != nil && x.Heuristic != nil {
		return *x.Heuristic
	}
	return FirstSolutionStrategy_UNSET
}

func (x *RecreateStrategy) GetParameters() *RecreateParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// The ruin composition strategies specifies how ruin are selected at every ILS
// iteration.
type RuinCompositionStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuinCompositionStrategy) Reset() {
	*x = RuinCompositionStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinCompositionStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinCompositionStrategy) ProtoMessage() {}

func (x *RuinCompositionStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinCompositionStrategy.ProtoReflect.Descriptor instead.
func (*RuinCompositionStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{6}
}

// Parameters to configure a perturbation based on a ruin and recreate approach.
type RuinRecreateParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of ruin strategies determining how a reference solution is ruined.
	RuinStrategies []*RuinStrategy `protobuf:"bytes,1,rep,name=ruin_strategies,json=ruinStrategies,proto3" json:"ruin_strategies,omitempty"`
	// The composition strategy to use when combining the given 'ruin_strategies'.
	// Has no effect when ruin_strategies is composed of a single strategy.
	RuinCompositionStrategy RuinCompositionStrategy_Value `protobuf:"varint,2,opt,name=ruin_composition_strategy,json=ruinCompositionStrategy,proto3,enum=operations_research.RuinCompositionStrategy_Value" json:"ruin_composition_strategy,omitempty"`
	// Strategy defining how a reference solution is recreated.
	RecreateStrategy *RecreateStrategy `protobuf:"bytes,3,opt,name=recreate_strategy,json=recreateStrategy,proto3" json:"recreate_strategy,omitempty"`
	// Ratio in [0, 1] of non start/end nodes to consider as neighbors for the
	// identification of routes spatially close to a non start/end seed node.
	//
	// In particular, given a non start/end seed node s served by route r, we say
	// that a route r' is spatially close to the seed node s if there is at
	// least one non start/end node s' among the neighbors of s, such that s' is
	// served by r'.
	//
	// The neighbors_ratio is coupled with the corresponding min_neighbors and
	// max_neighbors values, defining the minimum and maximum number of neighbor
	// nodes considered for a given seed node:
	// num_neighbors = min(max_neighbors,
	//
	//	max(min_neighbors, neighbors_ratio * NUM_NON_START_END_NODES))
	//
	// Neighbors ratio, and minimum and maximum number of non start/end neighbor
	// nodes for the identification of spatially close routes.
	RouteSelectionNeighborsRatio *float64 `protobuf:"fixed64,4,opt,name=route_selection_neighbors_ratio,json=routeSelectionNeighborsRatio,proto3,oneof" json:"route_selection_neighbors_ratio,omitempty"`
	RouteSelectionMinNeighbors   *uint32  `protobuf:"varint,5,opt,name=route_selection_min_neighbors,json=routeSelectionMinNeighbors,proto3,oneof" json:"route_selection_min_neighbors,omitempty"`
	RouteSelectionMaxNeighbors   *uint32  `protobuf:"varint,6,opt,name=route_selection_max_neighbors,json=routeSelectionMaxNeighbors,proto3,oneof" json:"route_selection_max_neighbors,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RuinRecreateParameters) Reset() {
	*x = RuinRecreateParameters{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinRecreateParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinRecreateParameters) ProtoMessage() {}

func (x *RuinRecreateParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinRecreateParameters.ProtoReflect.Descriptor instead.
func (*RuinRecreateParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{7}
}

func (x *RuinRecreateParameters) GetRuinStrategies() []*RuinStrategy {
	if x != nil {
		return x.RuinStrategies
	}
	return nil
}

func (x *RuinRecreateParameters) GetRuinCompositionStrategy() RuinCompositionStrategy_Value {
	if x != nil {
		return x.RuinCompositionStrategy
	}
	return RuinCompositionStrategy_UNSET
}

func (x *RuinRecreateParameters) GetRecreateStrategy() *RecreateStrategy {
	if x != nil {
		return x.RecreateStrategy
	}
	return nil
}

func (x *RuinRecreateParameters) GetRouteSelectionNeighborsRatio() float64 {
	if x != nil && x.RouteSelectionNeighborsRatio != nil {
		return *x.RouteSelectionNeighborsRatio
	}
	return 0
}

func (x *RuinRecreateParameters) GetRouteSelectionMinNeighbors() uint32 {
	if x != nil && x.RouteSelectionMinNeighbors != nil {
		return *x.RouteSelectionMinNeighbors
	}
	return 0
}

func (x *RuinRecreateParameters) GetRouteSelectionMaxNeighbors() uint32 {
	if x != nil && x.RouteSelectionMaxNeighbors != nil {
		return *x.RouteSelectionMaxNeighbors
	}
	return 0
}

// Defines how a reference solution is perturbed.
type PerturbationStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerturbationStrategy) Reset() {
	*x = PerturbationStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerturbationStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerturbationStrategy) ProtoMessage() {}

func (x *PerturbationStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerturbationStrategy.ProtoReflect.Descriptor instead.
func (*PerturbationStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{8}
}

// The cooling schedule strategy defines how to compute the current simulated
// annealing temperature t given
// - the initial temperature t0
// - the final temperature t1
// - the current search progress 0 <= p <= 1
//
// The value of t0 and t1 is defined by the initial_temperature and
// final_temperature in SimulatedAnnealingParameters, respectively.
//
// The search progress p is derived, at any given time, by the search limits.
// In particular, p measures how far we are in the search process w.r.t. to the
// number of explored solutions and the time limit.
//
// The temperature t, computed according to one of the strategies defined below,
// together with the selected AcceptanceStrategy, is used to guide the search
// trajectory. In particular, given a neighbor solution S', generated by the
// the application of the perturbation and improvement step to a reference
// solution S, we have that S will be replaced by S' iff
//
//	cost(S') + t * log(U(0, 1)) < cost(S)
//
// where U(0, 1) is a random number sampled from a uniform distribution of real
// numbers in [0, 1].
type CoolingScheduleStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoolingScheduleStrategy) Reset() {
	*x = CoolingScheduleStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoolingScheduleStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoolingScheduleStrategy) ProtoMessage() {}

func (x *CoolingScheduleStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoolingScheduleStrategy.ProtoReflect.Descriptor instead.
func (*CoolingScheduleStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{9}
}

// Acceptance strategy in which only improving solutions are accepted.
type GreedyDescentAcceptanceStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreedyDescentAcceptanceStrategy) Reset() {
	*x = GreedyDescentAcceptanceStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreedyDescentAcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreedyDescentAcceptanceStrategy) ProtoMessage() {}

func (x *GreedyDescentAcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreedyDescentAcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*GreedyDescentAcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{10}
}

// Acceptance strategy in which solutions are accepted with a probability that
// depends on its quality and on the current state of the search.
type SimulatedAnnealingAcceptanceStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Determines the speed at which the temperature changes from initial to
	// final.
	CoolingScheduleStrategy CoolingScheduleStrategy_Value `protobuf:"varint,1,opt,name=cooling_schedule_strategy,json=coolingScheduleStrategy,proto3,enum=operations_research.CoolingScheduleStrategy_Value" json:"cooling_schedule_strategy,omitempty"`
	// The initial temperature. See CoolingScheduleStrategy for its usage.
	InitialTemperature *float64 `protobuf:"fixed64,2,opt,name=initial_temperature,json=initialTemperature,proto3,oneof" json:"initial_temperature,omitempty"`
	// The final temperature. See CoolingScheduleStrategy for its usage.
	FinalTemperature *float64 `protobuf:"fixed64,3,opt,name=final_temperature,json=finalTemperature,proto3,oneof" json:"final_temperature,omitempty"`
	// Automatically define the value for the temperatures as follows.
	// First, a  reference temperature t is defined as
	//
	//	w1 * c1 + w2 * c2 + ... + wK * cK
	//
	// where 0 < wJ <= 1 is the fraction of vehicles of cost class J and cJ is the
	// average arc cost for the cost class J.
	// The value of cJ is identified by randomly sampling N arc costs for the cost
	// class J, where N is equal to the number of instance nodes.
	// The initial and final temperatures are then defined as
	// - initial_temperature: 0.1 * t
	// - final_temperature: 0.001 * t
	AutomaticTemperatures *bool `protobuf:"varint,4,opt,name=automatic_temperatures,json=automaticTemperatures,proto3,oneof" json:"automatic_temperatures,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SimulatedAnnealingAcceptanceStrategy) Reset() {
	*x = SimulatedAnnealingAcceptanceStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatedAnnealingAcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatedAnnealingAcceptanceStrategy) ProtoMessage() {}

func (x *SimulatedAnnealingAcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatedAnnealingAcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*SimulatedAnnealingAcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{11}
}

func (x *SimulatedAnnealingAcceptanceStrategy) GetCoolingScheduleStrategy() CoolingScheduleStrategy_Value {
	if x != nil {
		return x.CoolingScheduleStrategy
	}
	return CoolingScheduleStrategy_UNSET
}

func (x *SimulatedAnnealingAcceptanceStrategy) GetInitialTemperature() float64 {
	if x != nil && x.InitialTemperature != nil {
		return *x.InitialTemperature
	}
	return 0
}

func (x *SimulatedAnnealingAcceptanceStrategy) GetFinalTemperature() float64 {
	if x != nil && x.FinalTemperature != nil {
		return *x.FinalTemperature
	}
	return 0
}

func (x *SimulatedAnnealingAcceptanceStrategy) GetAutomaticTemperatures() bool {
	if x != nil && x.AutomaticTemperatures != nil {
		return *x.AutomaticTemperatures
	}
	return false
}

// Acceptance strategy in which a solution is accepted only if all nodes
// are performed. Disjunctions are respected when several nodes can be
// performed.
type AllNodesPerformedAcceptanceStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNodesPerformedAcceptanceStrategy) Reset() {
	*x = AllNodesPerformedAcceptanceStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNodesPerformedAcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNodesPerformedAcceptanceStrategy) ProtoMessage() {}

func (x *AllNodesPerformedAcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNodesPerformedAcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*AllNodesPerformedAcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{12}
}

// Acceptance strategy in which a solution is accepted only if it performs at
// least one more node than the reference solution.
type MoreNodesPerformedAcceptanceStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoreNodesPerformedAcceptanceStrategy) Reset() {
	*x = MoreNodesPerformedAcceptanceStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoreNodesPerformedAcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoreNodesPerformedAcceptanceStrategy) ProtoMessage() {}

func (x *MoreNodesPerformedAcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoreNodesPerformedAcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*MoreNodesPerformedAcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{13}
}

// Acceptance strategy in which a solution is accepted only if it has less
// absences than the reference solution (see Slack Induction by String Removals
// for Vehicle Routing Problems" Christiaens and Vanden Berghe, Transportation
// Science 2020).
//
// In particular, for each node n, the number of solutions where n was not
// performed by any route is tracked by a counter absences[n]. A candidate is
// accepted if
//
//	sum(absences[n]) < sum(absences[m])
//
// with
//
//	n in unperformed(candidate)
//	m in unperformed(reference)
//
// The counter absences is increased after every ILS iteration for the
// unperformed nodes in the reference solution. In addition, when
// remove_route_with_lowest_absences is true and a new best found solution is
// found, the route with the lowest sum of absences is removed from the
// reference solution.
type AbsencesBasedAcceptanceStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, when a new best solution is found, the route with the lowest sum
	// of absences is removed from the reference solution.
	RemoveRouteWithLowestAbsences *bool `protobuf:"varint,1,opt,name=remove_route_with_lowest_absences,json=removeRouteWithLowestAbsences,proto3,oneof" json:"remove_route_with_lowest_absences,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AbsencesBasedAcceptanceStrategy) Reset() {
	*x = AbsencesBasedAcceptanceStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsencesBasedAcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsencesBasedAcceptanceStrategy) ProtoMessage() {}

func (x *AbsencesBasedAcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsencesBasedAcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*AbsencesBasedAcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{14}
}

func (x *AbsencesBasedAcceptanceStrategy) GetRemoveRouteWithLowestAbsences() bool {
	if x != nil && x.RemoveRouteWithLowestAbsences != nil {
		return *x.RemoveRouteWithLowestAbsences
	}
	return false
}

// Determines when a candidate solution replaces another one.
type AcceptanceStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Strategy:
	//
	//	*AcceptanceStrategy_GreedyDescent
	//	*AcceptanceStrategy_SimulatedAnnealing
	//	*AcceptanceStrategy_AllNodesPerformed
	//	*AcceptanceStrategy_MoreNodesPerformed
	//	*AcceptanceStrategy_AbsencesBased
	Strategy      isAcceptanceStrategy_Strategy `protobuf_oneof:"strategy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptanceStrategy) Reset() {
	*x = AcceptanceStrategy{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptanceStrategy) ProtoMessage() {}

func (x *AcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*AcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{15}
}

func (x *AcceptanceStrategy) GetStrategy() isAcceptanceStrategy_Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *AcceptanceStrategy) GetGreedyDescent() *GreedyDescentAcceptanceStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*AcceptanceStrategy_GreedyDescent); ok {
			return x.GreedyDescent
		}
	}
	return nil
}

func (x *AcceptanceStrategy) GetSimulatedAnnealing() *SimulatedAnnealingAcceptanceStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*AcceptanceStrategy_SimulatedAnnealing); ok {
			return x.SimulatedAnnealing
		}
	}
	return nil
}

func (x *AcceptanceStrategy) GetAllNodesPerformed() *AllNodesPerformedAcceptanceStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*AcceptanceStrategy_AllNodesPerformed); ok {
			return x.AllNodesPerformed
		}
	}
	return nil
}

func (x *AcceptanceStrategy) GetMoreNodesPerformed() *MoreNodesPerformedAcceptanceStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*AcceptanceStrategy_MoreNodesPerformed); ok {
			return x.MoreNodesPerformed
		}
	}
	return nil
}

func (x *AcceptanceStrategy) GetAbsencesBased() *AbsencesBasedAcceptanceStrategy {
	if x != nil {
		if x, ok := x.Strategy.(*AcceptanceStrategy_AbsencesBased); ok {
			return x.AbsencesBased
		}
	}
	return nil
}

type isAcceptanceStrategy_Strategy interface {
	isAcceptanceStrategy_Strategy()
}

type AcceptanceStrategy_GreedyDescent struct {
	GreedyDescent *GreedyDescentAcceptanceStrategy `protobuf:"bytes,1,opt,name=greedy_descent,json=greedyDescent,proto3,oneof"`
}

type AcceptanceStrategy_SimulatedAnnealing struct {
	SimulatedAnnealing *SimulatedAnnealingAcceptanceStrategy `protobuf:"bytes,2,opt,name=simulated_annealing,json=simulatedAnnealing,proto3,oneof"`
}

type AcceptanceStrategy_AllNodesPerformed struct {
	AllNodesPerformed *AllNodesPerformedAcceptanceStrategy `protobuf:"bytes,3,opt,name=all_nodes_performed,json=allNodesPerformed,proto3,oneof"`
}

type AcceptanceStrategy_MoreNodesPerformed struct {
	MoreNodesPerformed *MoreNodesPerformedAcceptanceStrategy `protobuf:"bytes,4,opt,name=more_nodes_performed,json=moreNodesPerformed,proto3,oneof"`
}

type AcceptanceStrategy_AbsencesBased struct {
	AbsencesBased *AbsencesBasedAcceptanceStrategy `protobuf:"bytes,5,opt,name=absences_based,json=absencesBased,proto3,oneof"`
}

func (*AcceptanceStrategy_GreedyDescent) isAcceptanceStrategy_Strategy() {}

func (*AcceptanceStrategy_SimulatedAnnealing) isAcceptanceStrategy_Strategy() {}

func (*AcceptanceStrategy_AllNodesPerformed) isAcceptanceStrategy_Strategy() {}

func (*AcceptanceStrategy_MoreNodesPerformed) isAcceptanceStrategy_Strategy() {}

func (*AcceptanceStrategy_AbsencesBased) isAcceptanceStrategy_Strategy() {}

// Specifies the behavior of a search based on ILS.
type IteratedLocalSearchParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Determines how a reference solution S is perturbed to obtain a neighbor
	// solution S'.
	PerturbationStrategy PerturbationStrategy_Value `protobuf:"varint,1,opt,name=perturbation_strategy,json=perturbationStrategy,proto3,enum=operations_research.PerturbationStrategy_Value" json:"perturbation_strategy,omitempty"`
	// Parameters to customize a ruin and recreate perturbation.
	RuinRecreateParameters *RuinRecreateParameters `protobuf:"bytes,2,opt,name=ruin_recreate_parameters,json=ruinRecreateParameters,proto3" json:"ruin_recreate_parameters,omitempty"`
	// Determines whether solution S', obtained from the perturbation, should be
	// optimized with a local search application.
	ImprovePerturbedSolution *bool `protobuf:"varint,3,opt,name=improve_perturbed_solution,json=improvePerturbedSolution,proto3,oneof" json:"improve_perturbed_solution,omitempty"`
	// Determines when the neighbor solution S', possibly improved if
	// `improve_perturbed_solution` is true, replaces the reference solution S.
	ReferenceSolutionAcceptanceStrategy *AcceptanceStrategy `protobuf:"bytes,4,opt,name=reference_solution_acceptance_strategy,json=referenceSolutionAcceptanceStrategy,proto3" json:"reference_solution_acceptance_strategy,omitempty"`
	// Determines when the neighbor solution S' replaces the best solution found
	// so far.
	BestSolutionAcceptanceStrategy *AcceptanceStrategy `protobuf:"bytes,5,opt,name=best_solution_acceptance_strategy,json=bestSolutionAcceptanceStrategy,proto3" json:"best_solution_acceptance_strategy,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *IteratedLocalSearchParameters) Reset() {
	*x = IteratedLocalSearchParameters{}
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IteratedLocalSearchParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IteratedLocalSearchParameters) ProtoMessage() {}

func (x *IteratedLocalSearchParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IteratedLocalSearchParameters.ProtoReflect.Descriptor instead.
func (*IteratedLocalSearchParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{16}
}

func (x *IteratedLocalSearchParameters) GetPerturbationStrategy() PerturbationStrategy_Value {
	if x != nil {
		return x.PerturbationStrategy
	}
	return PerturbationStrategy_UNSET
}

func (x *IteratedLocalSearchParameters) GetRuinRecreateParameters() *RuinRecreateParameters {
	if x != nil {
		return x.RuinRecreateParameters
	}
	return nil
}

func (x *IteratedLocalSearchParameters) GetImprovePerturbedSolution() bool {
	if x != nil && x.ImprovePerturbedSolution != nil {
		return *x.ImprovePerturbedSolution
	}
	return false
}

func (x *IteratedLocalSearchParameters) GetReferenceSolutionAcceptanceStrategy() *AcceptanceStrategy {
	if x != nil {
		return x.ReferenceSolutionAcceptanceStrategy
	}
	return nil
}

func (x *IteratedLocalSearchParameters) GetBestSolutionAcceptanceStrategy() *AcceptanceStrategy {
	if x != nil {
		return x.BestSolutionAcceptanceStrategy
	}
	return nil
}

var File_ortools_constraint_solver_routing_ils_proto protoreflect.FileDescriptor

const file_ortools_constraint_solver_routing_ils_proto_rawDesc = "" +
	"\n" +
	"+ortools/constraint_solver/routing_ils.proto\x12\x13operations_research\x1a-ortools/constraint_solver/routing_enums.proto\x1a<ortools/constraint_solver/routing_heuristic_parameters.proto\"i\n" +
	" SpatiallyCloseRoutesRuinStrategy\x12/\n" +
	"\x11num_ruined_routes\x18\x03 \x01(\rH\x00R\x0fnumRuinedRoutes\x88\x01\x01B\x14\n" +
	"\x12_num_ruined_routes\"b\n" +
	"\x16RandomWalkRuinStrategy\x121\n" +
	"\x12num_removed_visits\x18\a \x01(\rH\x00R\x10numRemovedVisits\x88\x01\x01B\x15\n" +
	"\x13_num_removed_visits\"\x81\x02\n" +
	"\x10SISRRuinStrategy\x12>\n" +
	"\x19max_removed_sequence_size\x18\x01 \x01(\rH\x00R\x16maxRemovedSequenceSize\x88\x01\x01\x128\n" +
	"\x16avg_num_removed_visits\x18\x02 \x01(\rH\x01R\x13avgNumRemovedVisits\x88\x01\x01\x12(\n" +
	"\rbypass_factor\x18\x03 \x01(\x01H\x02R\fbypassFactor\x88\x01\x01B\x1c\n" +
	"\x1a_max_removed_sequence_sizeB\x19\n" +
	"\x17_avg_num_removed_visitsB\x10\n" +
	"\x0e_bypass_factor\"\x96\x02\n" +
	"\fRuinStrategy\x12m\n" +
	"\x16spatially_close_routes\x18\x01 \x01(\v25.operations_research.SpatiallyCloseRoutesRuinStrategyH\x00R\x14spatiallyCloseRoutes\x12N\n" +
	"\vrandom_walk\x18\x02 \x01(\v2+.operations_research.RandomWalkRuinStrategyH\x00R\n" +
	"randomWalk\x12;\n" +
	"\x04sisr\x18\x03 \x01(\v2%.operations_research.SISRRuinStrategyH\x00R\x04sisrB\n" +
	"\n" +
	"\bstrategy\"\xcf\x02\n" +
	"\x12RecreateParameters\x12q\n" +
	"\x18local_cheapest_insertion\x18\x01 \x01(\v25.operations_research.LocalCheapestInsertionParametersH\x00R\x16localCheapestInsertion\x12B\n" +
	"\asavings\x18\x02 \x01(\v2&.operations_research.SavingsParametersH\x00R\asavings\x12t\n" +
	"\x19global_cheapest_insertion\x18\x03 \x01(\v26.operations_research.GlobalCheapestInsertionParametersH\x00R\x17globalCheapestInsertionB\f\n" +
	"\n" +
	"parameters\"\xd2\x01\n" +
	"\x10RecreateStrategy\x12S\n" +
	"\theuristic\x18\x01 \x01(\x0e20.operations_research.FirstSolutionStrategy.ValueH\x00R\theuristic\x88\x01\x01\x12L\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2'.operations_research.RecreateParametersH\x01R\n" +
	"parameters\x88\x01\x01B\f\n" +
	"\n" +
	"_heuristicB\r\n" +
	"\v_parameters\"s\n" +
	"\x17RuinCompositionStrategy\"X\n" +
	"\x05Value\x12\t\n" +
	"\x05UNSET\x10\x00\x12\x18\n" +
	"\x14RUN_ALL_SEQUENTIALLY\x10\x01\x12\x14\n" +
	"\x10RUN_ALL_RANDOMLY\x10\x02\x12\x14\n" +
	"\x10RUN_ONE_RANDOMLY\x10\x03\"\xec\x04\n" +
	"\x16RuinRecreateParameters\x12J\n" +
	"\x0fruin_strategies\x18\x01 \x03(\v2!.operations_research.RuinStrategyR\x0eruinStrategies\x12n\n" +
	"\x19ruin_composition_strategy\x18\x02 \x01(\x0e22.operations_research.RuinCompositionStrategy.ValueR\x17ruinCompositionStrategy\x12R\n" +
	"\x11recreate_strategy\x18\x03 \x01(\v2%.operations_research.RecreateStrategyR\x10recreateStrategy\x12J\n" +
	"\x1froute_selection_neighbors_ratio\x18\x04 \x01(\x01H\x00R\x1crouteSelectionNeighborsRatio\x88\x01\x01\x12F\n" +
	"\x1droute_selection_min_neighbors\x18\x05 \x01(\rH\x01R\x1arouteSelectionMinNeighbors\x88\x01\x01\x12F\n" +
	"\x1droute_selection_max_neighbors\x18\x06 \x01(\rH\x02R\x1arouteSelectionMaxNeighbors\x88\x01\x01B\"\n" +
	" _route_selection_neighbors_ratioB \n" +
	"\x1e_route_selection_min_neighborsB \n" +
	"\x1e_route_selection_max_neighbors\"A\n" +
	"\x14PerturbationStrategy\")\n" +
	"\x05Value\x12\t\n" +
	"\x05UNSET\x10\x00\x12\x15\n" +
	"\x11RUIN_AND_RECREATE\x10\x01\"J\n" +
	"\x17CoolingScheduleStrategy\"/\n" +
	"\x05Value\x12\t\n" +
	"\x05UNSET\x10\x00\x12\x0f\n" +
	"\vEXPONENTIAL\x10\x01\x12\n" +
	"\n" +
	"\x06LINEAR\x10\x02\"!\n" +
	"\x1fGreedyDescentAcceptanceStrategy\"\x83\x03\n" +
	"$SimulatedAnnealingAcceptanceStrategy\x12n\n" +
	"\x19cooling_schedule_strategy\x18\x01 \x01(\x0e22.operations_research.CoolingScheduleStrategy.ValueR\x17coolingScheduleStrategy\x124\n" +
	"\x13initial_temperature\x18\x02 \x01(\x01H\x00R\x12initialTemperature\x88\x01\x01\x120\n" +
	"\x11final_temperature\x18\x03 \x01(\x01H\x01R\x10finalTemperature\x88\x01\x01\x12:\n" +
	"\x16automatic_temperatures\x18\x04 \x01(\bH\x02R\x15automaticTemperatures\x88\x01\x01B\x16\n" +
	"\x14_initial_temperatureB\x14\n" +
	"\x12_final_temperatureB\x19\n" +
	"\x17_automatic_temperatures\"%\n" +
	"#AllNodesPerformedAcceptanceStrategy\"&\n" +
	"$MoreNodesPerformedAcceptanceStrategy\"\x96\x01\n" +
	"\x1fAbsencesBasedAcceptanceStrategy\x12M\n" +
	"!remove_route_with_lowest_absences\x18\x01 \x01(\bH\x00R\x1dremoveRouteWithLowestAbsences\x88\x01\x01B$\n" +
	"\"_remove_route_with_lowest_absences\"\xa7\x04\n" +
	"\x12AcceptanceStrategy\x12]\n" +
	"\x0egreedy_descent\x18\x01 \x01(\v24.operations_research.GreedyDescentAcceptanceStrategyH\x00R\rgreedyDescent\x12l\n" +
	"\x13simulated_annealing\x18\x02 \x01(\v29.operations_research.SimulatedAnnealingAcceptanceStrategyH\x00R\x12simulatedAnnealing\x12j\n" +
	"\x13all_nodes_performed\x18\x03 \x01(\v28.operations_research.AllNodesPerformedAcceptanceStrategyH\x00R\x11allNodesPerformed\x12m\n" +
	"\x14more_nodes_performed\x18\x04 \x01(\v29.operations_research.MoreNodesPerformedAcceptanceStrategyH\x00R\x12moreNodesPerformed\x12]\n" +
	"\x0eabsences_based\x18\x05 \x01(\v24.operations_research.AbsencesBasedAcceptanceStrategyH\x00R\rabsencesBasedB\n" +
	"\n" +
	"\bstrategy\"\xc0\x04\n" +
	"\x1dIteratedLocalSearchParameters\x12d\n" +
	"\x15perturbation_strategy\x18\x01 \x01(\x0e2/.operations_research.PerturbationStrategy.ValueR\x14perturbationStrategy\x12e\n" +
	"\x18ruin_recreate_parameters\x18\x02 \x01(\v2+.operations_research.RuinRecreateParametersR\x16ruinRecreateParameters\x12A\n" +
	"\x1aimprove_perturbed_solution\x18\x03 \x01(\bH\x00R\x18improvePerturbedSolution\x88\x01\x01\x12|\n" +
	"&reference_solution_acceptance_strategy\x18\x04 \x01(\v2'.operations_research.AcceptanceStrategyR#referenceSolutionAcceptanceStrategy\x12r\n" +
	"!best_solution_acceptance_strategy\x18\x05 \x01(\v2'.operations_research.AcceptanceStrategyR\x1ebestSolutionAcceptanceStrategyB\x1d\n" +
	"\x1b_improve_perturbed_solutionB\x8f\x01\n" +
	"#com.google.ortools.constraintsolverP\x01ZDgithub.com/airspacetechnologies/or-tools/go/ortools/constraintsolver\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3"

var (
	file_ortools_constraint_solver_routing_ils_proto_rawDescOnce sync.Once
	file_ortools_constraint_solver_routing_ils_proto_rawDescData []byte
)

func file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP() []byte {
	file_ortools_constraint_solver_routing_ils_proto_rawDescOnce.Do(func() {
		file_ortools_constraint_solver_routing_ils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_ils_proto_rawDesc), len(file_ortools_constraint_solver_routing_ils_proto_rawDesc)))
	})
	return file_ortools_constraint_solver_routing_ils_proto_rawDescData
}

var file_ortools_constraint_solver_routing_ils_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ortools_constraint_solver_routing_ils_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ortools_constraint_solver_routing_ils_proto_goTypes = []any{
	(RuinCompositionStrategy_Value)(0),           // 0: operations_research.RuinCompositionStrategy.Value
	(PerturbationStrategy_Value)(0),              // 1: operations_research.PerturbationStrategy.Value
	(CoolingScheduleStrategy_Value)(0),           // 2: operations_research.CoolingScheduleStrategy.Value
	(*SpatiallyCloseRoutesRuinStrategy)(nil),     // 3: operations_research.SpatiallyCloseRoutesRuinStrategy
	(*RandomWalkRuinStrategy)(nil),               // 4: operations_research.RandomWalkRuinStrategy
	(*SISRRuinStrategy)(nil),                     // 5: operations_research.SISRRuinStrategy
	(*RuinStrategy)(nil),                         // 6: operations_research.RuinStrategy
	(*RecreateParameters)(nil),                   // 7: operations_research.RecreateParameters
	(*RecreateStrategy)(nil),                     // 8: operations_research.RecreateStrategy
	(*RuinCompositionStrategy)(nil),              // 9: operations_research.RuinCompositionStrategy
	(*RuinRecreateParameters)(nil),               // 10: operations_research.RuinRecreateParameters
	(*PerturbationStrategy)(nil),                 // 11: operations_research.PerturbationStrategy
	(*CoolingScheduleStrategy)(nil),              // 12: operations_research.CoolingScheduleStrategy
	(*GreedyDescentAcceptanceStrategy)(nil),      // 13: operations_research.GreedyDescentAcceptanceStrategy
	(*SimulatedAnnealingAcceptanceStrategy)(nil), // 14: operations_research.SimulatedAnnealingAcceptanceStrategy
	(*AllNodesPerformedAcceptanceStrategy)(nil),  // 15: operations_research.AllNodesPerformedAcceptanceStrategy
	(*MoreNodesPerformedAcceptanceStrategy)(nil), // 16: operations_research.MoreNodesPerformedAcceptanceStrategy
	(*AbsencesBasedAcceptanceStrategy)(nil),      // 17: operations_research.AbsencesBasedAcceptanceStrategy
	(*AcceptanceStrategy)(nil),                   // 18: operations_research.AcceptanceStrategy
	(*IteratedLocalSearchParameters)(nil),        // 19: operations_research.IteratedLocalSearchParameters
	(*LocalCheapestInsertionParameters)(nil),     // 20: operations_research.LocalCheapestInsertionParameters
	(*SavingsParameters)(nil),                    // 21: operations_research.SavingsParameters
	(*GlobalCheapestInsertionParameters)(nil),    // 22: operations_research.GlobalCheapestInsertionParameters
	(FirstSolutionStrategy_Value)(0),             // 23: operations_research.FirstSolutionStrategy.Value
}
var file_ortools_constraint_solver_routing_ils_proto_depIdxs = []int32{
	3,  // 0: operations_research.RuinStrategy.spatially_close_routes:type_name -> operations_research.SpatiallyCloseRoutesRuinStrategy
	4,  // 1: operations_research.RuinStrategy.random_walk:type_name -> operations_research.RandomWalkRuinStrategy
	5,  // 2: operations_research.RuinStrategy.sisr:type_name -> operations_research.SISRRuinStrategy
	20, // 3: operations_research.RecreateParameters.local_cheapest_insertion:type_name -> operations_research.LocalCheapestInsertionParameters
	21, // 4: operations_research.RecreateParameters.savings:type_name -> operations_research.SavingsParameters
	22, // 5: operations_research.RecreateParameters.global_cheapest_insertion:type_name -> operations_research.GlobalCheapestInsertionParameters
	23, // 6: operations_research.RecreateStrategy.heuristic:type_name -> operations_research.FirstSolutionStrategy.Value
	7,  // 7: operations_research.RecreateStrategy.parameters:type_name -> operations_research.RecreateParameters
	6,  // 8: operations_research.RuinRecreateParameters.ruin_strategies:type_name -> operations_research.RuinStrategy
	0,  // 9: operations_research.RuinRecreateParameters.ruin_composition_strategy:type_name -> operations_research.RuinCompositionStrategy.Value
	8,  // 10: operations_research.RuinRecreateParameters.recreate_strategy:type_name -> operations_research.RecreateStrategy
	2,  // 11: operations_research.SimulatedAnnealingAcceptanceStrategy.cooling_schedule_strategy:type_name -> operations_research.CoolingScheduleStrategy.Value
	13, // 12: operations_research.AcceptanceStrategy.greedy_descent:type_name -> operations_research.GreedyDescentAcceptanceStrategy
	14, // 13: operations_research.AcceptanceStrategy.simulated_annealing:type_name -> operations_research.SimulatedAnnealingAcceptanceStrategy
	15, // 14: operations_research.AcceptanceStrategy.all_nodes_performed:type_name -> operations_research.AllNodesPerformedAcceptanceStrategy
	16, // 15: operations_research.AcceptanceStrategy.more_nodes_performed:type_name -> operations_research.MoreNodesPerformedAcceptanceStrategy
	17, // 16: operations_research.AcceptanceStrategy.absences_based:type_name -> operations_research.AbsencesBasedAcceptanceStrategy
	1,  // 17: operations_research.IteratedLocalSearchParameters.perturbation_strategy:type_name -> operations_research.PerturbationStrategy.Value
	10, // 18: operations_research.IteratedLocalSearchParameters.ruin_recreate_parameters:type_name -> operations_research.RuinRecreateParameters
	18, // 19: operations_research.IteratedLocalSearchParameters.reference_solution_acceptance_strategy:type_name -> operations_research.AcceptanceStrategy
	18, // 20: operations_research.IteratedLocalSearchParameters.best_solution_acceptance_strategy:type_name -> operations_research.AcceptanceStrategy
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ortools_constraint_solver_routing_ils_proto_init() }
func file_ortools_constraint_solver_routing_ils_proto_init() {
	if File_ortools_constraint_solver_routing_ils_proto != nil {
		return
	}
	file_ortools_constraint_solver_routing_enums_proto_init()
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_init()
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[0].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[1].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[2].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[3].OneofWrappers = []any{
		(*RuinStrategy_SpatiallyCloseRoutes)(nil),
		(*RuinStrategy_RandomWalk)(nil),
		(*RuinStrategy_Sisr)(nil),
	}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[4].OneofWrappers = []any{
		(*RecreateParameters_LocalCheapestInsertion)(nil),
		(*RecreateParameters_Savings)(nil),
		(*RecreateParameters_GlobalCheapestInsertion)(nil),
	}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[5].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[7].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[11].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[14].OneofWrappers = []any{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[15].OneofWrappers = []any{
		(*AcceptanceStrategy_GreedyDescent)(nil),
		(*AcceptanceStrategy_SimulatedAnnealing)(nil),
		(*AcceptanceStrategy_AllNodesPerformed)(nil),
		(*AcceptanceStrategy_MoreNodesPerformed)(nil),
		(*AcceptanceStrategy_AbsencesBased)(nil),
	}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_ils_proto_rawDesc), len(file_ortools_constraint_solver_routing_ils_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_constraint_solver_routing_ils_proto_goTypes,
		DependencyIndexes: file_ortools_constraint_solver_routing_ils_proto_depIdxs,
		EnumInfos:         file_ortools_constraint_solver_routing_ils_proto_enumTypes,
		MessageInfos:      file_ortools_constraint_solver_routing_ils_proto_msgTypes,
	}.Build()
	File_ortools_constraint_solver_routing_ils_proto = out.File
	file_ortools_constraint_solver_routing_ils_proto_goTypes = nil
	file_ortools_constraint_solver_routing_ils_proto_depIdxs = nil
}
