// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer used to parametrize the routing library, in particular the
// search parameters such as first solution heuristics and local search
// neighborhoods.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ortools/constraint_solver/routing_parameters.proto

package constraintsolver

import (
	sat "github.com/airspacetechnologies/or-tools/go/ortools/sat"
	util "github.com/airspacetechnologies/or-tools/go/ortools/util"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Underlying solver to use in dimension scheduling, respectively for
// continuous and mixed models.
type RoutingSearchParameters_SchedulingSolver int32

const (
	RoutingSearchParameters_SCHEDULING_UNSET  RoutingSearchParameters_SchedulingSolver = 0
	RoutingSearchParameters_SCHEDULING_GLOP   RoutingSearchParameters_SchedulingSolver = 1
	RoutingSearchParameters_SCHEDULING_CP_SAT RoutingSearchParameters_SchedulingSolver = 2
)

// Enum value maps for RoutingSearchParameters_SchedulingSolver.
var (
	RoutingSearchParameters_SchedulingSolver_name = map[int32]string{
		0: "SCHEDULING_UNSET",
		1: "SCHEDULING_GLOP",
		2: "SCHEDULING_CP_SAT",
	}
	RoutingSearchParameters_SchedulingSolver_value = map[string]int32{
		"SCHEDULING_UNSET":  0,
		"SCHEDULING_GLOP":   1,
		"SCHEDULING_CP_SAT": 2,
	}
)

func (x RoutingSearchParameters_SchedulingSolver) Enum() *RoutingSearchParameters_SchedulingSolver {
	p := new(RoutingSearchParameters_SchedulingSolver)
	*p = x
	return p
}

func (x RoutingSearchParameters_SchedulingSolver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingSearchParameters_SchedulingSolver) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_parameters_proto_enumTypes[0].Descriptor()
}

func (RoutingSearchParameters_SchedulingSolver) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_parameters_proto_enumTypes[0]
}

func (x RoutingSearchParameters_SchedulingSolver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingSearchParameters_SchedulingSolver.Descriptor instead.
func (RoutingSearchParameters_SchedulingSolver) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_parameters_proto_rawDescGZIP(), []int{0, 0}
}

// Parameters defining the search used to solve vehicle routing problems.
//
// If a parameter is unset (or, equivalently, set to its default value),
// then the routing library will pick its preferred value for that parameter
// automatically: this should be the case for most parameters.
// To see those "default" parameters, call GetDefaultRoutingSearchParameters().
// Next ID: 73
type RoutingSearchParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First solution strategies, used as starting point of local search.
	FirstSolutionStrategy FirstSolutionStrategy_Value `protobuf:"varint,1,opt,name=first_solution_strategy,json=firstSolutionStrategy,proto3,enum=operations_research.FirstSolutionStrategy_Value" json:"first_solution_strategy,omitempty"`
	// --- Advanced first solutions strategy settings ---
	// Don't touch these unless you know what you are doing.
	//
	// Use filtered version of first solution strategy if available.
	UseUnfilteredFirstSolutionStrategy bool `protobuf:"varint,2,opt,name=use_unfiltered_first_solution_strategy,json=useUnfilteredFirstSolutionStrategy,proto3" json:"use_unfiltered_first_solution_strategy,omitempty"`
	// Parameters for the Savings heuristic.
	SavingsParameters *SavingsParameters `protobuf:"bytes,70,opt,name=savings_parameters,json=savingsParameters,proto3" json:"savings_parameters,omitempty"`
	// Parameters for the global cheapest insertion heuristic when used as first
	// solution heuristic.
	GlobalCheapestInsertionFirstSolutionParameters *GlobalCheapestInsertionParameters `protobuf:"bytes,71,opt,name=global_cheapest_insertion_first_solution_parameters,json=globalCheapestInsertionFirstSolutionParameters,proto3" json:"global_cheapest_insertion_first_solution_parameters,omitempty"`
	// Parameters for the global cheapest insertion heuristic when
	// used in a local search operator (see
	// local_search_operators.use_global_cheapest_insertion_path_lns and
	// local_search_operators.use_global_cheapest_insertion_chain_lns below).
	GlobalCheapestInsertionLsOperatorParameters *GlobalCheapestInsertionParameters `protobuf:"bytes,72,opt,name=global_cheapest_insertion_ls_operator_parameters,json=globalCheapestInsertionLsOperatorParameters,proto3" json:"global_cheapest_insertion_ls_operator_parameters,omitempty"`
	// Parameters for the local cheapest insertion heuristic.
	LocalCheapestInsertionParameters *LocalCheapestInsertionParameters `protobuf:"bytes,68,opt,name=local_cheapest_insertion_parameters,json=localCheapestInsertionParameters,proto3" json:"local_cheapest_insertion_parameters,omitempty"`
	// Parameters for the local cheapest cost insertion heuristic.
	LocalCheapestCostInsertionParameters *LocalCheapestInsertionParameters `protobuf:"bytes,69,opt,name=local_cheapest_cost_insertion_parameters,json=localCheapestCostInsertionParameters,proto3" json:"local_cheapest_cost_insertion_parameters,omitempty"`
	// If true use minimum matching instead of minimal matching in the
	// Christofides algorithm.
	ChristofidesUseMinimumMatching bool `protobuf:"varint,30,opt,name=christofides_use_minimum_matching,json=christofidesUseMinimumMatching,proto3" json:"christofides_use_minimum_matching,omitempty"`
	// If non zero, a period p indicates that every p node insertions or additions
	// to a path, an optimization of the current partial solution will be
	// performed. As of 12/2023:
	//   - this requires that a secondary routing model has been passed to the main
	//     one,
	//   - this is only supported by LOCAL_CHEAPEST_INSERTION and
	//
	// LOCAL_CHEAPEST_COST_INSERTION.
	FirstSolutionOptimizationPeriod int32                                                     `protobuf:"varint,59,opt,name=first_solution_optimization_period,json=firstSolutionOptimizationPeriod,proto3" json:"first_solution_optimization_period,omitempty"`
	LocalSearchOperators            *RoutingSearchParameters_LocalSearchNeighborhoodOperators `protobuf:"bytes,3,opt,name=local_search_operators,json=localSearchOperators,proto3" json:"local_search_operators,omitempty"`
	// Neighbors ratio and minimum number of neighbors considered in local
	// search operators (see
	// GlobalCheapestInsertionParameters.neighbors_ratio and
	// GlobalCheapestInsertionParameters.min_neighbors for more
	// information).
	LsOperatorNeighborsRatio float64 `protobuf:"fixed64,53,opt,name=ls_operator_neighbors_ratio,json=lsOperatorNeighborsRatio,proto3" json:"ls_operator_neighbors_ratio,omitempty"`
	LsOperatorMinNeighbors   int32   `protobuf:"varint,54,opt,name=ls_operator_min_neighbors,json=lsOperatorMinNeighbors,proto3" json:"ls_operator_min_neighbors,omitempty"`
	// If true, the solver will use multi-armed bandit concatenate operators. It
	// dynamically chooses the next neighbor operator in order to get the best
	// objective improvement.
	UseMultiArmedBanditConcatenateOperators bool `protobuf:"varint,41,opt,name=use_multi_armed_bandit_concatenate_operators,json=useMultiArmedBanditConcatenateOperators,proto3" json:"use_multi_armed_bandit_concatenate_operators,omitempty"`
	// Memory coefficient related to the multi-armed bandit compound operator.
	// Sets how much the objective improvement of previous accepted neighbors
	// influence the current average improvement.
	// This parameter should be between 0 and 1.
	MultiArmedBanditCompoundOperatorMemoryCoefficient float64 `protobuf:"fixed64,42,opt,name=multi_armed_bandit_compound_operator_memory_coefficient,json=multiArmedBanditCompoundOperatorMemoryCoefficient,proto3" json:"multi_armed_bandit_compound_operator_memory_coefficient,omitempty"`
	// Positive parameter defining the exploration coefficient of the multi-armed
	// bandit compound operator. Sets how often we explore rarely used and
	// unsuccessful in the past operators
	MultiArmedBanditCompoundOperatorExplorationCoefficient float64 `protobuf:"fixed64,43,opt,name=multi_armed_bandit_compound_operator_exploration_coefficient,json=multiArmedBanditCompoundOperatorExplorationCoefficient,proto3" json:"multi_armed_bandit_compound_operator_exploration_coefficient,omitempty"`
	// Maximum size of the chain to make inactive in SwapActiveChainOperator.
	MaxSwapActiveChainSize int32 `protobuf:"varint,66,opt,name=max_swap_active_chain_size,json=maxSwapActiveChainSize,proto3" json:"max_swap_active_chain_size,omitempty"`
	// Number of expensive arcs to consider cutting in the RelocateExpensiveChain
	// neighborhood operator (see
	// LocalSearchNeighborhoodOperators.use_relocate_expensive_chain()).
	// This parameter must be greater than 2.
	// NOTE(user): The number of neighbors generated by the operator for
	// relocate_expensive_chain_num_arcs_to_consider = K is around
	// K*(K-1)/2 * number_of_routes * number_of_nodes.
	RelocateExpensiveChainNumArcsToConsider int32 `protobuf:"varint,20,opt,name=relocate_expensive_chain_num_arcs_to_consider,json=relocateExpensiveChainNumArcsToConsider,proto3" json:"relocate_expensive_chain_num_arcs_to_consider,omitempty"`
	// Number of expensive arcs to consider cutting in the
	// FilteredHeuristicExpensiveChainLNSOperator operator.
	HeuristicExpensiveChainLnsNumArcsToConsider int32 `protobuf:"varint,32,opt,name=heuristic_expensive_chain_lns_num_arcs_to_consider,json=heuristicExpensiveChainLnsNumArcsToConsider,proto3" json:"heuristic_expensive_chain_lns_num_arcs_to_consider,omitempty"`
	// Number of closest nodes to consider for each node during the destruction
	// phase of the FilteredHeuristicCloseNodesLNSOperator.
	HeuristicCloseNodesLnsNumNodes int32 `protobuf:"varint,35,opt,name=heuristic_close_nodes_lns_num_nodes,json=heuristicCloseNodesLnsNumNodes,proto3" json:"heuristic_close_nodes_lns_num_nodes,omitempty"`
	// Local search metaheuristics used to guide the search.
	LocalSearchMetaheuristic LocalSearchMetaheuristic_Value `protobuf:"varint,4,opt,name=local_search_metaheuristic,json=localSearchMetaheuristic,proto3,enum=operations_research.LocalSearchMetaheuristic_Value" json:"local_search_metaheuristic,omitempty"`
	// Local search metaheuristics alternatively used to guide the search. Every
	// num_max_local_optima_before_metaheuristic_switch local minima found by a
	// metaheurisitic, the solver will switch to the next metaheuristic. Cannot be
	// defined if local_search_metaheuristic is different from UNSET or AUTOMATIC.
	LocalSearchMetaheuristics                  []LocalSearchMetaheuristic_Value `protobuf:"varint,63,rep,packed,name=local_search_metaheuristics,json=localSearchMetaheuristics,proto3,enum=operations_research.LocalSearchMetaheuristic_Value" json:"local_search_metaheuristics,omitempty"`
	NumMaxLocalOptimaBeforeMetaheuristicSwitch int32                            `protobuf:"varint,64,opt,name=num_max_local_optima_before_metaheuristic_switch,json=numMaxLocalOptimaBeforeMetaheuristicSwitch,proto3" json:"num_max_local_optima_before_metaheuristic_switch,omitempty"`
	// These are advanced settings which should not be modified unless you know
	// what you are doing.
	// Lambda coefficient used to penalize arc costs when GUIDED_LOCAL_SEARCH is
	// used. Must be positive.
	GuidedLocalSearchLambdaCoefficient float64 `protobuf:"fixed64,5,opt,name=guided_local_search_lambda_coefficient,json=guidedLocalSearchLambdaCoefficient,proto3" json:"guided_local_search_lambda_coefficient,omitempty"`
	// Whether to reset penalties when a new best solution is found. The effect is
	// that a greedy descent is started before the next penalization phase.
	GuidedLocalSearchResetPenaltiesOnNewBestSolution bool `protobuf:"varint,51,opt,name=guided_local_search_reset_penalties_on_new_best_solution,json=guidedLocalSearchResetPenaltiesOnNewBestSolution,proto3" json:"guided_local_search_reset_penalties_on_new_best_solution,omitempty"`
	// When an arc leaving a vehicle start or arriving at a vehicle end is
	// penalized, this field controls whether to penalize all other equivalent
	// arcs with starts or ends in the same vehicle class.
	GuidedLocalSearchPenalizeWithVehicleClasses bool `protobuf:"varint,61,opt,name=guided_local_search_penalize_with_vehicle_classes,json=guidedLocalSearchPenalizeWithVehicleClasses,proto3" json:"guided_local_search_penalize_with_vehicle_classes,omitempty"`
	// Whether to consider arc penalties in cost functions used in local search
	// operators using arc costs.
	UseGuidedLocalSearchPenaltiesInLocalSearchOperators bool `protobuf:"varint,62,opt,name=use_guided_local_search_penalties_in_local_search_operators,json=useGuidedLocalSearchPenaltiesInLocalSearchOperators,proto3" json:"use_guided_local_search_penalties_in_local_search_operators,omitempty"`
	// --- Search control ---
	//
	// If true, the solver should use depth-first search rather than local search
	// to solve the problem.
	UseDepthFirstSearch bool `protobuf:"varint,6,opt,name=use_depth_first_search,json=useDepthFirstSearch,proto3" json:"use_depth_first_search,omitempty"`
	// If true, use the CP solver to find a solution. Either local or depth-first
	// search will be used depending on the value of use_depth_first_search. Will
	// be run before the CP-SAT solver (cf. use_cp_sat).
	UseCp util.OptionalBoolean `protobuf:"varint,28,opt,name=use_cp,json=useCp,proto3,enum=operations_research.OptionalBoolean" json:"use_cp,omitempty"`
	// If true, use the CP-SAT solver to find a solution. If use_cp is also true,
	// the CP-SAT solver will be run after the CP solver if there is time
	// remaining and will use the CP solution as a hint for the CP-SAT search.
	// As of 5/2019, only TSP models can be solved.
	UseCpSat util.OptionalBoolean `protobuf:"varint,27,opt,name=use_cp_sat,json=useCpSat,proto3,enum=operations_research.OptionalBoolean" json:"use_cp_sat,omitempty"`
	// If true, use the CP-SAT solver to find a solution on generalized routing
	// model. If use_cp is also true, the CP-SAT solver will be run after the CP
	// solver if there is time remaining and will use the CP solution as a hint
	// for the CP-SAT search.
	UseGeneralizedCpSat util.OptionalBoolean `protobuf:"varint,47,opt,name=use_generalized_cp_sat,json=useGeneralizedCpSat,proto3,enum=operations_research.OptionalBoolean" json:"use_generalized_cp_sat,omitempty"`
	// If use_cp_sat or use_generalized_cp_sat is true, contains the SAT algorithm
	// parameters which will be used.
	SatParameters *sat.SatParameters `protobuf:"bytes,48,opt,name=sat_parameters,json=satParameters,proto3" json:"sat_parameters,omitempty"`
	// If use_cp_sat or use_generalized_cp_sat is true, will report intermediate
	// solutions found by CP-SAT to solution listeners.
	ReportIntermediateCpSatSolutions bool `protobuf:"varint,56,opt,name=report_intermediate_cp_sat_solutions,json=reportIntermediateCpSatSolutions,proto3" json:"report_intermediate_cp_sat_solutions,omitempty"`
	// If model.Size() is less than the threshold and that no solution has been
	// found, attempt a pass with CP-SAT.
	FallbackToCpSatSizeThreshold int32                                    `protobuf:"varint,52,opt,name=fallback_to_cp_sat_size_threshold,json=fallbackToCpSatSizeThreshold,proto3" json:"fallback_to_cp_sat_size_threshold,omitempty"`
	ContinuousSchedulingSolver   RoutingSearchParameters_SchedulingSolver `protobuf:"varint,33,opt,name=continuous_scheduling_solver,json=continuousSchedulingSolver,proto3,enum=operations_research.RoutingSearchParameters_SchedulingSolver" json:"continuous_scheduling_solver,omitempty"`
	MixedIntegerSchedulingSolver RoutingSearchParameters_SchedulingSolver `protobuf:"varint,34,opt,name=mixed_integer_scheduling_solver,json=mixedIntegerSchedulingSolver,proto3,enum=operations_research.RoutingSearchParameters_SchedulingSolver" json:"mixed_integer_scheduling_solver,omitempty"`
	// Setting this to true completely disables the LP and MIP scheduling in the
	// solver. This overrides the 2 SchedulingSolver options above.
	DisableSchedulingBewareThisMayDegradePerformance *bool `protobuf:"varint,50,opt,name=disable_scheduling_beware_this_may_degrade_performance,json=disableSchedulingBewareThisMayDegradePerformance,proto3,oneof" json:"disable_scheduling_beware_this_may_degrade_performance,omitempty"`
	// Minimum step by which the solution must be improved in local search. 0
	// means "unspecified". If this value is fractional, it will get rounded to
	// the nearest integer.
	OptimizationStep float64 `protobuf:"fixed64,7,opt,name=optimization_step,json=optimizationStep,proto3" json:"optimization_step,omitempty"`
	// Number of solutions to collect during the search. Corresponds to the best
	// solutions found during the search. 0 means "unspecified".
	NumberOfSolutionsToCollect int32 `protobuf:"varint,17,opt,name=number_of_solutions_to_collect,json=numberOfSolutionsToCollect,proto3" json:"number_of_solutions_to_collect,omitempty"`
	// -- Search limits --
	// Limit to the number of solutions generated during the search. 0 means
	// "unspecified".
	SolutionLimit int64 `protobuf:"varint,8,opt,name=solution_limit,json=solutionLimit,proto3" json:"solution_limit,omitempty"`
	// Limit to the time spent in the search.
	TimeLimit *durationpb.Duration `protobuf:"bytes,9,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	// Limit to the time spent in the completion search for each local search
	// neighbor.
	LnsTimeLimit *durationpb.Duration `protobuf:"bytes,10,opt,name=lns_time_limit,json=lnsTimeLimit,proto3" json:"lns_time_limit,omitempty"`
	// Ratio of the overall time limit spent in a secondary LS phase with only
	// intra-route and insertion operators, meant to "cleanup" the current
	// solution before stopping the search.
	// TODO(user): Since these operators are very fast, add a parameter to cap
	// the max time allocated for this second phase (e.g.
	// Duration max_secondary_ls_time_limit).
	SecondaryLsTimeLimitRatio float64 `protobuf:"fixed64,57,opt,name=secondary_ls_time_limit_ratio,json=secondaryLsTimeLimitRatio,proto3" json:"secondary_ls_time_limit_ratio,omitempty"`
	// The improvement search limit is added to the solver if the following
	// parameters are set.
	ImprovementLimitParameters *RoutingSearchParameters_ImprovementSearchLimitParameters `protobuf:"bytes,37,opt,name=improvement_limit_parameters,json=improvementLimitParameters,proto3" json:"improvement_limit_parameters,omitempty"`
	// --- Propagation control ---
	// These are advanced settings which should not be modified unless you know
	// what you are doing.
	//
	// Use constraints with full propagation in routing model (instead of 'light'
	// propagation only). Full propagation is only necessary when using
	// depth-first search or for models which require strong propagation to
	// finalize the value of secondary variables.
	// Changing this setting to true will slow down the search in most cases and
	// increase memory consumption in all cases.
	UseFullPropagation bool `protobuf:"varint,11,opt,name=use_full_propagation,json=useFullPropagation,proto3" json:"use_full_propagation,omitempty"`
	// --- Miscellaneous ---
	// Some of these are advanced settings which should not be modified unless you
	// know what you are doing.
	//
	// Activates search logging. For each solution found during the search, the
	// following will be displayed: its objective value, the maximum objective
	// value since the beginning of the search, the elapsed time since the
	// beginning of the search, the number of branches explored in the search
	// tree, the number of failures in the search tree, the depth of the search
	// tree, the number of local search neighbors explored, the number of local
	// search neighbors filtered by local search filters, the number of local
	// search neighbors accepted, the total memory used and the percentage of the
	// search done.
	LogSearch bool `protobuf:"varint,13,opt,name=log_search,json=logSearch,proto3" json:"log_search,omitempty"`
	// In logs, cost values will be scaled and offset by the given values in the
	// following way: log_cost_scaling_factor * (cost + log_cost_offset)
	LogCostScalingFactor float64 `protobuf:"fixed64,22,opt,name=log_cost_scaling_factor,json=logCostScalingFactor,proto3" json:"log_cost_scaling_factor,omitempty"`
	LogCostOffset        float64 `protobuf:"fixed64,29,opt,name=log_cost_offset,json=logCostOffset,proto3" json:"log_cost_offset,omitempty"`
	// In logs, this tag will be appended to each line corresponding to a new
	// solution. Useful to sort out logs when several solves are run in parallel.
	LogTag string `protobuf:"bytes,36,opt,name=log_tag,json=logTag,proto3" json:"log_tag,omitempty"`
	// Whether the solver should use an Iterated Local Search approach to solve
	// the problem.
	UseIteratedLocalSearch bool `protobuf:"varint,58,opt,name=use_iterated_local_search,json=useIteratedLocalSearch,proto3" json:"use_iterated_local_search,omitempty"`
	// Iterated Local Search parameters.
	IteratedLocalSearchParameters *IteratedLocalSearchParameters `protobuf:"bytes,60,opt,name=iterated_local_search_parameters,json=iteratedLocalSearchParameters,proto3" json:"iterated_local_search_parameters,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RoutingSearchParameters) Reset() {
	*x = RoutingSearchParameters{}
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSearchParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSearchParameters) ProtoMessage() {}

func (x *RoutingSearchParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSearchParameters.ProtoReflect.Descriptor instead.
func (*RoutingSearchParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_parameters_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingSearchParameters) GetFirstSolutionStrategy() FirstSolutionStrategy_Value {
	if x != nil {
		return x.FirstSolutionStrategy
	}
	return FirstSolutionStrategy_UNSET
}

func (x *RoutingSearchParameters) GetUseUnfilteredFirstSolutionStrategy() bool {
	if x != nil {
		return x.UseUnfilteredFirstSolutionStrategy
	}
	return false
}

func (x *RoutingSearchParameters) GetSavingsParameters() *SavingsParameters {
	if x != nil {
		return x.SavingsParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetGlobalCheapestInsertionFirstSolutionParameters() *GlobalCheapestInsertionParameters {
	if x != nil {
		return x.GlobalCheapestInsertionFirstSolutionParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetGlobalCheapestInsertionLsOperatorParameters() *GlobalCheapestInsertionParameters {
	if x != nil {
		return x.GlobalCheapestInsertionLsOperatorParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetLocalCheapestInsertionParameters() *LocalCheapestInsertionParameters {
	if x != nil {
		return x.LocalCheapestInsertionParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetLocalCheapestCostInsertionParameters() *LocalCheapestInsertionParameters {
	if x != nil {
		return x.LocalCheapestCostInsertionParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetChristofidesUseMinimumMatching() bool {
	if x != nil {
		return x.ChristofidesUseMinimumMatching
	}
	return false
}

func (x *RoutingSearchParameters) GetFirstSolutionOptimizationPeriod() int32 {
	if x != nil {
		return x.FirstSolutionOptimizationPeriod
	}
	return 0
}

func (x *RoutingSearchParameters) GetLocalSearchOperators() *RoutingSearchParameters_LocalSearchNeighborhoodOperators {
	if x != nil {
		return x.LocalSearchOperators
	}
	return nil
}

func (x *RoutingSearchParameters) GetLsOperatorNeighborsRatio() float64 {
	if x != nil {
		return x.LsOperatorNeighborsRatio
	}
	return 0
}

func (x *RoutingSearchParameters) GetLsOperatorMinNeighbors() int32 {
	if x != nil {
		return x.LsOperatorMinNeighbors
	}
	return 0
}

func (x *RoutingSearchParameters) GetUseMultiArmedBanditConcatenateOperators() bool {
	if x != nil {
		return x.UseMultiArmedBanditConcatenateOperators
	}
	return false
}

func (x *RoutingSearchParameters) GetMultiArmedBanditCompoundOperatorMemoryCoefficient() float64 {
	if x != nil {
		return x.MultiArmedBanditCompoundOperatorMemoryCoefficient
	}
	return 0
}

func (x *RoutingSearchParameters) GetMultiArmedBanditCompoundOperatorExplorationCoefficient() float64 {
	if x != nil {
		return x.MultiArmedBanditCompoundOperatorExplorationCoefficient
	}
	return 0
}

func (x *RoutingSearchParameters) GetMaxSwapActiveChainSize() int32 {
	if x != nil {
		return x.MaxSwapActiveChainSize
	}
	return 0
}

func (x *RoutingSearchParameters) GetRelocateExpensiveChainNumArcsToConsider() int32 {
	if x != nil {
		return x.RelocateExpensiveChainNumArcsToConsider
	}
	return 0
}

func (x *RoutingSearchParameters) GetHeuristicExpensiveChainLnsNumArcsToConsider() int32 {
	if x != nil {
		return x.HeuristicExpensiveChainLnsNumArcsToConsider
	}
	return 0
}

func (x *RoutingSearchParameters) GetHeuristicCloseNodesLnsNumNodes() int32 {
	if x != nil {
		return x.HeuristicCloseNodesLnsNumNodes
	}
	return 0
}

func (x *RoutingSearchParameters) GetLocalSearchMetaheuristic() LocalSearchMetaheuristic_Value {
	if x != nil {
		return x.LocalSearchMetaheuristic
	}
	return LocalSearchMetaheuristic_UNSET
}

func (x *RoutingSearchParameters) GetLocalSearchMetaheuristics() []LocalSearchMetaheuristic_Value {
	if x != nil {
		return x.LocalSearchMetaheuristics
	}
	return nil
}

func (x *RoutingSearchParameters) GetNumMaxLocalOptimaBeforeMetaheuristicSwitch() int32 {
	if x != nil {
		return x.NumMaxLocalOptimaBeforeMetaheuristicSwitch
	}
	return 0
}

func (x *RoutingSearchParameters) GetGuidedLocalSearchLambdaCoefficient() float64 {
	if x != nil {
		return x.GuidedLocalSearchLambdaCoefficient
	}
	return 0
}

func (x *RoutingSearchParameters) GetGuidedLocalSearchResetPenaltiesOnNewBestSolution() bool {
	if x != nil {
		return x.GuidedLocalSearchResetPenaltiesOnNewBestSolution
	}
	return false
}

func (x *RoutingSearchParameters) GetGuidedLocalSearchPenalizeWithVehicleClasses() bool {
	if x != nil {
		return x.GuidedLocalSearchPenalizeWithVehicleClasses
	}
	return false
}

func (x *RoutingSearchParameters) GetUseGuidedLocalSearchPenaltiesInLocalSearchOperators() bool {
	if x != nil {
		return x.UseGuidedLocalSearchPenaltiesInLocalSearchOperators
	}
	return false
}

func (x *RoutingSearchParameters) GetUseDepthFirstSearch() bool {
	if x != nil {
		return x.UseDepthFirstSearch
	}
	return false
}

func (x *RoutingSearchParameters) GetUseCp() util.OptionalBoolean {
	if x != nil {
		return x.UseCp
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters) GetUseCpSat() util.OptionalBoolean {
	if x != nil {
		return x.UseCpSat
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters) GetUseGeneralizedCpSat() util.OptionalBoolean {
	if x != nil {
		return x.UseGeneralizedCpSat
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters) GetSatParameters() *sat.SatParameters {
	if x != nil {
		return x.SatParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetReportIntermediateCpSatSolutions() bool {
	if x != nil {
		return x.ReportIntermediateCpSatSolutions
	}
	return false
}

func (x *RoutingSearchParameters) GetFallbackToCpSatSizeThreshold() int32 {
	if x != nil {
		return x.FallbackToCpSatSizeThreshold
	}
	return 0
}

func (x *RoutingSearchParameters) GetContinuousSchedulingSolver() RoutingSearchParameters_SchedulingSolver {
	if x != nil {
		return x.ContinuousSchedulingSolver
	}
	return RoutingSearchParameters_SCHEDULING_UNSET
}

func (x *RoutingSearchParameters) GetMixedIntegerSchedulingSolver() RoutingSearchParameters_SchedulingSolver {
	if x != nil {
		return x.MixedIntegerSchedulingSolver
	}
	return RoutingSearchParameters_SCHEDULING_UNSET
}

func (x *RoutingSearchParameters) GetDisableSchedulingBewareThisMayDegradePerformance() bool {
	if x != nil && x.DisableSchedulingBewareThisMayDegradePerformance != nil {
		return *x.DisableSchedulingBewareThisMayDegradePerformance
	}
	return false
}

func (x *RoutingSearchParameters) GetOptimizationStep() float64 {
	if x != nil {
		return x.OptimizationStep
	}
	return 0
}

func (x *RoutingSearchParameters) GetNumberOfSolutionsToCollect() int32 {
	if x != nil {
		return x.NumberOfSolutionsToCollect
	}
	return 0
}

func (x *RoutingSearchParameters) GetSolutionLimit() int64 {
	if x != nil {
		return x.SolutionLimit
	}
	return 0
}

func (x *RoutingSearchParameters) GetTimeLimit() *durationpb.Duration {
	if x != nil {
		return x.TimeLimit
	}
	return nil
}

func (x *RoutingSearchParameters) GetLnsTimeLimit() *durationpb.Duration {
	if x != nil {
		return x.LnsTimeLimit
	}
	return nil
}

func (x *RoutingSearchParameters) GetSecondaryLsTimeLimitRatio() float64 {
	if x != nil {
		return x.SecondaryLsTimeLimitRatio
	}
	return 0
}

func (x *RoutingSearchParameters) GetImprovementLimitParameters() *RoutingSearchParameters_ImprovementSearchLimitParameters {
	if x != nil {
		return x.ImprovementLimitParameters
	}
	return nil
}

func (x *RoutingSearchParameters) GetUseFullPropagation() bool {
	if x != nil {
		return x.UseFullPropagation
	}
	return false
}

func (x *RoutingSearchParameters) GetLogSearch() bool {
	if x != nil {
		return x.LogSearch
	}
	return false
}

func (x *RoutingSearchParameters) GetLogCostScalingFactor() float64 {
	if x != nil {
		return x.LogCostScalingFactor
	}
	return 0
}

func (x *RoutingSearchParameters) GetLogCostOffset() float64 {
	if x != nil {
		return x.LogCostOffset
	}
	return 0
}

func (x *RoutingSearchParameters) GetLogTag() string {
	if x != nil {
		return x.LogTag
	}
	return ""
}

func (x *RoutingSearchParameters) GetUseIteratedLocalSearch() bool {
	if x != nil {
		return x.UseIteratedLocalSearch
	}
	return false
}

func (x *RoutingSearchParameters) GetIteratedLocalSearchParameters() *IteratedLocalSearchParameters {
	if x != nil {
		return x.IteratedLocalSearchParameters
	}
	return nil
}

// Parameters which have to be set when creating a RoutingModel.
type RoutingModelParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameters to use in the underlying constraint solver.
	SolverParameters *ConstraintSolverParameters `protobuf:"bytes,1,opt,name=solver_parameters,json=solverParameters,proto3" json:"solver_parameters,omitempty"`
	// Advanced settings.
	// If set to true reduction of the underlying constraint model will be
	// attempted when all vehicles have exactly the same cost structure. This can
	// result in significant speedups.
	ReduceVehicleCostModel bool `protobuf:"varint,2,opt,name=reduce_vehicle_cost_model,json=reduceVehicleCostModel,proto3" json:"reduce_vehicle_cost_model,omitempty"`
	// Cache callback calls if the number of nodes in the model is less or equal
	// to this value.
	MaxCallbackCacheSize int32 `protobuf:"varint,3,opt,name=max_callback_cache_size,json=maxCallbackCacheSize,proto3" json:"max_callback_cache_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RoutingModelParameters) Reset() {
	*x = RoutingModelParameters{}
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingModelParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingModelParameters) ProtoMessage() {}

func (x *RoutingModelParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingModelParameters.ProtoReflect.Descriptor instead.
func (*RoutingModelParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_parameters_proto_rawDescGZIP(), []int{1}
}

func (x *RoutingModelParameters) GetSolverParameters() *ConstraintSolverParameters {
	if x != nil {
		return x.SolverParameters
	}
	return nil
}

func (x *RoutingModelParameters) GetReduceVehicleCostModel() bool {
	if x != nil {
		return x.ReduceVehicleCostModel
	}
	return false
}

func (x *RoutingModelParameters) GetMaxCallbackCacheSize() int32 {
	if x != nil {
		return x.MaxCallbackCacheSize
	}
	return 0
}

// Local search neighborhood operators used to build a solutions neighborhood.
// Next ID: 41
type RoutingSearchParameters_LocalSearchNeighborhoodOperators struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Inter-route operators ---
	// Operator which moves a single node to another position.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 -> 5
	// (where (1, 5) are first and last nodes of the path and can therefore not
	// be moved):
	//
	//	1 ->  3  -> [2] ->  4  -> 5
	//	1 ->  3  ->  4  -> [2] -> 5
	//	1 ->  2  ->  4  -> [3] -> 5
	//	1 -> [4] ->  2  ->  3  -> 5
	UseRelocate util.OptionalBoolean `protobuf:"varint,1,opt,name=use_relocate,json=useRelocate,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate,omitempty"`
	// Operator which moves a pair of pickup and delivery nodes to another
	// position where the first node of the pair must be before the second node
	// on the same path. Compared to the light_relocate_pair operator, tries all
	// possible positions of insertion of a pair (not only after another pair).
	// Possible neighbors for the path 1 -> A -> B -> 2 -> 3 (where (1, 3) are
	// first and last nodes of the path and can therefore not be moved, and
	// (A, B) is a pair of nodes):
	//
	//	1 -> [A] ->  2  -> [B] -> 3
	//	1 ->  2  -> [A] -> [B] -> 3
	UseRelocatePair util.OptionalBoolean `protobuf:"varint,2,opt,name=use_relocate_pair,json=useRelocatePair,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate_pair,omitempty"`
	// Operator which moves a pair of pickup and delivery nodes after another
	// pair.
	// Possible neighbors for paths 1 -> A -> B -> 2, 3 -> C -> D -> 4 (where
	// (1, 2) and (3, 4) are first and last nodes of paths and can therefore not
	// be moved, and (A, B) and (C, D) are pair of nodes):
	//
	//	1 -> 2, 3 -> C -> [A] -> D -> [B] -> 4
	//	1 -> A -> [C] -> B -> [D] -> 2, 3 -> 4
	UseLightRelocatePair util.OptionalBoolean `protobuf:"varint,24,opt,name=use_light_relocate_pair,json=useLightRelocatePair,proto3,enum=operations_research.OptionalBoolean" json:"use_light_relocate_pair,omitempty"`
	// Relocate neighborhood which moves chains of neighbors.
	// The operator starts by relocating a node n after a node m, then continues
	// moving nodes which were after n as long as the "cost" added is less than
	// the "cost" of the arc (m, n). If the new chain doesn't respect the domain
	// of next variables, it will try reordering the nodes until it finds a
	// valid path.
	// Possible neighbors for path 1 -> A -> B -> C -> D -> E -> 2 (where (1, 2)
	// are first and last nodes of the path and can therefore not be moved, A
	// must be performed before B, and A, D and E are located at the same
	// place):
	// 1 -> A -> C -> [B] -> D -> E -> 2
	// 1 -> A -> C -> D -> [B] -> E -> 2
	// 1 -> A -> C -> D -> E -> [B] -> 2
	// 1 -> A -> B -> D -> [C] -> E -> 2
	// 1 -> A -> B -> D -> E -> [C] -> 2
	// 1 -> A -> [D] -> [E] -> B -> C -> 2
	// 1 -> A -> B -> [D] -> [E] ->  C -> 2
	// 1 -> A -> [E] -> B -> C -> D -> 2
	// 1 -> A -> B -> [E] -> C -> D -> 2
	// 1 -> A -> B -> C -> [E] -> D -> 2
	// This operator is extremely useful to move chains of nodes which are
	// located at the same place (for instance nodes part of a same stop).
	UseRelocateNeighbors util.OptionalBoolean `protobuf:"varint,3,opt,name=use_relocate_neighbors,json=useRelocateNeighbors,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate_neighbors,omitempty"`
	// Relocate neighborhood that moves subpaths all pickup and delivery
	// pairs have both pickup and delivery inside the subpath or both outside
	// the subpath. For instance, for given paths:
	// 0 -> A -> B -> A' -> B' -> 5 -> 6 -> 8
	// 7 -> 9
	// Pairs (A,A') and (B,B') are interleaved, so the expected neighbors are:
	// 0 -> 5 -> A -> B -> A' -> B' -> 6 -> 8
	// 7 -> 9
	//
	// 0 -> 5 -> 6 -> A -> B -> A' -> B' -> 8
	// 7 -> 9
	//
	// 0 -> 5 -> 6 -> 8
	// 7 -> A -> B -> A' -> B' -> 9
	UseRelocateSubtrip util.OptionalBoolean `protobuf:"varint,25,opt,name=use_relocate_subtrip,json=useRelocateSubtrip,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate_subtrip,omitempty"`
	// Operator which exchanges the positions of two nodes.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 -> 5
	// (where (1, 5) are first and last nodes of the path and can therefore not
	// be moved):
	//
	//	1 -> [3] -> [2] ->  4  -> 5
	//	1 -> [4] ->  3  -> [2] -> 5
	//	1 ->  2  -> [4] -> [3] -> 5
	UseExchange util.OptionalBoolean `protobuf:"varint,4,opt,name=use_exchange,json=useExchange,proto3,enum=operations_research.OptionalBoolean" json:"use_exchange,omitempty"`
	// Operator which exchanges the positions of two pair of nodes. Pairs
	// correspond to the pickup and delivery pairs defined in the routing model.
	// Possible neighbor for the paths
	// 1 -> A -> B -> 2 -> 3 and 4 -> C -> D -> 5
	// (where (1, 3) and (4, 5) are first and last nodes of the paths and can
	// therefore not be moved, and (A, B) and (C,D) are pairs of nodes):
	//
	//	1 -> [C] ->  [D] -> 2 -> 3, 4 -> [A] -> [B] -> 5
	UseExchangePair util.OptionalBoolean `protobuf:"varint,22,opt,name=use_exchange_pair,json=useExchangePair,proto3,enum=operations_research.OptionalBoolean" json:"use_exchange_pair,omitempty"`
	// Operator which exchanges subtrips associated to two pairs of nodes,
	// see use_relocate_subtrip for a definition of subtrips.
	UseExchangeSubtrip util.OptionalBoolean `protobuf:"varint,26,opt,name=use_exchange_subtrip,json=useExchangeSubtrip,proto3,enum=operations_research.OptionalBoolean" json:"use_exchange_subtrip,omitempty"`
	// Operator which cross exchanges the starting chains of 2 paths, including
	// exchanging the whole paths.
	// First and last nodes are not moved.
	// Possible neighbors for the paths 1 -> 2 -> 3 -> 4 -> 5 and 6 -> 7 -> 8
	// (where (1, 5) and (6, 8) are first and last nodes of the paths and can
	// therefore not be moved):
	//
	//	1 -> [7] -> 3 -> 4 -> 5  6 -> [2] -> 8
	//	1 -> [7] -> 4 -> 5       6 -> [2 -> 3] -> 8
	//	1 -> [7] -> 5            6 -> [2 -> 3 -> 4] -> 8
	UseCross util.OptionalBoolean `protobuf:"varint,5,opt,name=use_cross,json=useCross,proto3,enum=operations_research.OptionalBoolean" json:"use_cross,omitempty"`
	// Not implemented yet. TODO(b/68128619): Implement.
	UseCrossExchange util.OptionalBoolean `protobuf:"varint,6,opt,name=use_cross_exchange,json=useCrossExchange,proto3,enum=operations_research.OptionalBoolean" json:"use_cross_exchange,omitempty"`
	// Operator which detects the relocate_expensive_chain_num_arcs_to_consider
	// most expensive arcs on a path, and moves the chain resulting from cutting
	// pairs of arcs among these to another position.
	// Possible neighbors for paths 1 -> 2 (empty) and
	// 3 -> A ------> B --> C -----> D -> 4 (where A -> B and C -> D are the 2
	// most expensive arcs, and the chain resulting from breaking them is
	// B -> C):
	//
	//	1 -> [B -> C] -> 2     3 -> A -> D -> 4
	//	1 -> 2      3 -> [B -> C] -> A -> D -> 4
	//	1 -> 2      3 -> A -> D -> [B -> C] -> 4
	UseRelocateExpensiveChain util.OptionalBoolean `protobuf:"varint,23,opt,name=use_relocate_expensive_chain,json=useRelocateExpensiveChain,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate_expensive_chain,omitempty"`
	// --- Intra-route operators ---
	// Operator which reverses a subchain of a path. It is called TwoOpt
	// because it breaks two arcs on the path; resulting paths are called
	// two-optimal.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 -> 5
	// (where (1, 5) are first and last nodes of the path and can therefore not
	// be moved):
	//
	//	1 -> [3 -> 2] -> 4  -> 5
	//	1 -> [4 -> 3  -> 2] -> 5
	//	1 ->  2 -> [4 -> 3] -> 5
	UseTwoOpt util.OptionalBoolean `protobuf:"varint,7,opt,name=use_two_opt,json=useTwoOpt,proto3,enum=operations_research.OptionalBoolean" json:"use_two_opt,omitempty"`
	// Operator which moves sub-chains of a path of length 1, 2 and 3 to another
	// position in the same path.
	// When the length of the sub-chain is 1, the operator simply moves a node
	// to another position.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 -> 5, for a sub-chain
	// length of 2 (where (1, 5) are first and last nodes of the path and can
	// therefore not be moved):
	//
	//	1 ->  4 -> [2 -> 3] -> 5
	//	1 -> [3 -> 4] -> 2  -> 5
	//
	// The OR_OPT operator is a limited version of 3-Opt (breaks 3 arcs on a
	// path).
	UseOrOpt util.OptionalBoolean `protobuf:"varint,8,opt,name=use_or_opt,json=useOrOpt,proto3,enum=operations_research.OptionalBoolean" json:"use_or_opt,omitempty"`
	// Lin-Kernighan operator.
	// While the accumulated local gain is positive, performs a 2-OPT or a 3-OPT
	// move followed by a series of 2-OPT moves. Returns a neighbor for which
	// the global gain is positive.
	UseLinKernighan util.OptionalBoolean `protobuf:"varint,9,opt,name=use_lin_kernighan,json=useLinKernighan,proto3,enum=operations_research.OptionalBoolean" json:"use_lin_kernighan,omitempty"`
	// Sliding TSP operator.
	// Uses an exact dynamic programming algorithm to solve the TSP
	// corresponding to path sub-chains.
	// For a subchain 1 -> 2 -> 3 -> 4 -> 5 -> 6, solves the TSP on
	// nodes A, 2, 3, 4, 5, where A is a merger of nodes 1 and 6 such that
	// cost(A,i) = cost(1,i) and cost(i,A) = cost(i,6).
	UseTspOpt util.OptionalBoolean `protobuf:"varint,10,opt,name=use_tsp_opt,json=useTspOpt,proto3,enum=operations_research.OptionalBoolean" json:"use_tsp_opt,omitempty"`
	// --- Operators on inactive nodes ---
	// Operator which inserts an inactive node into a path.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 with 5 inactive
	// (where 1 and 4 are first and last nodes of the path) are:
	//
	//	1 -> [5] ->  2  ->  3  -> 4
	//	1 ->  2  -> [5] ->  3  -> 4
	//	1 ->  2  ->  3  -> [5] -> 4
	UseMakeActive util.OptionalBoolean `protobuf:"varint,11,opt,name=use_make_active,json=useMakeActive,proto3,enum=operations_research.OptionalBoolean" json:"use_make_active,omitempty"`
	// Operator which relocates a node while making an inactive one active.
	// As of 3/2017, the operator is limited to two kinds of moves:
	//   - Relocating a node and replacing it by an inactive node.
	//     Possible neighbor for path 1 -> 5, 2 -> 3 -> 6 and 4 inactive
	//     (where 1,2 and 5,6 are first and last nodes of paths) is:
	//     1 -> 3 -> 5, 2 -> 4 -> 6.
	//   - Relocating a node and inserting an inactive node next to it.
	//     Possible neighbor for path 1 -> 5, 2 -> 3 -> 6 and 4 inactive
	//     (where 1,2 and 5,6 are first and last nodes of paths) is:
	//     1 -> 4 -> 3 -> 5, 2 -> 6.
	UseRelocateAndMakeActive util.OptionalBoolean `protobuf:"varint,21,opt,name=use_relocate_and_make_active,json=useRelocateAndMakeActive,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate_and_make_active,omitempty"`
	// Operator which exchanges two nodes and inserts an inactive node.
	// Possible neighbors for paths 0 -> 2 -> 4, 1 -> 3 -> 6 and 5 inactive are:
	// 0 -> 3 -> 4, 1 -> 5 -> 2 -> 6
	// 0 -> 3 -> 5 -> 4, 1 -> 2 -> 6
	// 0 -> 5 -> 3 -> 4, 1 -> 2 -> 6
	// 0 -> 3 -> 4, 1 -> 2 -> 5 -> 6
	UseExchangeAndMakeActive util.OptionalBoolean `protobuf:"varint,37,opt,name=use_exchange_and_make_active,json=useExchangeAndMakeActive,proto3,enum=operations_research.OptionalBoolean" json:"use_exchange_and_make_active,omitempty"`
	// Operator which exchanges the first and last nodes of two paths and makes
	// a node active.
	// Possible neighbors for paths 0 -> 1 -> 2 -> 7, 6 -> 3 -> 4 -> 8
	// and 5 inactive are:
	// 0 -> 5 -> 3 -> 4 -> 7, 6 -> 1 -> 2 -> 8
	// 0 -> 3 -> 4 -> 7, 6 -> 1 -> 5 -> 2 -> 8
	// 0 -> 3 -> 4 -> 7, 6 -> 1 -> 2 -> 5 -> 8
	// 0 -> 3 -> 5 -> 4 -> 7, 6 -> 1 -> 2 -> 8
	// 0 -> 3 -> 4 -> 5 -> 7, 6 -> 1 -> 2 -> 8
	UseExchangePathStartEndsAndMakeActive util.OptionalBoolean `protobuf:"varint,38,opt,name=use_exchange_path_start_ends_and_make_active,json=useExchangePathStartEndsAndMakeActive,proto3,enum=operations_research.OptionalBoolean" json:"use_exchange_path_start_ends_and_make_active,omitempty"`
	// Operator which makes path nodes inactive.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 (where 1 and 4 are first
	// and last nodes of the path) are:
	//
	//	1 -> 3 -> 4 with 2 inactive
	//	1 -> 2 -> 4 with 3 inactive
	UseMakeInactive util.OptionalBoolean `protobuf:"varint,12,opt,name=use_make_inactive,json=useMakeInactive,proto3,enum=operations_research.OptionalBoolean" json:"use_make_inactive,omitempty"`
	// Operator which makes a "chain" of path nodes inactive.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 (where 1 and 4 are first
	// and last nodes of the path) are:
	//
	//	1 -> 3 -> 4 with 2 inactive
	//	1 -> 2 -> 4 with 3 inactive
	//	1 -> 4 with 2 and 3 inactive
	UseMakeChainInactive util.OptionalBoolean `protobuf:"varint,13,opt,name=use_make_chain_inactive,json=useMakeChainInactive,proto3,enum=operations_research.OptionalBoolean" json:"use_make_chain_inactive,omitempty"`
	// Operator which replaces an active node by an inactive one.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 with 5 inactive
	// (where 1 and 4 are first and last nodes of the path) are:
	//
	//	1 -> [5] ->  3  -> 4 with 2 inactive
	//	1 ->  2  -> [5] -> 4 with 3 inactive
	UseSwapActive util.OptionalBoolean `protobuf:"varint,14,opt,name=use_swap_active,json=useSwapActive,proto3,enum=operations_research.OptionalBoolean" json:"use_swap_active,omitempty"`
	// Operator which replaces a chain of active nodes by an inactive one.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 with 5 inactive
	// (where 1 and 4 are first and last nodes of the path) are:
	//
	//	1 -> [5] ->  3  -> 4 with 2 inactive
	//	1 ->  2  -> [5] -> 4 with 3 inactive
	//	1 -> [5] -> 4 with 2 and 3 inactive
	UseSwapActiveChain util.OptionalBoolean `protobuf:"varint,35,opt,name=use_swap_active_chain,json=useSwapActiveChain,proto3,enum=operations_research.OptionalBoolean" json:"use_swap_active_chain,omitempty"`
	// Operator which makes an inactive node active and an active one inactive.
	// It is similar to SwapActiveOperator excepts that it tries to insert the
	// inactive node in all possible positions instead of just the position of
	// the node made inactive.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 with 5 inactive
	// (where 1 and 4 are first and last nodes of the path) are:
	//
	//	1 -> [5] ->  3  -> 4 with 2 inactive
	//	1 ->  3  -> [5] -> 4 with 2 inactive
	//	1 -> [5] ->  2  -> 4 with 3 inactive
	//	1 ->  2  -> [5] -> 4 with 3 inactive
	UseExtendedSwapActive util.OptionalBoolean `protobuf:"varint,15,opt,name=use_extended_swap_active,json=useExtendedSwapActive,proto3,enum=operations_research.OptionalBoolean" json:"use_extended_swap_active,omitempty"`
	// Swaps active nodes from node alternatives in sequence. Considers chains
	// of nodes with alternatives, builds a DAG from the chain, each "layer" of
	// the DAG being composed of the set of alternatives of the node at a given
	// rank in the chain, fully connected to the next layer. A neighbor is built
	// from the shortest path starting from the node before the chain (source),
	// through the DAG to the node following the chain.
	UseShortestPathSwapActive util.OptionalBoolean `protobuf:"varint,34,opt,name=use_shortest_path_swap_active,json=useShortestPathSwapActive,proto3,enum=operations_research.OptionalBoolean" json:"use_shortest_path_swap_active,omitempty"`
	// Similar to use_two_opt but returns the shortest path on the DAG of node
	// alternatives of the reversed chain (cf. use_shortest_path_swap_active).
	UseShortestPathTwoOpt util.OptionalBoolean `protobuf:"varint,36,opt,name=use_shortest_path_two_opt,json=useShortestPathTwoOpt,proto3,enum=operations_research.OptionalBoolean" json:"use_shortest_path_two_opt,omitempty"`
	// Operator which makes an inactive node active and an active pair of nodes
	// inactive OR makes an inactive pair of nodes active and an active node
	// inactive.
	// Possible neighbors for the path 1 -> 2 -> 3 -> 4 with 5 inactive
	// (where 1 and 4 are first and last nodes of the path and (2,3) is a pair
	// of nodes) are:
	//
	//	1 -> [5] -> 4 with (2,3) inactive
	//
	// Possible neighbors for the path 1 -> 2 -> 3 with (4,5) inactive
	// (where 1 and 3 are first and last nodes of the path and (4,5) is a pair
	// of nodes) are:
	//
	//	1 -> [4] -> [5] -> 3 with 2 inactive
	UseNodePairSwapActive util.OptionalBoolean `protobuf:"varint,20,opt,name=use_node_pair_swap_active,json=useNodePairSwapActive,proto3,enum=operations_research.OptionalBoolean" json:"use_node_pair_swap_active,omitempty"`
	// --- Large neighborhood search operators ---
	// Operator which relaxes two sub-chains of three consecutive arcs each.
	// Each sub-chain is defined by a start node and the next three arcs. Those
	// six arcs are relaxed to build a new neighbor.
	// PATH_LNS explores all possible pairs of starting nodes and so defines
	// n^2 neighbors, n being the number of nodes.
	// Note that the two sub-chains can be part of the same path; they even may
	// overlap.
	UsePathLns util.OptionalBoolean `protobuf:"varint,16,opt,name=use_path_lns,json=usePathLns,proto3,enum=operations_research.OptionalBoolean" json:"use_path_lns,omitempty"`
	// Operator which relaxes one entire path and all inactive nodes.
	UseFullPathLns util.OptionalBoolean `protobuf:"varint,17,opt,name=use_full_path_lns,json=useFullPathLns,proto3,enum=operations_research.OptionalBoolean" json:"use_full_path_lns,omitempty"`
	// TSP-base LNS.
	// Randomly merges consecutive nodes until n "meta"-nodes remain and solves
	// the corresponding TSP.
	// This defines an "unlimited" neighborhood which must be stopped by search
	// limits. To force diversification, the operator iteratively forces each
	// node to serve as base of a meta-node.
	UseTspLns util.OptionalBoolean `protobuf:"varint,18,opt,name=use_tsp_lns,json=useTspLns,proto3,enum=operations_research.OptionalBoolean" json:"use_tsp_lns,omitempty"`
	// Operator which relaxes all inactive nodes and one sub-chain of six
	// consecutive arcs. That way the path can be improved by inserting inactive
	// nodes or swapping arcs.
	UseInactiveLns util.OptionalBoolean `protobuf:"varint,19,opt,name=use_inactive_lns,json=useInactiveLns,proto3,enum=operations_research.OptionalBoolean" json:"use_inactive_lns,omitempty"`
	// --- LNS-like large neighborhood search operators using heuristics ---
	// Operator which makes all nodes on a route unperformed, and reinserts them
	// using the GlobalCheapestInsertion heuristic.
	UseGlobalCheapestInsertionPathLns util.OptionalBoolean `protobuf:"varint,27,opt,name=use_global_cheapest_insertion_path_lns,json=useGlobalCheapestInsertionPathLns,proto3,enum=operations_research.OptionalBoolean" json:"use_global_cheapest_insertion_path_lns,omitempty"`
	// Same as above but using LocalCheapestInsertion as a heuristic.
	UseLocalCheapestInsertionPathLns util.OptionalBoolean `protobuf:"varint,28,opt,name=use_local_cheapest_insertion_path_lns,json=useLocalCheapestInsertionPathLns,proto3,enum=operations_research.OptionalBoolean" json:"use_local_cheapest_insertion_path_lns,omitempty"`
	// The following operator relocates an entire route to an empty path and
	// then tries to insert the unperformed nodes using the global cheapest
	// insertion heuristic.
	UseRelocatePathGlobalCheapestInsertionInsertUnperformed util.OptionalBoolean `protobuf:"varint,33,opt,name=use_relocate_path_global_cheapest_insertion_insert_unperformed,json=useRelocatePathGlobalCheapestInsertionInsertUnperformed,proto3,enum=operations_research.OptionalBoolean" json:"use_relocate_path_global_cheapest_insertion_insert_unperformed,omitempty"`
	// This operator finds heuristic_expensive_chain_lns_num_arcs_to_consider
	// most expensive arcs on a route, makes the nodes in between pairs of these
	// expensive arcs unperformed, and reinserts them using the
	// GlobalCheapestInsertion heuristic.
	UseGlobalCheapestInsertionExpensiveChainLns util.OptionalBoolean `protobuf:"varint,29,opt,name=use_global_cheapest_insertion_expensive_chain_lns,json=useGlobalCheapestInsertionExpensiveChainLns,proto3,enum=operations_research.OptionalBoolean" json:"use_global_cheapest_insertion_expensive_chain_lns,omitempty"`
	// Same as above but using LocalCheapestInsertion as a heuristic for
	// insertion.
	UseLocalCheapestInsertionExpensiveChainLns util.OptionalBoolean `protobuf:"varint,30,opt,name=use_local_cheapest_insertion_expensive_chain_lns,json=useLocalCheapestInsertionExpensiveChainLns,proto3,enum=operations_research.OptionalBoolean" json:"use_local_cheapest_insertion_expensive_chain_lns,omitempty"`
	// The following operator makes a node and its
	// heuristic_close_nodes_lns_num_nodes closest neighbors unperformed along
	// with each of their corresponding performed pickup/delivery pairs, and
	// then reinserts them using the GlobalCheapestInsertion heuristic.
	UseGlobalCheapestInsertionCloseNodesLns util.OptionalBoolean `protobuf:"varint,31,opt,name=use_global_cheapest_insertion_close_nodes_lns,json=useGlobalCheapestInsertionCloseNodesLns,proto3,enum=operations_research.OptionalBoolean" json:"use_global_cheapest_insertion_close_nodes_lns,omitempty"`
	// Same as above, but insertion positions for nodes are determined by the
	// LocalCheapestInsertion heuristic.
	UseLocalCheapestInsertionCloseNodesLns util.OptionalBoolean `protobuf:"varint,32,opt,name=use_local_cheapest_insertion_close_nodes_lns,json=useLocalCheapestInsertionCloseNodesLns,proto3,enum=operations_research.OptionalBoolean" json:"use_local_cheapest_insertion_close_nodes_lns,omitempty"`
	// The following operator removes all nodes of a visit type connected
	// component from their current route and reinserts them to an empty route
	// using the GlobalCheapestInsertion heuristic.
	UseGlobalCheapestInsertionVisitTypesLns util.OptionalBoolean `protobuf:"varint,39,opt,name=use_global_cheapest_insertion_visit_types_lns,json=useGlobalCheapestInsertionVisitTypesLns,proto3,enum=operations_research.OptionalBoolean" json:"use_global_cheapest_insertion_visit_types_lns,omitempty"`
	// Same as above, but insertion positions for nodes are determined by the
	// LocalCheapestInsertion heuristic.
	UseLocalCheapestInsertionVisitTypesLns util.OptionalBoolean `protobuf:"varint,40,opt,name=use_local_cheapest_insertion_visit_types_lns,json=useLocalCheapestInsertionVisitTypesLns,proto3,enum=operations_research.OptionalBoolean" json:"use_local_cheapest_insertion_visit_types_lns,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) Reset() {
	*x = RoutingSearchParameters_LocalSearchNeighborhoodOperators{}
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSearchParameters_LocalSearchNeighborhoodOperators) ProtoMessage() {}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSearchParameters_LocalSearchNeighborhoodOperators.ProtoReflect.Descriptor instead.
func (*RoutingSearchParameters_LocalSearchNeighborhoodOperators) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_parameters_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocate() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocate
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocatePair() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocatePair
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseLightRelocatePair() util.OptionalBoolean {
	if x != nil {
		return x.UseLightRelocatePair
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocateNeighbors() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocateNeighbors
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocateSubtrip() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocateSubtrip
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseExchange() util.OptionalBoolean {
	if x != nil {
		return x.UseExchange
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseExchangePair() util.OptionalBoolean {
	if x != nil {
		return x.UseExchangePair
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseExchangeSubtrip() util.OptionalBoolean {
	if x != nil {
		return x.UseExchangeSubtrip
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseCross() util.OptionalBoolean {
	if x != nil {
		return x.UseCross
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseCrossExchange() util.OptionalBoolean {
	if x != nil {
		return x.UseCrossExchange
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocateExpensiveChain() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocateExpensiveChain
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseTwoOpt() util.OptionalBoolean {
	if x != nil {
		return x.UseTwoOpt
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseOrOpt() util.OptionalBoolean {
	if x != nil {
		return x.UseOrOpt
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseLinKernighan() util.OptionalBoolean {
	if x != nil {
		return x.UseLinKernighan
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseTspOpt() util.OptionalBoolean {
	if x != nil {
		return x.UseTspOpt
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseMakeActive() util.OptionalBoolean {
	if x != nil {
		return x.UseMakeActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocateAndMakeActive() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocateAndMakeActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseExchangeAndMakeActive() util.OptionalBoolean {
	if x != nil {
		return x.UseExchangeAndMakeActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseExchangePathStartEndsAndMakeActive() util.OptionalBoolean {
	if x != nil {
		return x.UseExchangePathStartEndsAndMakeActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseMakeInactive() util.OptionalBoolean {
	if x != nil {
		return x.UseMakeInactive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseMakeChainInactive() util.OptionalBoolean {
	if x != nil {
		return x.UseMakeChainInactive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseSwapActive() util.OptionalBoolean {
	if x != nil {
		return x.UseSwapActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseSwapActiveChain() util.OptionalBoolean {
	if x != nil {
		return x.UseSwapActiveChain
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseExtendedSwapActive() util.OptionalBoolean {
	if x != nil {
		return x.UseExtendedSwapActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseShortestPathSwapActive() util.OptionalBoolean {
	if x != nil {
		return x.UseShortestPathSwapActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseShortestPathTwoOpt() util.OptionalBoolean {
	if x != nil {
		return x.UseShortestPathTwoOpt
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseNodePairSwapActive() util.OptionalBoolean {
	if x != nil {
		return x.UseNodePairSwapActive
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUsePathLns() util.OptionalBoolean {
	if x != nil {
		return x.UsePathLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseFullPathLns() util.OptionalBoolean {
	if x != nil {
		return x.UseFullPathLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseTspLns() util.OptionalBoolean {
	if x != nil {
		return x.UseTspLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseInactiveLns() util.OptionalBoolean {
	if x != nil {
		return x.UseInactiveLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseGlobalCheapestInsertionPathLns() util.OptionalBoolean {
	if x != nil {
		return x.UseGlobalCheapestInsertionPathLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseLocalCheapestInsertionPathLns() util.OptionalBoolean {
	if x != nil {
		return x.UseLocalCheapestInsertionPathLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseRelocatePathGlobalCheapestInsertionInsertUnperformed() util.OptionalBoolean {
	if x != nil {
		return x.UseRelocatePathGlobalCheapestInsertionInsertUnperformed
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseGlobalCheapestInsertionExpensiveChainLns() util.OptionalBoolean {
	if x != nil {
		return x.UseGlobalCheapestInsertionExpensiveChainLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseLocalCheapestInsertionExpensiveChainLns() util.OptionalBoolean {
	if x != nil {
		return x.UseLocalCheapestInsertionExpensiveChainLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseGlobalCheapestInsertionCloseNodesLns() util.OptionalBoolean {
	if x != nil {
		return x.UseGlobalCheapestInsertionCloseNodesLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseLocalCheapestInsertionCloseNodesLns() util.OptionalBoolean {
	if x != nil {
		return x.UseLocalCheapestInsertionCloseNodesLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseGlobalCheapestInsertionVisitTypesLns() util.OptionalBoolean {
	if x != nil {
		return x.UseGlobalCheapestInsertionVisitTypesLns
	}
	return util.OptionalBoolean(0)
}

func (x *RoutingSearchParameters_LocalSearchNeighborhoodOperators) GetUseLocalCheapestInsertionVisitTypesLns() util.OptionalBoolean {
	if x != nil {
		return x.UseLocalCheapestInsertionVisitTypesLns
	}
	return util.OptionalBoolean(0)
}

// Parameters required for the improvement search limit.
type RoutingSearchParameters_ImprovementSearchLimitParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameter that regulates exchange rate between objective improvement and
	// number of neighbors spent. The smaller the value, the sooner the limit
	// stops the search. Must be positive.
	ImprovementRateCoefficient float64 `protobuf:"fixed64,38,opt,name=improvement_rate_coefficient,json=improvementRateCoefficient,proto3" json:"improvement_rate_coefficient,omitempty"`
	// Parameter that specifies the distance between improvements taken into
	// consideration for calculating the improvement rate.
	// Example: For 5 objective improvements = (10, 8, 6, 4, 2), and the
	// solutions_distance parameter of 2, then the improvement_rate will be
	// computed for (10, 6), (8, 4), and (6, 2).
	ImprovementRateSolutionsDistance int32 `protobuf:"varint,39,opt,name=improvement_rate_solutions_distance,json=improvementRateSolutionsDistance,proto3" json:"improvement_rate_solutions_distance,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *RoutingSearchParameters_ImprovementSearchLimitParameters) Reset() {
	*x = RoutingSearchParameters_ImprovementSearchLimitParameters{}
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSearchParameters_ImprovementSearchLimitParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSearchParameters_ImprovementSearchLimitParameters) ProtoMessage() {}

func (x *RoutingSearchParameters_ImprovementSearchLimitParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_parameters_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSearchParameters_ImprovementSearchLimitParameters.ProtoReflect.Descriptor instead.
func (*RoutingSearchParameters_ImprovementSearchLimitParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_parameters_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RoutingSearchParameters_ImprovementSearchLimitParameters) GetImprovementRateCoefficient() float64 {
	if x != nil {
		return x.ImprovementRateCoefficient
	}
	return 0
}

func (x *RoutingSearchParameters_ImprovementSearchLimitParameters) GetImprovementRateSolutionsDistance() int32 {
	if x != nil {
		return x.ImprovementRateSolutionsDistance
	}
	return 0
}

var File_ortools_constraint_solver_routing_parameters_proto protoreflect.FileDescriptor

const file_ortools_constraint_solver_routing_parameters_proto_rawDesc = "" +
	"\n" +
	"2ortools/constraint_solver/routing_parameters.proto\x12\x13operations_research\x1a\x1egoogle/protobuf/duration.proto\x1a-ortools/constraint_solver/routing_enums.proto\x1a<ortools/constraint_solver/routing_heuristic_parameters.proto\x1a+ortools/constraint_solver/routing_ils.proto\x1a1ortools/constraint_solver/solver_parameters.proto\x1a ortools/sat/sat_parameters.proto\x1a#ortools/util/optional_boolean.proto\"\x9fE\n" +
	"\x17RoutingSearchParameters\x12h\n" +
	"\x17first_solution_strategy\x18\x01 \x01(\x0e20.operations_research.FirstSolutionStrategy.ValueR\x15firstSolutionStrategy\x12R\n" +
	"&use_unfiltered_first_solution_strategy\x18\x02 \x01(\bR\"useUnfilteredFirstSolutionStrategy\x12U\n" +
	"\x12savings_parameters\x18F \x01(\v2&.operations_research.SavingsParametersR\x11savingsParameters\x12\xa3\x01\n" +
	"3global_cheapest_insertion_first_solution_parameters\x18G \x01(\v26.operations_research.GlobalCheapestInsertionParametersR.globalCheapestInsertionFirstSolutionParameters\x12\x9d\x01\n" +
	"0global_cheapest_insertion_ls_operator_parameters\x18H \x01(\v26.operations_research.GlobalCheapestInsertionParametersR+globalCheapestInsertionLsOperatorParameters\x12\x84\x01\n" +
	"#local_cheapest_insertion_parameters\x18D \x01(\v25.operations_research.LocalCheapestInsertionParametersR localCheapestInsertionParameters\x12\x8d\x01\n" +
	"(local_cheapest_cost_insertion_parameters\x18E \x01(\v25.operations_research.LocalCheapestInsertionParametersR$localCheapestCostInsertionParameters\x12I\n" +
	"!christofides_use_minimum_matching\x18\x1e \x01(\bR\x1echristofidesUseMinimumMatching\x12K\n" +
	"\"first_solution_optimization_period\x18; \x01(\x05R\x1ffirstSolutionOptimizationPeriod\x12\x83\x01\n" +
	"\x16local_search_operators\x18\x03 \x01(\v2M.operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperatorsR\x14localSearchOperators\x12=\n" +
	"\x1bls_operator_neighbors_ratio\x185 \x01(\x01R\x18lsOperatorNeighborsRatio\x129\n" +
	"\x19ls_operator_min_neighbors\x186 \x01(\x05R\x16lsOperatorMinNeighbors\x12]\n" +
	",use_multi_armed_bandit_concatenate_operators\x18) \x01(\bR'useMultiArmedBanditConcatenateOperators\x12r\n" +
	"7multi_armed_bandit_compound_operator_memory_coefficient\x18* \x01(\x01R1multiArmedBanditCompoundOperatorMemoryCoefficient\x12|\n" +
	"<multi_armed_bandit_compound_operator_exploration_coefficient\x18+ \x01(\x01R6multiArmedBanditCompoundOperatorExplorationCoefficient\x12:\n" +
	"\x1amax_swap_active_chain_size\x18B \x01(\x05R\x16maxSwapActiveChainSize\x12^\n" +
	"-relocate_expensive_chain_num_arcs_to_consider\x18\x14 \x01(\x05R'relocateExpensiveChainNumArcsToConsider\x12g\n" +
	"2heuristic_expensive_chain_lns_num_arcs_to_consider\x18  \x01(\x05R+heuristicExpensiveChainLnsNumArcsToConsider\x12K\n" +
	"#heuristic_close_nodes_lns_num_nodes\x18# \x01(\x05R\x1eheuristicCloseNodesLnsNumNodes\x12q\n" +
	"\x1alocal_search_metaheuristic\x18\x04 \x01(\x0e23.operations_research.LocalSearchMetaheuristic.ValueR\x18localSearchMetaheuristic\x12s\n" +
	"\x1blocal_search_metaheuristics\x18? \x03(\x0e23.operations_research.LocalSearchMetaheuristic.ValueR\x19localSearchMetaheuristics\x12d\n" +
	"0num_max_local_optima_before_metaheuristic_switch\x18@ \x01(\x05R*numMaxLocalOptimaBeforeMetaheuristicSwitch\x12R\n" +
	"&guided_local_search_lambda_coefficient\x18\x05 \x01(\x01R\"guidedLocalSearchLambdaCoefficient\x12r\n" +
	"8guided_local_search_reset_penalties_on_new_best_solution\x183 \x01(\bR0guidedLocalSearchResetPenaltiesOnNewBestSolution\x12f\n" +
	"1guided_local_search_penalize_with_vehicle_classes\x18= \x01(\bR+guidedLocalSearchPenalizeWithVehicleClasses\x12x\n" +
	";use_guided_local_search_penalties_in_local_search_operators\x18> \x01(\bR3useGuidedLocalSearchPenaltiesInLocalSearchOperators\x123\n" +
	"\x16use_depth_first_search\x18\x06 \x01(\bR\x13useDepthFirstSearch\x12;\n" +
	"\x06use_cp\x18\x1c \x01(\x0e2$.operations_research.OptionalBooleanR\x05useCp\x12B\n" +
	"\n" +
	"use_cp_sat\x18\x1b \x01(\x0e2$.operations_research.OptionalBooleanR\buseCpSat\x12Y\n" +
	"\x16use_generalized_cp_sat\x18/ \x01(\x0e2$.operations_research.OptionalBooleanR\x13useGeneralizedCpSat\x12M\n" +
	"\x0esat_parameters\x180 \x01(\v2&.operations_research.sat.SatParametersR\rsatParameters\x12N\n" +
	"$report_intermediate_cp_sat_solutions\x188 \x01(\bR reportIntermediateCpSatSolutions\x12G\n" +
	"!fallback_to_cp_sat_size_threshold\x184 \x01(\x05R\x1cfallbackToCpSatSizeThreshold\x12\x7f\n" +
	"\x1ccontinuous_scheduling_solver\x18! \x01(\x0e2=.operations_research.RoutingSearchParameters.SchedulingSolverR\x1acontinuousSchedulingSolver\x12\x84\x01\n" +
	"\x1fmixed_integer_scheduling_solver\x18\" \x01(\x0e2=.operations_research.RoutingSearchParameters.SchedulingSolverR\x1cmixedIntegerSchedulingSolver\x12u\n" +
	"6disable_scheduling_beware_this_may_degrade_performance\x182 \x01(\bH\x00R0disableSchedulingBewareThisMayDegradePerformance\x88\x01\x01\x12+\n" +
	"\x11optimization_step\x18\a \x01(\x01R\x10optimizationStep\x12B\n" +
	"\x1enumber_of_solutions_to_collect\x18\x11 \x01(\x05R\x1anumberOfSolutionsToCollect\x12%\n" +
	"\x0esolution_limit\x18\b \x01(\x03R\rsolutionLimit\x128\n" +
	"\n" +
	"time_limit\x18\t \x01(\v2\x19.google.protobuf.DurationR\ttimeLimit\x12?\n" +
	"\x0elns_time_limit\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\flnsTimeLimit\x12@\n" +
	"\x1dsecondary_ls_time_limit_ratio\x189 \x01(\x01R\x19secondaryLsTimeLimitRatio\x12\x8f\x01\n" +
	"\x1cimprovement_limit_parameters\x18% \x01(\v2M.operations_research.RoutingSearchParameters.ImprovementSearchLimitParametersR\x1aimprovementLimitParameters\x120\n" +
	"\x14use_full_propagation\x18\v \x01(\bR\x12useFullPropagation\x12\x1d\n" +
	"\n" +
	"log_search\x18\r \x01(\bR\tlogSearch\x125\n" +
	"\x17log_cost_scaling_factor\x18\x16 \x01(\x01R\x14logCostScalingFactor\x12&\n" +
	"\x0flog_cost_offset\x18\x1d \x01(\x01R\rlogCostOffset\x12\x17\n" +
	"\alog_tag\x18$ \x01(\tR\x06logTag\x129\n" +
	"\x19use_iterated_local_search\x18: \x01(\bR\x16useIteratedLocalSearch\x12{\n" +
	" iterated_local_search_parameters\x18< \x01(\v22.operations_research.IteratedLocalSearchParametersR\x1diteratedLocalSearchParameters\x1a\xd7\x1e\n" +
	" LocalSearchNeighborhoodOperators\x12G\n" +
	"\fuse_relocate\x18\x01 \x01(\x0e2$.operations_research.OptionalBooleanR\vuseRelocate\x12P\n" +
	"\x11use_relocate_pair\x18\x02 \x01(\x0e2$.operations_research.OptionalBooleanR\x0fuseRelocatePair\x12[\n" +
	"\x17use_light_relocate_pair\x18\x18 \x01(\x0e2$.operations_research.OptionalBooleanR\x14useLightRelocatePair\x12Z\n" +
	"\x16use_relocate_neighbors\x18\x03 \x01(\x0e2$.operations_research.OptionalBooleanR\x14useRelocateNeighbors\x12V\n" +
	"\x14use_relocate_subtrip\x18\x19 \x01(\x0e2$.operations_research.OptionalBooleanR\x12useRelocateSubtrip\x12G\n" +
	"\fuse_exchange\x18\x04 \x01(\x0e2$.operations_research.OptionalBooleanR\vuseExchange\x12P\n" +
	"\x11use_exchange_pair\x18\x16 \x01(\x0e2$.operations_research.OptionalBooleanR\x0fuseExchangePair\x12V\n" +
	"\x14use_exchange_subtrip\x18\x1a \x01(\x0e2$.operations_research.OptionalBooleanR\x12useExchangeSubtrip\x12A\n" +
	"\tuse_cross\x18\x05 \x01(\x0e2$.operations_research.OptionalBooleanR\buseCross\x12R\n" +
	"\x12use_cross_exchange\x18\x06 \x01(\x0e2$.operations_research.OptionalBooleanR\x10useCrossExchange\x12e\n" +
	"\x1cuse_relocate_expensive_chain\x18\x17 \x01(\x0e2$.operations_research.OptionalBooleanR\x19useRelocateExpensiveChain\x12D\n" +
	"\vuse_two_opt\x18\a \x01(\x0e2$.operations_research.OptionalBooleanR\tuseTwoOpt\x12B\n" +
	"\n" +
	"use_or_opt\x18\b \x01(\x0e2$.operations_research.OptionalBooleanR\buseOrOpt\x12P\n" +
	"\x11use_lin_kernighan\x18\t \x01(\x0e2$.operations_research.OptionalBooleanR\x0fuseLinKernighan\x12D\n" +
	"\vuse_tsp_opt\x18\n" +
	" \x01(\x0e2$.operations_research.OptionalBooleanR\tuseTspOpt\x12L\n" +
	"\x0fuse_make_active\x18\v \x01(\x0e2$.operations_research.OptionalBooleanR\ruseMakeActive\x12d\n" +
	"\x1cuse_relocate_and_make_active\x18\x15 \x01(\x0e2$.operations_research.OptionalBooleanR\x18useRelocateAndMakeActive\x12d\n" +
	"\x1cuse_exchange_and_make_active\x18% \x01(\x0e2$.operations_research.OptionalBooleanR\x18useExchangeAndMakeActive\x12\x81\x01\n" +
	",use_exchange_path_start_ends_and_make_active\x18& \x01(\x0e2$.operations_research.OptionalBooleanR%useExchangePathStartEndsAndMakeActive\x12P\n" +
	"\x11use_make_inactive\x18\f \x01(\x0e2$.operations_research.OptionalBooleanR\x0fuseMakeInactive\x12[\n" +
	"\x17use_make_chain_inactive\x18\r \x01(\x0e2$.operations_research.OptionalBooleanR\x14useMakeChainInactive\x12L\n" +
	"\x0fuse_swap_active\x18\x0e \x01(\x0e2$.operations_research.OptionalBooleanR\ruseSwapActive\x12W\n" +
	"\x15use_swap_active_chain\x18# \x01(\x0e2$.operations_research.OptionalBooleanR\x12useSwapActiveChain\x12]\n" +
	"\x18use_extended_swap_active\x18\x0f \x01(\x0e2$.operations_research.OptionalBooleanR\x15useExtendedSwapActive\x12f\n" +
	"\x1duse_shortest_path_swap_active\x18\" \x01(\x0e2$.operations_research.OptionalBooleanR\x19useShortestPathSwapActive\x12^\n" +
	"\x19use_shortest_path_two_opt\x18$ \x01(\x0e2$.operations_research.OptionalBooleanR\x15useShortestPathTwoOpt\x12^\n" +
	"\x19use_node_pair_swap_active\x18\x14 \x01(\x0e2$.operations_research.OptionalBooleanR\x15useNodePairSwapActive\x12F\n" +
	"\fuse_path_lns\x18\x10 \x01(\x0e2$.operations_research.OptionalBooleanR\n" +
	"usePathLns\x12O\n" +
	"\x11use_full_path_lns\x18\x11 \x01(\x0e2$.operations_research.OptionalBooleanR\x0euseFullPathLns\x12D\n" +
	"\vuse_tsp_lns\x18\x12 \x01(\x0e2$.operations_research.OptionalBooleanR\tuseTspLns\x12N\n" +
	"\x10use_inactive_lns\x18\x13 \x01(\x0e2$.operations_research.OptionalBooleanR\x0euseInactiveLns\x12w\n" +
	"&use_global_cheapest_insertion_path_lns\x18\x1b \x01(\x0e2$.operations_research.OptionalBooleanR!useGlobalCheapestInsertionPathLns\x12u\n" +
	"%use_local_cheapest_insertion_path_lns\x18\x1c \x01(\x0e2$.operations_research.OptionalBooleanR useLocalCheapestInsertionPathLns\x12\xa5\x01\n" +
	">use_relocate_path_global_cheapest_insertion_insert_unperformed\x18! \x01(\x0e2$.operations_research.OptionalBooleanR7useRelocatePathGlobalCheapestInsertionInsertUnperformed\x12\x8c\x01\n" +
	"1use_global_cheapest_insertion_expensive_chain_lns\x18\x1d \x01(\x0e2$.operations_research.OptionalBooleanR+useGlobalCheapestInsertionExpensiveChainLns\x12\x8a\x01\n" +
	"0use_local_cheapest_insertion_expensive_chain_lns\x18\x1e \x01(\x0e2$.operations_research.OptionalBooleanR*useLocalCheapestInsertionExpensiveChainLns\x12\x84\x01\n" +
	"-use_global_cheapest_insertion_close_nodes_lns\x18\x1f \x01(\x0e2$.operations_research.OptionalBooleanR'useGlobalCheapestInsertionCloseNodesLns\x12\x82\x01\n" +
	",use_local_cheapest_insertion_close_nodes_lns\x18  \x01(\x0e2$.operations_research.OptionalBooleanR&useLocalCheapestInsertionCloseNodesLns\x12\x84\x01\n" +
	"-use_global_cheapest_insertion_visit_types_lns\x18' \x01(\x0e2$.operations_research.OptionalBooleanR'useGlobalCheapestInsertionVisitTypesLns\x12\x82\x01\n" +
	",use_local_cheapest_insertion_visit_types_lns\x18( \x01(\x0e2$.operations_research.OptionalBooleanR&useLocalCheapestInsertionVisitTypesLns\x1a\xb3\x01\n" +
	" ImprovementSearchLimitParameters\x12@\n" +
	"\x1cimprovement_rate_coefficient\x18& \x01(\x01R\x1aimprovementRateCoefficient\x12M\n" +
	"#improvement_rate_solutions_distance\x18' \x01(\x05R improvementRateSolutionsDistance\"T\n" +
	"\x10SchedulingSolver\x12\x14\n" +
	"\x10SCHEDULING_UNSET\x10\x00\x12\x13\n" +
	"\x0fSCHEDULING_GLOP\x10\x01\x12\x15\n" +
	"\x11SCHEDULING_CP_SAT\x10\x02B9\n" +
	"7_disable_scheduling_beware_this_may_degrade_performanceJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x12\x10\x13J\x04\b\x13\x10\x14J\x04\b\x15\x10\x16J\x04\b\x17\x10\x18J\x04\b\x1f\x10 J\x04\b(\x10)J\x04\b,\x10-J\x04\b-\x10.J\x04\b.\x10/J\x04\b1\x102J\x04\b7\x108J\x04\bA\x10BJ\x04\bC\x10D\"\xe8\x01\n" +
	"\x16RoutingModelParameters\x12\\\n" +
	"\x11solver_parameters\x18\x01 \x01(\v2/.operations_research.ConstraintSolverParametersR\x10solverParameters\x129\n" +
	"\x19reduce_vehicle_cost_model\x18\x02 \x01(\bR\x16reduceVehicleCostModel\x125\n" +
	"\x17max_callback_cache_size\x18\x03 \x01(\x05R\x14maxCallbackCacheSizeB\x8f\x01\n" +
	"#com.google.ortools.constraintsolverP\x01ZDgithub.com/airspacetechnologies/or-tools/go/ortools/constraintsolver\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3"

var (
	file_ortools_constraint_solver_routing_parameters_proto_rawDescOnce sync.Once
	file_ortools_constraint_solver_routing_parameters_proto_rawDescData []byte
)

func file_ortools_constraint_solver_routing_parameters_proto_rawDescGZIP() []byte {
	file_ortools_constraint_solver_routing_parameters_proto_rawDescOnce.Do(func() {
		file_ortools_constraint_solver_routing_parameters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_parameters_proto_rawDesc), len(file_ortools_constraint_solver_routing_parameters_proto_rawDesc)))
	})
	return file_ortools_constraint_solver_routing_parameters_proto_rawDescData
}

var file_ortools_constraint_solver_routing_parameters_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ortools_constraint_solver_routing_parameters_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ortools_constraint_solver_routing_parameters_proto_goTypes = []any{
	(RoutingSearchParameters_SchedulingSolver)(0),                    // 0: operations_research.RoutingSearchParameters.SchedulingSolver
	(*RoutingSearchParameters)(nil),                                  // 1: operations_research.RoutingSearchParameters
	(*RoutingModelParameters)(nil),                                   // 2: operations_research.RoutingModelParameters
	(*RoutingSearchParameters_LocalSearchNeighborhoodOperators)(nil), // 3: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators
	(*RoutingSearchParameters_ImprovementSearchLimitParameters)(nil), // 4: operations_research.RoutingSearchParameters.ImprovementSearchLimitParameters
	(FirstSolutionStrategy_Value)(0),                                 // 5: operations_research.FirstSolutionStrategy.Value
	(*SavingsParameters)(nil),                                        // 6: operations_research.SavingsParameters
	(*GlobalCheapestInsertionParameters)(nil),                        // 7: operations_research.GlobalCheapestInsertionParameters
	(*LocalCheapestInsertionParameters)(nil),                         // 8: operations_research.LocalCheapestInsertionParameters
	(LocalSearchMetaheuristic_Value)(0),                              // 9: operations_research.LocalSearchMetaheuristic.Value
	(util.OptionalBoolean)(0),                                        // 10: operations_research.OptionalBoolean
	(*sat.SatParameters)(nil),                                        // 11: operations_research.sat.SatParameters
	(*durationpb.Duration)(nil),                                      // 12: google.protobuf.Duration
	(*IteratedLocalSearchParameters)(nil),                            // 13: operations_research.IteratedLocalSearchParameters
	(*ConstraintSolverParameters)(nil),                               // 14: operations_research.ConstraintSolverParameters
}
var file_ortools_constraint_solver_routing_parameters_proto_depIdxs = []int32{
	5,  // 0: operations_research.RoutingSearchParameters.first_solution_strategy:type_name -> operations_research.FirstSolutionStrategy.Value
	6,  // 1: operations_research.RoutingSearchParameters.savings_parameters:type_name -> operations_research.SavingsParameters
	7,  // 2: operations_research.RoutingSearchParameters.global_cheapest_insertion_first_solution_parameters:type_name -> operations_research.GlobalCheapestInsertionParameters
	7,  // 3: operations_research.RoutingSearchParameters.global_cheapest_insertion_ls_operator_parameters:type_name -> operations_research.GlobalCheapestInsertionParameters
	8,  // 4: operations_research.RoutingSearchParameters.local_cheapest_insertion_parameters:type_name -> operations_research.LocalCheapestInsertionParameters
	8,  // 5: operations_research.RoutingSearchParameters.local_cheapest_cost_insertion_parameters:type_name -> operations_research.LocalCheapestInsertionParameters
	3,  // 6: operations_research.RoutingSearchParameters.local_search_operators:type_name -> operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators
	9,  // 7: operations_research.RoutingSearchParameters.local_search_metaheuristic:type_name -> operations_research.LocalSearchMetaheuristic.Value
	9,  // 8: operations_research.RoutingSearchParameters.local_search_metaheuristics:type_name -> operations_research.LocalSearchMetaheuristic.Value
	10, // 9: operations_research.RoutingSearchParameters.use_cp:type_name -> operations_research.OptionalBoolean
	10, // 10: operations_research.RoutingSearchParameters.use_cp_sat:type_name -> operations_research.OptionalBoolean
	10, // 11: operations_research.RoutingSearchParameters.use_generalized_cp_sat:type_name -> operations_research.OptionalBoolean
	11, // 12: operations_research.RoutingSearchParameters.sat_parameters:type_name -> operations_research.sat.SatParameters
	0,  // 13: operations_research.RoutingSearchParameters.continuous_scheduling_solver:type_name -> operations_research.RoutingSearchParameters.SchedulingSolver
	0,  // 14: operations_research.RoutingSearchParameters.mixed_integer_scheduling_solver:type_name -> operations_research.RoutingSearchParameters.SchedulingSolver
	12, // 15: operations_research.RoutingSearchParameters.time_limit:type_name -> google.protobuf.Duration
	12, // 16: operations_research.RoutingSearchParameters.lns_time_limit:type_name -> google.protobuf.Duration
	4,  // 17: operations_research.RoutingSearchParameters.improvement_limit_parameters:type_name -> operations_research.RoutingSearchParameters.ImprovementSearchLimitParameters
	13, // 18: operations_research.RoutingSearchParameters.iterated_local_search_parameters:type_name -> operations_research.IteratedLocalSearchParameters
	14, // 19: operations_research.RoutingModelParameters.solver_parameters:type_name -> operations_research.ConstraintSolverParameters
	10, // 20: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate:type_name -> operations_research.OptionalBoolean
	10, // 21: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_pair:type_name -> operations_research.OptionalBoolean
	10, // 22: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_light_relocate_pair:type_name -> operations_research.OptionalBoolean
	10, // 23: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_neighbors:type_name -> operations_research.OptionalBoolean
	10, // 24: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_subtrip:type_name -> operations_research.OptionalBoolean
	10, // 25: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange:type_name -> operations_research.OptionalBoolean
	10, // 26: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange_pair:type_name -> operations_research.OptionalBoolean
	10, // 27: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange_subtrip:type_name -> operations_research.OptionalBoolean
	10, // 28: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_cross:type_name -> operations_research.OptionalBoolean
	10, // 29: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_cross_exchange:type_name -> operations_research.OptionalBoolean
	10, // 30: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_expensive_chain:type_name -> operations_research.OptionalBoolean
	10, // 31: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_two_opt:type_name -> operations_research.OptionalBoolean
	10, // 32: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_or_opt:type_name -> operations_research.OptionalBoolean
	10, // 33: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_lin_kernighan:type_name -> operations_research.OptionalBoolean
	10, // 34: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_tsp_opt:type_name -> operations_research.OptionalBoolean
	10, // 35: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_active:type_name -> operations_research.OptionalBoolean
	10, // 36: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_and_make_active:type_name -> operations_research.OptionalBoolean
	10, // 37: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange_and_make_active:type_name -> operations_research.OptionalBoolean
	10, // 38: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange_path_start_ends_and_make_active:type_name -> operations_research.OptionalBoolean
	10, // 39: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_inactive:type_name -> operations_research.OptionalBoolean
	10, // 40: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_chain_inactive:type_name -> operations_research.OptionalBoolean
	10, // 41: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_swap_active:type_name -> operations_research.OptionalBoolean
	10, // 42: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_swap_active_chain:type_name -> operations_research.OptionalBoolean
	10, // 43: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_extended_swap_active:type_name -> operations_research.OptionalBoolean
	10, // 44: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_shortest_path_swap_active:type_name -> operations_research.OptionalBoolean
	10, // 45: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_shortest_path_two_opt:type_name -> operations_research.OptionalBoolean
	10, // 46: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_node_pair_swap_active:type_name -> operations_research.OptionalBoolean
	10, // 47: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_path_lns:type_name -> operations_research.OptionalBoolean
	10, // 48: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_full_path_lns:type_name -> operations_research.OptionalBoolean
	10, // 49: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_tsp_lns:type_name -> operations_research.OptionalBoolean
	10, // 50: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_inactive_lns:type_name -> operations_research.OptionalBoolean
	10, // 51: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_global_cheapest_insertion_path_lns:type_name -> operations_research.OptionalBoolean
	10, // 52: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_local_cheapest_insertion_path_lns:type_name -> operations_research.OptionalBoolean
	10, // 53: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_path_global_cheapest_insertion_insert_unperformed:type_name -> operations_research.OptionalBoolean
	10, // 54: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_global_cheapest_insertion_expensive_chain_lns:type_name -> operations_research.OptionalBoolean
	10, // 55: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_local_cheapest_insertion_expensive_chain_lns:type_name -> operations_research.OptionalBoolean
	10, // 56: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_global_cheapest_insertion_close_nodes_lns:type_name -> operations_research.OptionalBoolean
	10, // 57: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_local_cheapest_insertion_close_nodes_lns:type_name -> operations_research.OptionalBoolean
	10, // 58: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_global_cheapest_insertion_visit_types_lns:type_name -> operations_research.OptionalBoolean
	10, // 59: operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_local_cheapest_insertion_visit_types_lns:type_name -> operations_research.OptionalBoolean
	60, // [60:60] is the sub-list for method output_type
	60, // [60:60] is the sub-list for method input_type
	60, // [60:60] is the sub-list for extension type_name
	60, // [60:60] is the sub-list for extension extendee
	0,  // [0:60] is the sub-list for field type_name
}

func init() { file_ortools_constraint_solver_routing_parameters_proto_init() }
func file_ortools_constraint_solver_routing_parameters_proto_init() {
	if File_ortools_constraint_solver_routing_parameters_proto != nil {
		return
	}
	file_ortools_constraint_solver_routing_enums_proto_init()
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_init()
	file_ortools_constraint_solver_routing_ils_proto_init()
	file_ortools_constraint_solver_solver_parameters_proto_init()
	file_ortools_constraint_solver_routing_parameters_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_parameters_proto_rawDesc), len(file_ortools_constraint_solver_routing_parameters_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_constraint_solver_routing_parameters_proto_goTypes,
		DependencyIndexes: file_ortools_constraint_solver_routing_parameters_proto_depIdxs,
		EnumInfos:         file_ortools_constraint_solver_routing_parameters_proto_enumTypes,
		MessageInfos:      file_ortools_constraint_solver_routing_parameters_proto_msgTypes,
	}.Build()
	File_ortools_constraint_solver_routing_parameters_proto = out.File
	file_ortools_constraint_solver_routing_parameters_proto_goTypes = nil
	file_ortools_constraint_solver_routing_parameters_proto_depIdxs = nil
}
