// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer used to parametrize an iterated local search (ILS) approach.
// ILS is an iterative metaheuristic in which every iteration consists in
// performing a perturbation followed by an improvement step on a reference
// solution to generate a neighbor solution.
// The neighbor solution is accepted as the new reference solution according
// to an acceptance criterion.
// The best found solution is eventually returned.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: ortools/constraint_solver/routing_ils.proto

package constraintsolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuinCompositionStrategy_Value int32

const (
	// Unspecified value.
	RuinCompositionStrategy_UNSET RuinCompositionStrategy_Value = 0
	// Execute all ruin strategies sequentially in the same order provided in
	// input.
	RuinCompositionStrategy_RUN_ALL_SEQUENTIALLY RuinCompositionStrategy_Value = 1
	// Execute all ruin strategies in a random order.
	RuinCompositionStrategy_RUN_ALL_RANDOMLY RuinCompositionStrategy_Value = 2
	// Execute a randomly selected ruin.
	RuinCompositionStrategy_RUN_ONE_RANDOMLY RuinCompositionStrategy_Value = 3
)

// Enum value maps for RuinCompositionStrategy_Value.
var (
	RuinCompositionStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "RUN_ALL_SEQUENTIALLY",
		2: "RUN_ALL_RANDOMLY",
		3: "RUN_ONE_RANDOMLY",
	}
	RuinCompositionStrategy_Value_value = map[string]int32{
		"UNSET":                0,
		"RUN_ALL_SEQUENTIALLY": 1,
		"RUN_ALL_RANDOMLY":     2,
		"RUN_ONE_RANDOMLY":     3,
	}
)

func (x RuinCompositionStrategy_Value) Enum() *RuinCompositionStrategy_Value {
	p := new(RuinCompositionStrategy_Value)
	*p = x
	return p
}

func (x RuinCompositionStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuinCompositionStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[0].Descriptor()
}

func (RuinCompositionStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[0]
}

func (x RuinCompositionStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuinCompositionStrategy_Value.Descriptor instead.
func (RuinCompositionStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{4, 0}
}

type PerturbationStrategy_Value int32

const (
	// Unspecified value.
	PerturbationStrategy_UNSET PerturbationStrategy_Value = 0
	// Performs a perturbation in a ruin and recreate fashion.
	PerturbationStrategy_RUIN_AND_RECREATE PerturbationStrategy_Value = 1
)

// Enum value maps for PerturbationStrategy_Value.
var (
	PerturbationStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "RUIN_AND_RECREATE",
	}
	PerturbationStrategy_Value_value = map[string]int32{
		"UNSET":             0,
		"RUIN_AND_RECREATE": 1,
	}
)

func (x PerturbationStrategy_Value) Enum() *PerturbationStrategy_Value {
	p := new(PerturbationStrategy_Value)
	*p = x
	return p
}

func (x PerturbationStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PerturbationStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[1].Descriptor()
}

func (PerturbationStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[1]
}

func (x PerturbationStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PerturbationStrategy_Value.Descriptor instead.
func (PerturbationStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{6, 0}
}

type CoolingScheduleStrategy_Value int32

const (
	// Unspecified value.
	CoolingScheduleStrategy_UNSET CoolingScheduleStrategy_Value = 0
	// Exponentially decreases the temperature as the search progresses.
	// More precisely, t = t0 * (t1/t0)^p.
	CoolingScheduleStrategy_EXPONENTIAL CoolingScheduleStrategy_Value = 1
	// Linearly decreases the temperature as the search progresses.
	// More precisely, t = t0 - p * (t0 - t1).
	CoolingScheduleStrategy_LINEAR CoolingScheduleStrategy_Value = 2
)

// Enum value maps for CoolingScheduleStrategy_Value.
var (
	CoolingScheduleStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "EXPONENTIAL",
		2: "LINEAR",
	}
	CoolingScheduleStrategy_Value_value = map[string]int32{
		"UNSET":       0,
		"EXPONENTIAL": 1,
		"LINEAR":      2,
	}
)

func (x CoolingScheduleStrategy_Value) Enum() *CoolingScheduleStrategy_Value {
	p := new(CoolingScheduleStrategy_Value)
	*p = x
	return p
}

func (x CoolingScheduleStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoolingScheduleStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[2].Descriptor()
}

func (CoolingScheduleStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[2]
}

func (x CoolingScheduleStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoolingScheduleStrategy_Value.Descriptor instead.
func (CoolingScheduleStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{7, 0}
}

type AcceptanceStrategy_Value int32

const (
	// Unspecified value.
	AcceptanceStrategy_UNSET AcceptanceStrategy_Value = 0
	// Accepts only solutions that are improving with respect to the reference
	// one.
	AcceptanceStrategy_GREEDY_DESCENT AcceptanceStrategy_Value = 1
	// Accepts a candidate solution with a probability that depends on its
	// quality and on the current state of the search.
	AcceptanceStrategy_SIMULATED_ANNEALING AcceptanceStrategy_Value = 2
)

// Enum value maps for AcceptanceStrategy_Value.
var (
	AcceptanceStrategy_Value_name = map[int32]string{
		0: "UNSET",
		1: "GREEDY_DESCENT",
		2: "SIMULATED_ANNEALING",
	}
	AcceptanceStrategy_Value_value = map[string]int32{
		"UNSET":               0,
		"GREEDY_DESCENT":      1,
		"SIMULATED_ANNEALING": 2,
	}
)

func (x AcceptanceStrategy_Value) Enum() *AcceptanceStrategy_Value {
	p := new(AcceptanceStrategy_Value)
	*p = x
	return p
}

func (x AcceptanceStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcceptanceStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_ils_proto_enumTypes[3].Descriptor()
}

func (AcceptanceStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_ils_proto_enumTypes[3]
}

func (x AcceptanceStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcceptanceStrategy_Value.Descriptor instead.
func (AcceptanceStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{9, 0}
}

// Ruin strategy that removes a number of spatially close routes.
type SpatiallyCloseRoutesRuinStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of spatially close routes ruined at each ruin application.
	NumRuinedRoutes *uint32 `protobuf:"varint,3,opt,name=num_ruined_routes,json=numRuinedRoutes,proto3,oneof" json:"num_ruined_routes,omitempty"`
}

func (x *SpatiallyCloseRoutesRuinStrategy) Reset() {
	*x = SpatiallyCloseRoutesRuinStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpatiallyCloseRoutesRuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatiallyCloseRoutesRuinStrategy) ProtoMessage() {}

func (x *SpatiallyCloseRoutesRuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatiallyCloseRoutesRuinStrategy.ProtoReflect.Descriptor instead.
func (*SpatiallyCloseRoutesRuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{0}
}

func (x *SpatiallyCloseRoutesRuinStrategy) GetNumRuinedRoutes() uint32 {
	if x != nil && x.NumRuinedRoutes != nil {
		return *x.NumRuinedRoutes
	}
	return 0
}

// Ruin strategy that removes a number of customers by performing a random walk
// on the underlying routing solution. More precisely, starting from a randomly
// selected seed visit, the walk is extended by either moving within the
// same route or by jumping to a visit served by a different neighboring
// route. Every active visit encountered along this random walk is made
// unperformed.
type RandomWalkRuinStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of visits removed during a ruin application defined on visits.
	// Note that pickup and delivery pairs are considered as a single entity,
	// i.e., the removal of a pickup (respectively delivery) causes the removal of
	// the associated delivery (respectively pickup) and it counts as a single
	// removal.
	NumRemovedVisits *uint32 `protobuf:"varint,7,opt,name=num_removed_visits,json=numRemovedVisits,proto3,oneof" json:"num_removed_visits,omitempty"`
}

func (x *RandomWalkRuinStrategy) Reset() {
	*x = RandomWalkRuinStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomWalkRuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomWalkRuinStrategy) ProtoMessage() {}

func (x *RandomWalkRuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomWalkRuinStrategy.ProtoReflect.Descriptor instead.
func (*RandomWalkRuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{1}
}

func (x *RandomWalkRuinStrategy) GetNumRemovedVisits() uint32 {
	if x != nil && x.NumRemovedVisits != nil {
		return *x.NumRemovedVisits
	}
	return 0
}

// Ruin strategy based on the "Slack Induction by String Removals for Vehicle
// Routing Problems" by Jan Christiaens and Greet Vanden Berghe, Transportation
// Science 2020.
// Link to paper:
// https://kuleuven.limo.libis.be/discovery/fulldisplay?docid=lirias1988666&context=SearchWebhook&vid=32KUL_KUL:Lirias&lang=en&search_scope=lirias_profile&adaptor=SearchWebhook&tab=LIRIAS&query=any,contains,LIRIAS1988666&offset=0
//
// Note that, in this implementation, the notion of "string" is replaced by
// "sequence".
//
// The main idea of this ruin is to remove a number of geographically close
// sequences of nodes. In particular, at every ruin application, a maximum
// number max_ruined_routes of routes are disrupted. The value for
// max_ruined_routes is defined as
//
//	(4 * avg_num_removed_visits) / (1 + max_sequence_size) + 1
//
// with
//   - avg_num_removed_visits: user-defined parameter ruling the average number of
//     visits that are removed in face of several ruin applications (see also the
//     proto message below)
//   - max_sequence_size is defined as
//     min{max_removed_sequence_size, average_route_size}
//     with
//   - max_removed_sequence_size: user-defined parameter that specifies
//     the maximum number of visits removed from a single route (see also the
//     proto message below)
//   - average_route_size: the average size of a non-empty route in the current
//     solution
//
// The actual number of ruined routes is then obtained as
//
//	floor(U(1, max_ruined_routes + 1))
//
// where U is a continuous uniform distribution of real values in the given
// interval.
//
// The routes affected by the ruin procedure are selected as follows.
// First, a non start/end seed node is randomly selected. The route serving this
// node is the first ruined route. Then, until the required number of routes has
// been ruined, neighbor nodes of the initial seed node are scanned and the
// associated not yet ruined routes are disrupted. Nodes defining the selected
// routes are designated as seed nodes for the "sequence" and "split sequence"
// removal procedures described below.
//
// For every selected route, a maximum number route_max_sequence_size of nodes
// are removed. In particular, route_max_sequence_size is defined as
//
//	min{route_size, max_sequence_size}
//
// with route_size being the size of the current route.
//
// Then, the actual number of removed nodes num_removed_nodes is defined as
//
//	floor(U(1, route_max_sequence_size + 1))
//
// where U is a continuous uniform distribution of real values in the given
// interval.
//
// As mentioned above, the selected num_removed_nodes number of nodes is removed
// either via the "sequence" removal or "split sequence" removal procedures. The
// two removal procedures are executed with equal probabilities.
//
// The "sequence" removal procedure removes a randomly selected sequence of size
// num_removed_nodes that includes the seed node.
//
// The "split sequence" removal procedure also removes a randomly selected
// sequence of size num_removed_nodes that includes the seed node, but it can
// possibly preserve a subsequence of contiguous nodes.
// In particular, the procedure first selects a sequence of size
// num_removed_nodes + num_bypassed, then num_bypassed contiguous nodes in the
// selected sequence are preserved while the others removed.
//
// The definition of num_bypassed is as follows. First num_bypassed = 1. The
// current value of num_bypassed is maintaned if
//
//	U(0, 1) < bypass_factor * U(0, 1)
//
// or the maximum value for num_bypassed, equal to
//
//	route_size - num_removed_nodes
//
// is reached. The value is incremented of a unit otherwise,
// and the process is repeated. The value assigned to bypass_factor affects the
// number of preserved visits (see also the proto message below).
type SISRRuinStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum number of removed visits per sequence. The parameter name in the
	// paper is L^{max} and the suggested value is 10.
	MaxRemovedSequenceSize *uint32 `protobuf:"varint,1,opt,name=max_removed_sequence_size,json=maxRemovedSequenceSize,proto3,oneof" json:"max_removed_sequence_size,omitempty"`
	// Number of visits that are removed on average. The parameter name in the
	// paper is \bar{c} and the suggested value is 10.
	AvgNumRemovedVisits *uint32 `protobuf:"varint,2,opt,name=avg_num_removed_visits,json=avgNumRemovedVisits,proto3,oneof" json:"avg_num_removed_visits,omitempty"`
	// Value in [0, 1] ruling the number of preserved customers in the split
	// sequence removal. The parameter name in the paper is \alpha and the
	// suggested value is 0.01.
	BypassFactor *float64 `protobuf:"fixed64,3,opt,name=bypass_factor,json=bypassFactor,proto3,oneof" json:"bypass_factor,omitempty"`
}

func (x *SISRRuinStrategy) Reset() {
	*x = SISRRuinStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SISRRuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SISRRuinStrategy) ProtoMessage() {}

func (x *SISRRuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SISRRuinStrategy.ProtoReflect.Descriptor instead.
func (*SISRRuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{2}
}

func (x *SISRRuinStrategy) GetMaxRemovedSequenceSize() uint32 {
	if x != nil && x.MaxRemovedSequenceSize != nil {
		return *x.MaxRemovedSequenceSize
	}
	return 0
}

func (x *SISRRuinStrategy) GetAvgNumRemovedVisits() uint32 {
	if x != nil && x.AvgNumRemovedVisits != nil {
		return *x.AvgNumRemovedVisits
	}
	return 0
}

func (x *SISRRuinStrategy) GetBypassFactor() float64 {
	if x != nil && x.BypassFactor != nil {
		return *x.BypassFactor
	}
	return 0
}

// Ruin strategies, used in perturbation based on ruin and recreate approaches.
type RuinStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Strategy:
	//
	//	*RuinStrategy_SpatiallyCloseRoutes
	//	*RuinStrategy_RandomWalk
	//	*RuinStrategy_Sisr
	Strategy isRuinStrategy_Strategy `protobuf_oneof:"strategy"`
}

func (x *RuinStrategy) Reset() {
	*x = RuinStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuinStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinStrategy) ProtoMessage() {}

func (x *RuinStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinStrategy.ProtoReflect.Descriptor instead.
func (*RuinStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{3}
}

func (m *RuinStrategy) GetStrategy() isRuinStrategy_Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (x *RuinStrategy) GetSpatiallyCloseRoutes() *SpatiallyCloseRoutesRuinStrategy {
	if x, ok := x.GetStrategy().(*RuinStrategy_SpatiallyCloseRoutes); ok {
		return x.SpatiallyCloseRoutes
	}
	return nil
}

func (x *RuinStrategy) GetRandomWalk() *RandomWalkRuinStrategy {
	if x, ok := x.GetStrategy().(*RuinStrategy_RandomWalk); ok {
		return x.RandomWalk
	}
	return nil
}

func (x *RuinStrategy) GetSisr() *SISRRuinStrategy {
	if x, ok := x.GetStrategy().(*RuinStrategy_Sisr); ok {
		return x.Sisr
	}
	return nil
}

type isRuinStrategy_Strategy interface {
	isRuinStrategy_Strategy()
}

type RuinStrategy_SpatiallyCloseRoutes struct {
	SpatiallyCloseRoutes *SpatiallyCloseRoutesRuinStrategy `protobuf:"bytes,1,opt,name=spatially_close_routes,json=spatiallyCloseRoutes,proto3,oneof"`
}

type RuinStrategy_RandomWalk struct {
	RandomWalk *RandomWalkRuinStrategy `protobuf:"bytes,2,opt,name=random_walk,json=randomWalk,proto3,oneof"`
}

type RuinStrategy_Sisr struct {
	Sisr *SISRRuinStrategy `protobuf:"bytes,3,opt,name=sisr,proto3,oneof"`
}

func (*RuinStrategy_SpatiallyCloseRoutes) isRuinStrategy_Strategy() {}

func (*RuinStrategy_RandomWalk) isRuinStrategy_Strategy() {}

func (*RuinStrategy_Sisr) isRuinStrategy_Strategy() {}

// The ruin composition strategies specifies how ruin are selected at every ILS
// iteration.
type RuinCompositionStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuinCompositionStrategy) Reset() {
	*x = RuinCompositionStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuinCompositionStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinCompositionStrategy) ProtoMessage() {}

func (x *RuinCompositionStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinCompositionStrategy.ProtoReflect.Descriptor instead.
func (*RuinCompositionStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{4}
}

// Parameters to configure a perturbation based on a ruin and recreate approach.
type RuinRecreateParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of ruin strategies determining how a reference solution is ruined.
	RuinStrategies []*RuinStrategy `protobuf:"bytes,1,rep,name=ruin_strategies,json=ruinStrategies,proto3" json:"ruin_strategies,omitempty"`
	// The composition strategy to use when combining the given 'ruin_strategies'.
	// Has no effect when ruin_strategies is composed of a single strategy.
	RuinCompositionStrategy RuinCompositionStrategy_Value `protobuf:"varint,2,opt,name=ruin_composition_strategy,json=ruinCompositionStrategy,proto3,enum=operations_research.RuinCompositionStrategy_Value" json:"ruin_composition_strategy,omitempty"`
	// Strategy defining how a reference solution is recreated.
	RecreateStrategy FirstSolutionStrategy_Value `protobuf:"varint,3,opt,name=recreate_strategy,json=recreateStrategy,proto3,enum=operations_research.FirstSolutionStrategy_Value" json:"recreate_strategy,omitempty"`
	// Ratio in [0, 1] of non start/end nodes to consider as neighbors for the
	// identification of routes spatially close to a non start/end seed node.
	//
	// In particular, given a non start/end seed node s served by route r, we say
	// that a route r' is spatially close to the seed node s if there is at
	// least one non start/end node s' among the neighbors of s, such that s' is
	// served by r'.
	//
	// The neighbors_ratio is coupled with the corresponding min_neighbors and
	// max_neighbors values, defining the minimum and maximum number of neighbor
	// nodes considered for a given seed node:
	// num_neighbors = min(max_neighbors,
	//
	//	max(min_neighbors, neighbors_ratio * NUM_NON_START_END_NODES))
	//
	// Neighbors ratio, and minimum and maximum number of non start/end neighbor
	// nodes for the identification of spatially close routes.
	RouteSelectionNeighborsRatio *float64 `protobuf:"fixed64,4,opt,name=route_selection_neighbors_ratio,json=routeSelectionNeighborsRatio,proto3,oneof" json:"route_selection_neighbors_ratio,omitempty"`
	RouteSelectionMinNeighbors   *uint32  `protobuf:"varint,5,opt,name=route_selection_min_neighbors,json=routeSelectionMinNeighbors,proto3,oneof" json:"route_selection_min_neighbors,omitempty"`
	RouteSelectionMaxNeighbors   *uint32  `protobuf:"varint,6,opt,name=route_selection_max_neighbors,json=routeSelectionMaxNeighbors,proto3,oneof" json:"route_selection_max_neighbors,omitempty"`
}

func (x *RuinRecreateParameters) Reset() {
	*x = RuinRecreateParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuinRecreateParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinRecreateParameters) ProtoMessage() {}

func (x *RuinRecreateParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinRecreateParameters.ProtoReflect.Descriptor instead.
func (*RuinRecreateParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{5}
}

func (x *RuinRecreateParameters) GetRuinStrategies() []*RuinStrategy {
	if x != nil {
		return x.RuinStrategies
	}
	return nil
}

func (x *RuinRecreateParameters) GetRuinCompositionStrategy() RuinCompositionStrategy_Value {
	if x != nil {
		return x.RuinCompositionStrategy
	}
	return RuinCompositionStrategy_UNSET
}

func (x *RuinRecreateParameters) GetRecreateStrategy() FirstSolutionStrategy_Value {
	if x != nil {
		return x.RecreateStrategy
	}
	return FirstSolutionStrategy_UNSET
}

func (x *RuinRecreateParameters) GetRouteSelectionNeighborsRatio() float64 {
	if x != nil && x.RouteSelectionNeighborsRatio != nil {
		return *x.RouteSelectionNeighborsRatio
	}
	return 0
}

func (x *RuinRecreateParameters) GetRouteSelectionMinNeighbors() uint32 {
	if x != nil && x.RouteSelectionMinNeighbors != nil {
		return *x.RouteSelectionMinNeighbors
	}
	return 0
}

func (x *RuinRecreateParameters) GetRouteSelectionMaxNeighbors() uint32 {
	if x != nil && x.RouteSelectionMaxNeighbors != nil {
		return *x.RouteSelectionMaxNeighbors
	}
	return 0
}

// Defines how a reference solution is perturbed.
type PerturbationStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PerturbationStrategy) Reset() {
	*x = PerturbationStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerturbationStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerturbationStrategy) ProtoMessage() {}

func (x *PerturbationStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerturbationStrategy.ProtoReflect.Descriptor instead.
func (*PerturbationStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{6}
}

// The cooling schedule strategy defines how to compute the current simulated
// annealing temperature t given
// - the initial temperature t0
// - the final temperature t1
// - the current search progress 0 <= p <= 1
//
// The value of t0 and t1 is defined by the initial_temperature and
// final_temperature in SimulatedAnnealingParameters, respectively.
//
// The search progress p is derived, at any given time, by the search limits.
// In particular, p measures how far we are in the search process w.r.t. to the
// number of explored solutions and the time limit.
//
// The temperature t, computed according to one of the strategies defined below,
// together with the selected AcceptanceStrategy, is used to guide the search
// trajectory. In particular, given a neighbor solution S', generated by the
// the application of the perturbation and improvement step to a reference
// solution S, we have that S will be replaced by S' iff
//
//	cost(S') + t * log(U(0, 1)) < cost(S)
//
// where U(0, 1) is a random number sampled from a uniform distribution of real
// numbers in [0, 1].
type CoolingScheduleStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CoolingScheduleStrategy) Reset() {
	*x = CoolingScheduleStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoolingScheduleStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoolingScheduleStrategy) ProtoMessage() {}

func (x *CoolingScheduleStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoolingScheduleStrategy.ProtoReflect.Descriptor instead.
func (*CoolingScheduleStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{7}
}

// Specifies the behavior of a simulated annealing acceptance strategy.
type SimulatedAnnealingParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Determines the speed at which the temperature changes from initial to
	// final.
	CoolingScheduleStrategy CoolingScheduleStrategy_Value `protobuf:"varint,1,opt,name=cooling_schedule_strategy,json=coolingScheduleStrategy,proto3,enum=operations_research.CoolingScheduleStrategy_Value" json:"cooling_schedule_strategy,omitempty"`
	// The initial temperature. See CoolingScheduleStrategy for its usage.
	InitialTemperature *float64 `protobuf:"fixed64,2,opt,name=initial_temperature,json=initialTemperature,proto3,oneof" json:"initial_temperature,omitempty"`
	// The final temperature. See CoolingScheduleStrategy for its usage.
	FinalTemperature *float64 `protobuf:"fixed64,3,opt,name=final_temperature,json=finalTemperature,proto3,oneof" json:"final_temperature,omitempty"`
	// Automatically define the value for the temperatures as follows.
	// First, a  reference temperature t is defined as
	//
	//	w1 * c1 + w2 * c2 + ... + wK * cK
	//
	// where 0 < wJ <= 1 is the fraction of vehicles of cost class J and cJ is the
	// average arc cost for the cost class J.
	// The value of cJ is identified by randomly sampling N arc costs for the cost
	// class J, where N is equal to the number of instance nodes.
	// The initial and final temperatures are then defined as
	// - initial_temperature: 0.1 * t
	// - final_temperature: 0.001 * t
	AutomaticTemperatures *bool `protobuf:"varint,4,opt,name=automatic_temperatures,json=automaticTemperatures,proto3,oneof" json:"automatic_temperatures,omitempty"`
}

func (x *SimulatedAnnealingParameters) Reset() {
	*x = SimulatedAnnealingParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulatedAnnealingParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatedAnnealingParameters) ProtoMessage() {}

func (x *SimulatedAnnealingParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatedAnnealingParameters.ProtoReflect.Descriptor instead.
func (*SimulatedAnnealingParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{8}
}

func (x *SimulatedAnnealingParameters) GetCoolingScheduleStrategy() CoolingScheduleStrategy_Value {
	if x != nil {
		return x.CoolingScheduleStrategy
	}
	return CoolingScheduleStrategy_UNSET
}

func (x *SimulatedAnnealingParameters) GetInitialTemperature() float64 {
	if x != nil && x.InitialTemperature != nil {
		return *x.InitialTemperature
	}
	return 0
}

func (x *SimulatedAnnealingParameters) GetFinalTemperature() float64 {
	if x != nil && x.FinalTemperature != nil {
		return *x.FinalTemperature
	}
	return 0
}

func (x *SimulatedAnnealingParameters) GetAutomaticTemperatures() bool {
	if x != nil && x.AutomaticTemperatures != nil {
		return *x.AutomaticTemperatures
	}
	return false
}

// Determines when a neighbor solution, obtained by the application of a
// perturbation and improvement step to a reference solution, is used to
// replace the reference solution.
type AcceptanceStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptanceStrategy) Reset() {
	*x = AcceptanceStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptanceStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptanceStrategy) ProtoMessage() {}

func (x *AcceptanceStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptanceStrategy.ProtoReflect.Descriptor instead.
func (*AcceptanceStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{9}
}

// Specifies the behavior of a search based on ILS.
type IteratedLocalSearchParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Determines how a reference solution S is perturbed to obtain a neighbor
	// solution S'.
	PerturbationStrategy PerturbationStrategy_Value `protobuf:"varint,1,opt,name=perturbation_strategy,json=perturbationStrategy,proto3,enum=operations_research.PerturbationStrategy_Value" json:"perturbation_strategy,omitempty"`
	// Parameters to customize a ruin and recreate perturbation.
	RuinRecreateParameters *RuinRecreateParameters `protobuf:"bytes,2,opt,name=ruin_recreate_parameters,json=ruinRecreateParameters,proto3" json:"ruin_recreate_parameters,omitempty"`
	// Determines whether solution S', obtained from the perturbation, should be
	// optimized with a local search application.
	ImprovePerturbedSolution *bool `protobuf:"varint,3,opt,name=improve_perturbed_solution,json=improvePerturbedSolution,proto3,oneof" json:"improve_perturbed_solution,omitempty"`
	// Determines when the neighbor solution S', possibly improved if
	// `improve_perturbed_solution` is true, replaces the reference solution S.
	AcceptanceStrategy AcceptanceStrategy_Value `protobuf:"varint,4,opt,name=acceptance_strategy,json=acceptanceStrategy,proto3,enum=operations_research.AcceptanceStrategy_Value" json:"acceptance_strategy,omitempty"`
	// Parameters to customize a simulated annealing acceptance strategy. These
	// parameters are required iff the acceptance_strategy is SIMULATED_ANNEALING.
	SimulatedAnnealingParameters *SimulatedAnnealingParameters `protobuf:"bytes,5,opt,name=simulated_annealing_parameters,json=simulatedAnnealingParameters,proto3" json:"simulated_annealing_parameters,omitempty"`
}

func (x *IteratedLocalSearchParameters) Reset() {
	*x = IteratedLocalSearchParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IteratedLocalSearchParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IteratedLocalSearchParameters) ProtoMessage() {}

func (x *IteratedLocalSearchParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_ils_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IteratedLocalSearchParameters.ProtoReflect.Descriptor instead.
func (*IteratedLocalSearchParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP(), []int{10}
}

func (x *IteratedLocalSearchParameters) GetPerturbationStrategy() PerturbationStrategy_Value {
	if x != nil {
		return x.PerturbationStrategy
	}
	return PerturbationStrategy_UNSET
}

func (x *IteratedLocalSearchParameters) GetRuinRecreateParameters() *RuinRecreateParameters {
	if x != nil {
		return x.RuinRecreateParameters
	}
	return nil
}

func (x *IteratedLocalSearchParameters) GetImprovePerturbedSolution() bool {
	if x != nil && x.ImprovePerturbedSolution != nil {
		return *x.ImprovePerturbedSolution
	}
	return false
}

func (x *IteratedLocalSearchParameters) GetAcceptanceStrategy() AcceptanceStrategy_Value {
	if x != nil {
		return x.AcceptanceStrategy
	}
	return AcceptanceStrategy_UNSET
}

func (x *IteratedLocalSearchParameters) GetSimulatedAnnealingParameters() *SimulatedAnnealingParameters {
	if x != nil {
		return x.SimulatedAnnealingParameters
	}
	return nil
}

var File_ortools_constraint_solver_routing_ils_proto protoreflect.FileDescriptor

var file_ortools_constraint_solver_routing_ils_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6f, 0x72, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x1a, 0x2d, 0x6f, 0x72, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x69, 0x0a, 0x20, 0x53, 0x70, 0x61, 0x74, 0x69, 0x61, 0x6c, 0x6c, 0x79, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x75, 0x69, 0x6e, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x2f, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x75, 0x69,
	0x6e, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x00, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x52, 0x75, 0x69, 0x6e, 0x65, 0x64, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x88, 0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x72,
	0x75, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x16,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x75, 0x69, 0x6e, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x31, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64,
	0x56, 0x69, 0x73, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x6e, 0x75,
	0x6d, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x73,
	0x22, 0x81, 0x02, 0x0a, 0x10, 0x53, 0x49, 0x53, 0x52, 0x52, 0x75, 0x69, 0x6e, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x3e, 0x0a, 0x19, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x16, 0x6d, 0x61, 0x78, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a, 0x16, 0x61, 0x76, 0x67, 0x5f, 0x6e, 0x75, 0x6d,
	0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x13, 0x61, 0x76, 0x67, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x28, 0x0a, 0x0d, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x0c, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73,
	0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x1c, 0x0a, 0x1a, 0x5f, 0x6d, 0x61,
	0x78, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x19, 0x0a, 0x17, 0x5f, 0x61, 0x76, 0x67, 0x5f,
	0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x73, 0x69,
	0x74, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x96, 0x02, 0x0a, 0x0c, 0x52, 0x75, 0x69, 0x6e, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x6d, 0x0a, 0x16, 0x73, 0x70, 0x61, 0x74, 0x69, 0x61, 0x6c,
	0x6c, 0x79, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x53, 0x70, 0x61, 0x74,
	0x69, 0x61, 0x6c, 0x6c, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x52, 0x75, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x48, 0x00, 0x52, 0x14,
	0x73, 0x70, 0x61, 0x74, 0x69, 0x61, 0x6c, 0x6c, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x12, 0x4e, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x77,
	0x61, 0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x75, 0x69, 0x6e, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x57, 0x61, 0x6c, 0x6b, 0x12, 0x3b, 0x0a, 0x04, 0x73, 0x69, 0x73, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x53, 0x49, 0x53, 0x52, 0x52, 0x75, 0x69,
	0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x48, 0x00, 0x52, 0x04, 0x73, 0x69, 0x73,
	0x72, 0x42, 0x0a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x73, 0x0a,
	0x17, 0x52, 0x75, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x58, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x52, 0x55, 0x4e, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x53, 0x45, 0x51, 0x55, 0x45, 0x4e, 0x54, 0x49,
	0x41, 0x4c, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x55, 0x4e, 0x5f, 0x41, 0x4c,
	0x4c, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x55, 0x4e, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x4c, 0x59,
	0x10, 0x03, 0x22, 0xf7, 0x04, 0x0a, 0x16, 0x52, 0x75, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x4a, 0x0a,
	0x0f, 0x72, 0x75, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x52, 0x75, 0x69,
	0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x0e, 0x72, 0x75, 0x69, 0x6e, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65, 0x73, 0x12, 0x6e, 0x0a, 0x19, 0x72, 0x75, 0x69,
	0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2e, 0x52, 0x75, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x17, 0x72, 0x75, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x5d, 0x0a, 0x11, 0x72, 0x65, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x10, 0x72, 0x65, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x4a, 0x0a, 0x1f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x48, 0x00, 0x52, 0x1c, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x88, 0x01, 0x01, 0x12, 0x46, 0x0a, 0x1d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x6e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x1a, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x88, 0x01, 0x01, 0x12, 0x46, 0x0a, 0x1d,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x1a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x78, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x73, 0x88, 0x01, 0x01, 0x42, 0x22, 0x0a, 0x20, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x72, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x42, 0x20, 0x0a, 0x1e, 0x5f, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e,
	0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x42, 0x20, 0x0a, 0x1e, 0x5f, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x61, 0x78, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x22, 0x41, 0x0a, 0x14,
	0x50, 0x65, 0x72, 0x74, 0x75, 0x72, 0x62, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x22, 0x29, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x55, 0x49, 0x4e,
	0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x22,
	0x4a, 0x0a, 0x17, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x2f, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x45, 0x58, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x52, 0x10, 0x02, 0x22, 0xfb, 0x02, 0x0a, 0x1c,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x6e, 0x65, 0x61, 0x6c, 0x69,
	0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x6e, 0x0a, 0x19,
	0x63, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x32, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x17, 0x63, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x34, 0x0a, 0x13,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x12, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x30, 0x0a, 0x11, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52,
	0x10, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x16, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69,
	0x63, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x15, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69,
	0x63, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x88, 0x01, 0x01,
	0x42, 0x16, 0x0a, 0x14, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x19,
	0x0a, 0x17, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x12, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22,
	0x3f, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45,
	0x54, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x52, 0x45, 0x45, 0x44, 0x59, 0x5f, 0x44, 0x45,
	0x53, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x49, 0x4d, 0x55, 0x4c,
	0x41, 0x54, 0x45, 0x44, 0x5f, 0x41, 0x4e, 0x4e, 0x45, 0x41, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x22, 0xa7, 0x04, 0x0a, 0x1d, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x64, 0x0a, 0x15, 0x70, 0x65, 0x72, 0x74, 0x75, 0x72, 0x62, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2f, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x50, 0x65, 0x72, 0x74, 0x75, 0x72, 0x62, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x14, 0x70, 0x65, 0x72, 0x74, 0x75, 0x72, 0x62, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x65, 0x0a, 0x18, 0x72, 0x75, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2e, 0x52, 0x75, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x16, 0x72, 0x75, 0x69, 0x6e, 0x52, 0x65, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x41, 0x0a, 0x1a, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x74, 0x75,
	0x72, 0x62, 0x65, 0x64, 0x5f, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x18, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x50, 0x65,
	0x72, 0x74, 0x75, 0x72, 0x62, 0x65, 0x64, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x5e, 0x0a, 0x13, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2d, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x12,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x12, 0x77, 0x0a, 0x1e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x6e, 0x6e, 0x65, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x6e, 0x65, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x1c, 0x73,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x6e, 0x65, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x42, 0x1d, 0x0a, 0x1b, 0x5f,
	0x69, 0x6d, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x74, 0x75, 0x72, 0x62, 0x65,
	0x64, 0x5f, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x8f, 0x01, 0x0a, 0x23, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x6f, 0x72, 0x74, 0x6f, 0x6f, 0x6c,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x50, 0x01, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x69, 0x72, 0x73, 0x70, 0x61, 0x63, 0x65, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c,
	0x6f, 0x67, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x67,
	0x6f, 0x2f, 0x6f, 0x72, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0xaa, 0x02, 0x1f, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x4f, 0x72, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ortools_constraint_solver_routing_ils_proto_rawDescOnce sync.Once
	file_ortools_constraint_solver_routing_ils_proto_rawDescData = file_ortools_constraint_solver_routing_ils_proto_rawDesc
)

func file_ortools_constraint_solver_routing_ils_proto_rawDescGZIP() []byte {
	file_ortools_constraint_solver_routing_ils_proto_rawDescOnce.Do(func() {
		file_ortools_constraint_solver_routing_ils_proto_rawDescData = protoimpl.X.CompressGZIP(file_ortools_constraint_solver_routing_ils_proto_rawDescData)
	})
	return file_ortools_constraint_solver_routing_ils_proto_rawDescData
}

var file_ortools_constraint_solver_routing_ils_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ortools_constraint_solver_routing_ils_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ortools_constraint_solver_routing_ils_proto_goTypes = []interface{}{
	(RuinCompositionStrategy_Value)(0),       // 0: operations_research.RuinCompositionStrategy.Value
	(PerturbationStrategy_Value)(0),          // 1: operations_research.PerturbationStrategy.Value
	(CoolingScheduleStrategy_Value)(0),       // 2: operations_research.CoolingScheduleStrategy.Value
	(AcceptanceStrategy_Value)(0),            // 3: operations_research.AcceptanceStrategy.Value
	(*SpatiallyCloseRoutesRuinStrategy)(nil), // 4: operations_research.SpatiallyCloseRoutesRuinStrategy
	(*RandomWalkRuinStrategy)(nil),           // 5: operations_research.RandomWalkRuinStrategy
	(*SISRRuinStrategy)(nil),                 // 6: operations_research.SISRRuinStrategy
	(*RuinStrategy)(nil),                     // 7: operations_research.RuinStrategy
	(*RuinCompositionStrategy)(nil),          // 8: operations_research.RuinCompositionStrategy
	(*RuinRecreateParameters)(nil),           // 9: operations_research.RuinRecreateParameters
	(*PerturbationStrategy)(nil),             // 10: operations_research.PerturbationStrategy
	(*CoolingScheduleStrategy)(nil),          // 11: operations_research.CoolingScheduleStrategy
	(*SimulatedAnnealingParameters)(nil),     // 12: operations_research.SimulatedAnnealingParameters
	(*AcceptanceStrategy)(nil),               // 13: operations_research.AcceptanceStrategy
	(*IteratedLocalSearchParameters)(nil),    // 14: operations_research.IteratedLocalSearchParameters
	(FirstSolutionStrategy_Value)(0),         // 15: operations_research.FirstSolutionStrategy.Value
}
var file_ortools_constraint_solver_routing_ils_proto_depIdxs = []int32{
	4,  // 0: operations_research.RuinStrategy.spatially_close_routes:type_name -> operations_research.SpatiallyCloseRoutesRuinStrategy
	5,  // 1: operations_research.RuinStrategy.random_walk:type_name -> operations_research.RandomWalkRuinStrategy
	6,  // 2: operations_research.RuinStrategy.sisr:type_name -> operations_research.SISRRuinStrategy
	7,  // 3: operations_research.RuinRecreateParameters.ruin_strategies:type_name -> operations_research.RuinStrategy
	0,  // 4: operations_research.RuinRecreateParameters.ruin_composition_strategy:type_name -> operations_research.RuinCompositionStrategy.Value
	15, // 5: operations_research.RuinRecreateParameters.recreate_strategy:type_name -> operations_research.FirstSolutionStrategy.Value
	2,  // 6: operations_research.SimulatedAnnealingParameters.cooling_schedule_strategy:type_name -> operations_research.CoolingScheduleStrategy.Value
	1,  // 7: operations_research.IteratedLocalSearchParameters.perturbation_strategy:type_name -> operations_research.PerturbationStrategy.Value
	9,  // 8: operations_research.IteratedLocalSearchParameters.ruin_recreate_parameters:type_name -> operations_research.RuinRecreateParameters
	3,  // 9: operations_research.IteratedLocalSearchParameters.acceptance_strategy:type_name -> operations_research.AcceptanceStrategy.Value
	12, // 10: operations_research.IteratedLocalSearchParameters.simulated_annealing_parameters:type_name -> operations_research.SimulatedAnnealingParameters
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ortools_constraint_solver_routing_ils_proto_init() }
func file_ortools_constraint_solver_routing_ils_proto_init() {
	if File_ortools_constraint_solver_routing_ils_proto != nil {
		return
	}
	file_ortools_constraint_solver_routing_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpatiallyCloseRoutesRuinStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomWalkRuinStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SISRRuinStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuinStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuinCompositionStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuinRecreateParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerturbationStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoolingScheduleStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulatedAnnealingParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptanceStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ortools_constraint_solver_routing_ils_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IteratedLocalSearchParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*RuinStrategy_SpatiallyCloseRoutes)(nil),
		(*RuinStrategy_RandomWalk)(nil),
		(*RuinStrategy_Sisr)(nil),
	}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_ortools_constraint_solver_routing_ils_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ortools_constraint_solver_routing_ils_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_constraint_solver_routing_ils_proto_goTypes,
		DependencyIndexes: file_ortools_constraint_solver_routing_ils_proto_depIdxs,
		EnumInfos:         file_ortools_constraint_solver_routing_ils_proto_enumTypes,
		MessageInfos:      file_ortools_constraint_solver_routing_ils_proto_msgTypes,
	}.Build()
	File_ortools_constraint_solver_routing_ils_proto = out.File
	file_ortools_constraint_solver_routing_ils_proto_rawDesc = nil
	file_ortools_constraint_solver_routing_ils_proto_goTypes = nil
	file_ortools_constraint_solver_routing_ils_proto_depIdxs = nil
}
