// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Enums used to define routing parameters.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ortools/constraint_solver/routing_enums.proto

package constraintsolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FirstSolutionStrategy_Value int32

const (
	// See the homonymous value in LocalSearchMetaheuristic.
	FirstSolutionStrategy_UNSET FirstSolutionStrategy_Value = 0
	// Lets the solver detect which strategy to use according to the model being
	// solved.
	FirstSolutionStrategy_AUTOMATIC FirstSolutionStrategy_Value = 15
	// --- Path addition heuristics ---
	// Starting from a route "start" node, connect it to the node which produces
	// the cheapest route segment, then extend the route by iterating on the
	// last node added to the route.
	FirstSolutionStrategy_PATH_CHEAPEST_ARC FirstSolutionStrategy_Value = 3
	// Same as PATH_CHEAPEST_ARC, but arcs are evaluated with a comparison-based
	// selector which will favor the most constrained arc first. To assign a
	// selector to the routing model, see
	// RoutingModel::ArcIsMoreConstrainedThanArc() in routing.h for details.
	FirstSolutionStrategy_PATH_MOST_CONSTRAINED_ARC FirstSolutionStrategy_Value = 4
	// Same as PATH_CHEAPEST_ARC, except that arc costs are evaluated using the
	// function passed to RoutingModel::SetFirstSolutionEvaluator()
	// (cf. routing.h).
	FirstSolutionStrategy_EVALUATOR_STRATEGY FirstSolutionStrategy_Value = 5
	// Savings algorithm (Clarke & Wright).
	// Reference: Clarke, G. & Wright, J.W.:
	// "Scheduling of Vehicles from a Central Depot to a Number of Delivery
	// Points", Operations Research, Vol. 12, 1964, pp. 568-581
	FirstSolutionStrategy_SAVINGS FirstSolutionStrategy_Value = 10
	// Parallel version of the Savings algorithm.
	// Instead of extending a single route until it is no longer possible,
	// the parallel version iteratively considers the next most improving
	// feasible saving and possibly builds several routes in parallel.
	FirstSolutionStrategy_PARALLEL_SAVINGS FirstSolutionStrategy_Value = 17
	// Sweep algorithm (Wren & Holliday).
	// Reference: Anthony Wren & Alan Holliday: Computer Scheduling of Vehicles
	// from One or More Depots to a Number of Delivery Points Operational
	// Research Quarterly (1970-1977),
	// Vol. 23, No. 3 (Sep., 1972), pp. 333-344
	FirstSolutionStrategy_SWEEP FirstSolutionStrategy_Value = 11
	// Christofides algorithm (actually a variant of the Christofides algorithm
	// using a maximal matching instead of a maximum matching, which does
	// not guarantee the 3/2 factor of the approximation on a metric travelling
	// salesman). Works on generic vehicle routing models by extending a route
	// until no nodes can be inserted on it.
	// Reference: Nicos Christofides, Worst-case analysis of a new heuristic for
	// the travelling salesman problem, Report 388, Graduate School of
	// Industrial Administration, CMU, 1976.
	FirstSolutionStrategy_CHRISTOFIDES FirstSolutionStrategy_Value = 13
	// --- Path insertion heuristics ---
	// Make all nodes inactive. Only finds a solution if nodes are optional (are
	// element of a disjunction constraint with a finite penalty cost).
	FirstSolutionStrategy_ALL_UNPERFORMED FirstSolutionStrategy_Value = 6
	// Iteratively build a solution by inserting the cheapest node at its
	// cheapest position; the cost of insertion is based on the global cost
	// function of the routing model. As of 2/2012, only works on models with
	// optional nodes (with finite penalty costs).
	FirstSolutionStrategy_BEST_INSERTION FirstSolutionStrategy_Value = 7
	// Iteratively build a solution by inserting the cheapest node at its
	// cheapest position; the cost of insertion is based on the arc cost
	// function. Is faster than BEST_INSERTION.
	FirstSolutionStrategy_PARALLEL_CHEAPEST_INSERTION FirstSolutionStrategy_Value = 8
	// Iteratively build a solution by constructing routes sequentially, for
	// each route inserting the cheapest node at its cheapest position until the
	// route is completed; the cost of insertion is based on the arc cost
	// function. Is faster than PARALLEL_CHEAPEST_INSERTION.
	FirstSolutionStrategy_SEQUENTIAL_CHEAPEST_INSERTION FirstSolutionStrategy_Value = 14
	// Iteratively build a solution by inserting each node at its cheapest
	// position; the cost of insertion is based on the arc cost function.
	// Differs from PARALLEL_CHEAPEST_INSERTION by the node selected for
	// insertion; here nodes are considered in decreasing order of distance to
	// the start/ends of the routes, i.e. farthest nodes are inserted first.
	// Is faster than SEQUENTIAL_CHEAPEST_INSERTION.
	FirstSolutionStrategy_LOCAL_CHEAPEST_INSERTION FirstSolutionStrategy_Value = 9
	// Same as LOCAL_CHEAPEST_INSERTION except that the cost of insertion is
	// based on the routing model cost function instead of arc costs only.
	FirstSolutionStrategy_LOCAL_CHEAPEST_COST_INSERTION FirstSolutionStrategy_Value = 16
	// --- Variable-based heuristics ---
	// Iteratively connect two nodes which produce the cheapest route segment.
	FirstSolutionStrategy_GLOBAL_CHEAPEST_ARC FirstSolutionStrategy_Value = 1
	// Select the first node with an unbound successor and connect it to the
	// node which produces the cheapest route segment.
	FirstSolutionStrategy_LOCAL_CHEAPEST_ARC FirstSolutionStrategy_Value = 2
	// Select the first node with an unbound successor and connect it to the
	// first available node.
	// This is equivalent to the CHOOSE_FIRST_UNBOUND strategy combined with
	// ASSIGN_MIN_VALUE (cf. constraint_solver.h).
	FirstSolutionStrategy_FIRST_UNBOUND_MIN_VALUE FirstSolutionStrategy_Value = 12
)

// Enum value maps for FirstSolutionStrategy_Value.
var (
	FirstSolutionStrategy_Value_name = map[int32]string{
		0:  "UNSET",
		15: "AUTOMATIC",
		3:  "PATH_CHEAPEST_ARC",
		4:  "PATH_MOST_CONSTRAINED_ARC",
		5:  "EVALUATOR_STRATEGY",
		10: "SAVINGS",
		17: "PARALLEL_SAVINGS",
		11: "SWEEP",
		13: "CHRISTOFIDES",
		6:  "ALL_UNPERFORMED",
		7:  "BEST_INSERTION",
		8:  "PARALLEL_CHEAPEST_INSERTION",
		14: "SEQUENTIAL_CHEAPEST_INSERTION",
		9:  "LOCAL_CHEAPEST_INSERTION",
		16: "LOCAL_CHEAPEST_COST_INSERTION",
		1:  "GLOBAL_CHEAPEST_ARC",
		2:  "LOCAL_CHEAPEST_ARC",
		12: "FIRST_UNBOUND_MIN_VALUE",
	}
	FirstSolutionStrategy_Value_value = map[string]int32{
		"UNSET":                         0,
		"AUTOMATIC":                     15,
		"PATH_CHEAPEST_ARC":             3,
		"PATH_MOST_CONSTRAINED_ARC":     4,
		"EVALUATOR_STRATEGY":            5,
		"SAVINGS":                       10,
		"PARALLEL_SAVINGS":              17,
		"SWEEP":                         11,
		"CHRISTOFIDES":                  13,
		"ALL_UNPERFORMED":               6,
		"BEST_INSERTION":                7,
		"PARALLEL_CHEAPEST_INSERTION":   8,
		"SEQUENTIAL_CHEAPEST_INSERTION": 14,
		"LOCAL_CHEAPEST_INSERTION":      9,
		"LOCAL_CHEAPEST_COST_INSERTION": 16,
		"GLOBAL_CHEAPEST_ARC":           1,
		"LOCAL_CHEAPEST_ARC":            2,
		"FIRST_UNBOUND_MIN_VALUE":       12,
	}
)

func (x FirstSolutionStrategy_Value) Enum() *FirstSolutionStrategy_Value {
	p := new(FirstSolutionStrategy_Value)
	*p = x
	return p
}

func (x FirstSolutionStrategy_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirstSolutionStrategy_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_enums_proto_enumTypes[0].Descriptor()
}

func (FirstSolutionStrategy_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_enums_proto_enumTypes[0]
}

func (x FirstSolutionStrategy_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirstSolutionStrategy_Value.Descriptor instead.
func (FirstSolutionStrategy_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP(), []int{0, 0}
}

type LocalSearchMetaheuristic_Value int32

const (
	// Means "not set". If the solver sees that, it'll behave like for
	// AUTOMATIC. But this value won't override others upon a proto MergeFrom(),
	// whereas "AUTOMATIC" will.
	LocalSearchMetaheuristic_UNSET LocalSearchMetaheuristic_Value = 0
	// Lets the solver select the metaheuristic.
	LocalSearchMetaheuristic_AUTOMATIC LocalSearchMetaheuristic_Value = 6
	// Accepts improving (cost-reducing) local search neighbors until a local
	// minimum is reached.
	LocalSearchMetaheuristic_GREEDY_DESCENT LocalSearchMetaheuristic_Value = 1
	// Uses guided local search to escape local minima
	// (cf. http://en.wikipedia.org/wiki/Guided_Local_Search); this is generally
	// the most efficient metaheuristic for vehicle routing.
	LocalSearchMetaheuristic_GUIDED_LOCAL_SEARCH LocalSearchMetaheuristic_Value = 2
	// Uses simulated annealing to escape local minima
	// (cf. http://en.wikipedia.org/wiki/Simulated_annealing).
	LocalSearchMetaheuristic_SIMULATED_ANNEALING LocalSearchMetaheuristic_Value = 3
	// Uses tabu search to escape local minima
	// (cf. http://en.wikipedia.org/wiki/Tabu_search).
	LocalSearchMetaheuristic_TABU_SEARCH LocalSearchMetaheuristic_Value = 4
	// Uses tabu search on a list of variables to escape local minima. The list
	// of variables to use must be provided via the SetTabuVarsCallback
	// callback.
	LocalSearchMetaheuristic_GENERIC_TABU_SEARCH LocalSearchMetaheuristic_Value = 5
)

// Enum value maps for LocalSearchMetaheuristic_Value.
var (
	LocalSearchMetaheuristic_Value_name = map[int32]string{
		0: "UNSET",
		6: "AUTOMATIC",
		1: "GREEDY_DESCENT",
		2: "GUIDED_LOCAL_SEARCH",
		3: "SIMULATED_ANNEALING",
		4: "TABU_SEARCH",
		5: "GENERIC_TABU_SEARCH",
	}
	LocalSearchMetaheuristic_Value_value = map[string]int32{
		"UNSET":               0,
		"AUTOMATIC":           6,
		"GREEDY_DESCENT":      1,
		"GUIDED_LOCAL_SEARCH": 2,
		"SIMULATED_ANNEALING": 3,
		"TABU_SEARCH":         4,
		"GENERIC_TABU_SEARCH": 5,
	}
)

func (x LocalSearchMetaheuristic_Value) Enum() *LocalSearchMetaheuristic_Value {
	p := new(LocalSearchMetaheuristic_Value)
	*p = x
	return p
}

func (x LocalSearchMetaheuristic_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalSearchMetaheuristic_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_enums_proto_enumTypes[1].Descriptor()
}

func (LocalSearchMetaheuristic_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_enums_proto_enumTypes[1]
}

func (x LocalSearchMetaheuristic_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalSearchMetaheuristic_Value.Descriptor instead.
func (LocalSearchMetaheuristic_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP(), []int{1, 0}
}

type RoutingSearchStatus_Value int32

const (
	// Problem not solved yet (before calling RoutingModel::Solve()).
	RoutingSearchStatus_ROUTING_NOT_SOLVED RoutingSearchStatus_Value = 0
	// Problem solved successfully after calling RoutingModel::Solve().
	RoutingSearchStatus_ROUTING_SUCCESS RoutingSearchStatus_Value = 1
	// Problem solved successfully after calling RoutingModel::Solve(), except
	// that a local optimum has not been reached. Leaving more time would allow
	// improving the solution.
	RoutingSearchStatus_ROUTING_PARTIAL_SUCCESS_LOCAL_OPTIMUM_NOT_REACHED RoutingSearchStatus_Value = 2
	// No solution found to the problem after calling RoutingModel::Solve().
	RoutingSearchStatus_ROUTING_FAIL RoutingSearchStatus_Value = 3
	// Time limit reached before finding a solution with RoutingModel::Solve().
	RoutingSearchStatus_ROUTING_FAIL_TIMEOUT RoutingSearchStatus_Value = 4
	// Model, model parameters or flags are not valid.
	RoutingSearchStatus_ROUTING_INVALID RoutingSearchStatus_Value = 5
	// Problem proven to be infeasible.
	RoutingSearchStatus_ROUTING_INFEASIBLE RoutingSearchStatus_Value = 6
	// Problem has been solved to optimality.
	RoutingSearchStatus_ROUTING_OPTIMAL RoutingSearchStatus_Value = 7
)

// Enum value maps for RoutingSearchStatus_Value.
var (
	RoutingSearchStatus_Value_name = map[int32]string{
		0: "ROUTING_NOT_SOLVED",
		1: "ROUTING_SUCCESS",
		2: "ROUTING_PARTIAL_SUCCESS_LOCAL_OPTIMUM_NOT_REACHED",
		3: "ROUTING_FAIL",
		4: "ROUTING_FAIL_TIMEOUT",
		5: "ROUTING_INVALID",
		6: "ROUTING_INFEASIBLE",
		7: "ROUTING_OPTIMAL",
	}
	RoutingSearchStatus_Value_value = map[string]int32{
		"ROUTING_NOT_SOLVED": 0,
		"ROUTING_SUCCESS":    1,
		"ROUTING_PARTIAL_SUCCESS_LOCAL_OPTIMUM_NOT_REACHED": 2,
		"ROUTING_FAIL":         3,
		"ROUTING_FAIL_TIMEOUT": 4,
		"ROUTING_INVALID":      5,
		"ROUTING_INFEASIBLE":   6,
		"ROUTING_OPTIMAL":      7,
	}
)

func (x RoutingSearchStatus_Value) Enum() *RoutingSearchStatus_Value {
	p := new(RoutingSearchStatus_Value)
	*p = x
	return p
}

func (x RoutingSearchStatus_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingSearchStatus_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_enums_proto_enumTypes[2].Descriptor()
}

func (RoutingSearchStatus_Value) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_enums_proto_enumTypes[2]
}

func (x RoutingSearchStatus_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingSearchStatus_Value.Descriptor instead.
func (RoutingSearchStatus_Value) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP(), []int{2, 0}
}

// First solution strategies, used as starting point of local search.
type FirstSolutionStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirstSolutionStrategy) Reset() {
	*x = FirstSolutionStrategy{}
	mi := &file_ortools_constraint_solver_routing_enums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstSolutionStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstSolutionStrategy) ProtoMessage() {}

func (x *FirstSolutionStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_enums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstSolutionStrategy.ProtoReflect.Descriptor instead.
func (*FirstSolutionStrategy) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP(), []int{0}
}

// Local search metaheuristics used to guide the search. Apart from greedy
// descent, they will try to escape local minima.
type LocalSearchMetaheuristic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalSearchMetaheuristic) Reset() {
	*x = LocalSearchMetaheuristic{}
	mi := &file_ortools_constraint_solver_routing_enums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSearchMetaheuristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSearchMetaheuristic) ProtoMessage() {}

func (x *LocalSearchMetaheuristic) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_enums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSearchMetaheuristic.ProtoReflect.Descriptor instead.
func (*LocalSearchMetaheuristic) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP(), []int{1}
}

// Used by `RoutingModel` to report the status of the search for a solution.
type RoutingSearchStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingSearchStatus) Reset() {
	*x = RoutingSearchStatus{}
	mi := &file_ortools_constraint_solver_routing_enums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSearchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSearchStatus) ProtoMessage() {}

func (x *RoutingSearchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_enums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSearchStatus.ProtoReflect.Descriptor instead.
func (*RoutingSearchStatus) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP(), []int{2}
}

var File_ortools_constraint_solver_routing_enums_proto protoreflect.FileDescriptor

const file_ortools_constraint_solver_routing_enums_proto_rawDesc = "" +
	"\n" +
	"-ortools/constraint_solver/routing_enums.proto\x12\x13operations_research\"\xc5\x03\n" +
	"\x15FirstSolutionStrategy\"\xab\x03\n" +
	"\x05Value\x12\t\n" +
	"\x05UNSET\x10\x00\x12\r\n" +
	"\tAUTOMATIC\x10\x0f\x12\x15\n" +
	"\x11PATH_CHEAPEST_ARC\x10\x03\x12\x1d\n" +
	"\x19PATH_MOST_CONSTRAINED_ARC\x10\x04\x12\x16\n" +
	"\x12EVALUATOR_STRATEGY\x10\x05\x12\v\n" +
	"\aSAVINGS\x10\n" +
	"\x12\x14\n" +
	"\x10PARALLEL_SAVINGS\x10\x11\x12\t\n" +
	"\x05SWEEP\x10\v\x12\x10\n" +
	"\fCHRISTOFIDES\x10\r\x12\x13\n" +
	"\x0fALL_UNPERFORMED\x10\x06\x12\x12\n" +
	"\x0eBEST_INSERTION\x10\a\x12\x1f\n" +
	"\x1bPARALLEL_CHEAPEST_INSERTION\x10\b\x12!\n" +
	"\x1dSEQUENTIAL_CHEAPEST_INSERTION\x10\x0e\x12\x1c\n" +
	"\x18LOCAL_CHEAPEST_INSERTION\x10\t\x12!\n" +
	"\x1dLOCAL_CHEAPEST_COST_INSERTION\x10\x10\x12\x17\n" +
	"\x13GLOBAL_CHEAPEST_ARC\x10\x01\x12\x16\n" +
	"\x12LOCAL_CHEAPEST_ARC\x10\x02\x12\x1b\n" +
	"\x17FIRST_UNBOUND_MIN_VALUE\x10\f\"\xae\x01\n" +
	"\x18LocalSearchMetaheuristic\"\x91\x01\n" +
	"\x05Value\x12\t\n" +
	"\x05UNSET\x10\x00\x12\r\n" +
	"\tAUTOMATIC\x10\x06\x12\x12\n" +
	"\x0eGREEDY_DESCENT\x10\x01\x12\x17\n" +
	"\x13GUIDED_LOCAL_SEARCH\x10\x02\x12\x17\n" +
	"\x13SIMULATED_ANNEALING\x10\x03\x12\x0f\n" +
	"\vTABU_SEARCH\x10\x04\x12\x17\n" +
	"\x13GENERIC_TABU_SEARCH\x10\x05\"\xf1\x01\n" +
	"\x13RoutingSearchStatus\"\xd9\x01\n" +
	"\x05Value\x12\x16\n" +
	"\x12ROUTING_NOT_SOLVED\x10\x00\x12\x13\n" +
	"\x0fROUTING_SUCCESS\x10\x01\x125\n" +
	"1ROUTING_PARTIAL_SUCCESS_LOCAL_OPTIMUM_NOT_REACHED\x10\x02\x12\x10\n" +
	"\fROUTING_FAIL\x10\x03\x12\x18\n" +
	"\x14ROUTING_FAIL_TIMEOUT\x10\x04\x12\x13\n" +
	"\x0fROUTING_INVALID\x10\x05\x12\x16\n" +
	"\x12ROUTING_INFEASIBLE\x10\x06\x12\x13\n" +
	"\x0fROUTING_OPTIMAL\x10\aB\x8f\x01\n" +
	"#com.google.ortools.constraintsolverP\x01ZDgithub.com/airspacetechnologies/or-tools/go/ortools/constraintsolver\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3"

var (
	file_ortools_constraint_solver_routing_enums_proto_rawDescOnce sync.Once
	file_ortools_constraint_solver_routing_enums_proto_rawDescData []byte
)

func file_ortools_constraint_solver_routing_enums_proto_rawDescGZIP() []byte {
	file_ortools_constraint_solver_routing_enums_proto_rawDescOnce.Do(func() {
		file_ortools_constraint_solver_routing_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_enums_proto_rawDesc), len(file_ortools_constraint_solver_routing_enums_proto_rawDesc)))
	})
	return file_ortools_constraint_solver_routing_enums_proto_rawDescData
}

var file_ortools_constraint_solver_routing_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ortools_constraint_solver_routing_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ortools_constraint_solver_routing_enums_proto_goTypes = []any{
	(FirstSolutionStrategy_Value)(0),    // 0: operations_research.FirstSolutionStrategy.Value
	(LocalSearchMetaheuristic_Value)(0), // 1: operations_research.LocalSearchMetaheuristic.Value
	(RoutingSearchStatus_Value)(0),      // 2: operations_research.RoutingSearchStatus.Value
	(*FirstSolutionStrategy)(nil),       // 3: operations_research.FirstSolutionStrategy
	(*LocalSearchMetaheuristic)(nil),    // 4: operations_research.LocalSearchMetaheuristic
	(*RoutingSearchStatus)(nil),         // 5: operations_research.RoutingSearchStatus
}
var file_ortools_constraint_solver_routing_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ortools_constraint_solver_routing_enums_proto_init() }
func file_ortools_constraint_solver_routing_enums_proto_init() {
	if File_ortools_constraint_solver_routing_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_enums_proto_rawDesc), len(file_ortools_constraint_solver_routing_enums_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_constraint_solver_routing_enums_proto_goTypes,
		DependencyIndexes: file_ortools_constraint_solver_routing_enums_proto_depIdxs,
		EnumInfos:         file_ortools_constraint_solver_routing_enums_proto_enumTypes,
		MessageInfos:      file_ortools_constraint_solver_routing_enums_proto_msgTypes,
	}.Build()
	File_ortools_constraint_solver_routing_enums_proto = out.File
	file_ortools_constraint_solver_routing_enums_proto_goTypes = nil
	file_ortools_constraint_solver_routing_enums_proto_depIdxs = nil
}
