// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer used to parametrize the local cheapest insertion heuristics.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ortools/constraint_solver/routing_heuristic_parameters.proto

package constraintsolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// In insertion-based heuristics, describes what positions must be considered
// when inserting a pickup/delivery pair, and in what order they are
// considered.
type LocalCheapestInsertionParameters_PairInsertionStrategy int32

const (
	// Let the solver decide the set of positions and its ordering.
	LocalCheapestInsertionParameters_AUTOMATIC LocalCheapestInsertionParameters_PairInsertionStrategy = 0
	// Consider all positions, by increasing (cost(pickup), cost(delivery)).
	LocalCheapestInsertionParameters_BEST_PICKUP_THEN_BEST_DELIVERY LocalCheapestInsertionParameters_PairInsertionStrategy = 1
	// Consider all positions, by increasing by cost(pickup) + cost(delivery).
	LocalCheapestInsertionParameters_BEST_PICKUP_DELIVERY_PAIR LocalCheapestInsertionParameters_PairInsertionStrategy = 2
	// Only consider insertion positions that are compatible with the multitour
	// property, meaning a series of pickups may only start when the vehicle
	// is not carrying any delivery. This setting is designed to explore much
	// less possibilities than the full BEST_PICKUP_DELIVERY_PAIR.
	// Order by increasing by cost(pickup) + cost(delivery).
	LocalCheapestInsertionParameters_BEST_PICKUP_DELIVERY_PAIR_MULTITOUR LocalCheapestInsertionParameters_PairInsertionStrategy = 3
)

// Enum value maps for LocalCheapestInsertionParameters_PairInsertionStrategy.
var (
	LocalCheapestInsertionParameters_PairInsertionStrategy_name = map[int32]string{
		0: "AUTOMATIC",
		1: "BEST_PICKUP_THEN_BEST_DELIVERY",
		2: "BEST_PICKUP_DELIVERY_PAIR",
		3: "BEST_PICKUP_DELIVERY_PAIR_MULTITOUR",
	}
	LocalCheapestInsertionParameters_PairInsertionStrategy_value = map[string]int32{
		"AUTOMATIC":                           0,
		"BEST_PICKUP_THEN_BEST_DELIVERY":      1,
		"BEST_PICKUP_DELIVERY_PAIR":           2,
		"BEST_PICKUP_DELIVERY_PAIR_MULTITOUR": 3,
	}
)

func (x LocalCheapestInsertionParameters_PairInsertionStrategy) Enum() *LocalCheapestInsertionParameters_PairInsertionStrategy {
	p := new(LocalCheapestInsertionParameters_PairInsertionStrategy)
	*p = x
	return p
}

func (x LocalCheapestInsertionParameters_PairInsertionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalCheapestInsertionParameters_PairInsertionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_enumTypes[0].Descriptor()
}

func (LocalCheapestInsertionParameters_PairInsertionStrategy) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_heuristic_parameters_proto_enumTypes[0]
}

func (x LocalCheapestInsertionParameters_PairInsertionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalCheapestInsertionParameters_PairInsertionStrategy.Descriptor instead.
func (LocalCheapestInsertionParameters_PairInsertionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescGZIP(), []int{0, 0}
}

// Properties used to select in which order nodes or node pairs are considered
// in insertion heuristics.
type LocalCheapestInsertionParameters_InsertionSortingProperty int32

const (
	// Invalid property.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_UNSPECIFIED LocalCheapestInsertionParameters_InsertionSortingProperty = 0
	// Selects nodes with the least number of allowed vehicles.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_ALLOWED_VEHICLES LocalCheapestInsertionParameters_InsertionSortingProperty = 1
	// Selects nodes with the highest penalty.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_PENALTY LocalCheapestInsertionParameters_InsertionSortingProperty = 2
	// Selects nodes with the highest penalty / number of allowed vehicles
	// ratio.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_PENALTY_OVER_ALLOWED_VEHICLES_RATIO LocalCheapestInsertionParameters_InsertionSortingProperty = 3
	// Selects nodes that are on average the farthest from vehicles.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_HIGHEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS LocalCheapestInsertionParameters_InsertionSortingProperty = 4
	// Selects nodes that are on average the closest to vehicles.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_LOWEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS LocalCheapestInsertionParameters_InsertionSortingProperty = 5
	// Select nodes with the smallest distance to the closest vehicle.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_LOWEST_MIN_ARC_COST_TO_VEHICLE_START_ENDS LocalCheapestInsertionParameters_InsertionSortingProperty = 6
	// Selects nodes that have a higher dimension usage on average, where the
	// usage is determined as the ratio of node demand over vehicle capacity.
	// Currently, this property only supports unary dimensions.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_HIGHEST_DIMENSION_USAGE LocalCheapestInsertionParameters_InsertionSortingProperty = 7
	// Selects nodes in random order.
	// This property cannot be used in conjunction with other properties.
	LocalCheapestInsertionParameters_SORTING_PROPERTY_RANDOM LocalCheapestInsertionParameters_InsertionSortingProperty = 8
)

// Enum value maps for LocalCheapestInsertionParameters_InsertionSortingProperty.
var (
	LocalCheapestInsertionParameters_InsertionSortingProperty_name = map[int32]string{
		0: "SORTING_PROPERTY_UNSPECIFIED",
		1: "SORTING_PROPERTY_ALLOWED_VEHICLES",
		2: "SORTING_PROPERTY_PENALTY",
		3: "SORTING_PROPERTY_PENALTY_OVER_ALLOWED_VEHICLES_RATIO",
		4: "SORTING_PROPERTY_HIGHEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS",
		5: "SORTING_PROPERTY_LOWEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS",
		6: "SORTING_PROPERTY_LOWEST_MIN_ARC_COST_TO_VEHICLE_START_ENDS",
		7: "SORTING_PROPERTY_HIGHEST_DIMENSION_USAGE",
		8: "SORTING_PROPERTY_RANDOM",
	}
	LocalCheapestInsertionParameters_InsertionSortingProperty_value = map[string]int32{
		"SORTING_PROPERTY_UNSPECIFIED":                                0,
		"SORTING_PROPERTY_ALLOWED_VEHICLES":                           1,
		"SORTING_PROPERTY_PENALTY":                                    2,
		"SORTING_PROPERTY_PENALTY_OVER_ALLOWED_VEHICLES_RATIO":        3,
		"SORTING_PROPERTY_HIGHEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS": 4,
		"SORTING_PROPERTY_LOWEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS":  5,
		"SORTING_PROPERTY_LOWEST_MIN_ARC_COST_TO_VEHICLE_START_ENDS":  6,
		"SORTING_PROPERTY_HIGHEST_DIMENSION_USAGE":                    7,
		"SORTING_PROPERTY_RANDOM":                                     8,
	}
)

func (x LocalCheapestInsertionParameters_InsertionSortingProperty) Enum() *LocalCheapestInsertionParameters_InsertionSortingProperty {
	p := new(LocalCheapestInsertionParameters_InsertionSortingProperty)
	*p = x
	return p
}

func (x LocalCheapestInsertionParameters_InsertionSortingProperty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalCheapestInsertionParameters_InsertionSortingProperty) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_enumTypes[1].Descriptor()
}

func (LocalCheapestInsertionParameters_InsertionSortingProperty) Type() protoreflect.EnumType {
	return &file_ortools_constraint_solver_routing_heuristic_parameters_proto_enumTypes[1]
}

func (x LocalCheapestInsertionParameters_InsertionSortingProperty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalCheapestInsertionParameters_InsertionSortingProperty.Descriptor instead.
func (LocalCheapestInsertionParameters_InsertionSortingProperty) EnumDescriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescGZIP(), []int{0, 1}
}

// Parameters used to configure local cheapest insertion heuristics.
type LocalCheapestInsertionParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Choice of insertion strategy for pickup/delivery pairs, used in local
	// cheapest insertion, both first solution heuristic and LNS.
	PickupDeliveryStrategy LocalCheapestInsertionParameters_PairInsertionStrategy `protobuf:"varint,1,opt,name=pickup_delivery_strategy,json=pickupDeliveryStrategy,proto3,enum=operations_research.LocalCheapestInsertionParameters_PairInsertionStrategy" json:"pickup_delivery_strategy,omitempty"`
	// The properties used to sort insertion entries in the local cheapest
	// insertion heuristic, in *decreasing* order of priority. The properties
	// listed here are applied hierarchically, from highest to lowest priority.
	// When no properties are provided
	//
	//	(SORTING_PROPERTY_ALLOWED_VEHICLES, SORTING_PROPERTY_PENALTY)
	//
	// is used by default.
	InsertionSortingProperties []LocalCheapestInsertionParameters_InsertionSortingProperty `protobuf:"varint,2,rep,packed,name=insertion_sorting_properties,json=insertionSortingProperties,proto3,enum=operations_research.LocalCheapestInsertionParameters_InsertionSortingProperty" json:"insertion_sorting_properties,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LocalCheapestInsertionParameters) Reset() {
	*x = LocalCheapestInsertionParameters{}
	mi := &file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCheapestInsertionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCheapestInsertionParameters) ProtoMessage() {}

func (x *LocalCheapestInsertionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCheapestInsertionParameters.ProtoReflect.Descriptor instead.
func (*LocalCheapestInsertionParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescGZIP(), []int{0}
}

func (x *LocalCheapestInsertionParameters) GetPickupDeliveryStrategy() LocalCheapestInsertionParameters_PairInsertionStrategy {
	if x != nil {
		return x.PickupDeliveryStrategy
	}
	return LocalCheapestInsertionParameters_AUTOMATIC
}

func (x *LocalCheapestInsertionParameters) GetInsertionSortingProperties() []LocalCheapestInsertionParameters_InsertionSortingProperty {
	if x != nil {
		return x.InsertionSortingProperties
	}
	return nil
}

// Parameters used to configure savings heuristics.
type SavingsParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ratio (in ]0, 1]) of neighbors to consider for each node when constructing
	// the savings. If unspecified, its value is considered to be 1.0.
	NeighborsRatio float64 `protobuf:"fixed64,1,opt,name=neighbors_ratio,json=neighborsRatio,proto3" json:"neighbors_ratio,omitempty"`
	// The number of neighbors considered for each node in the Savings heuristic
	// is chosen so that the space used to store the savings doesn't exceed
	// max_memory_usage_bytes, which must be in ]0, 1e10].
	// NOTE: If both neighbors_ratio and max_memory_usage_bytes
	// are specified, the number of neighbors considered for each node will be the
	// minimum of the two numbers determined by these parameters.
	MaxMemoryUsageBytes float64 `protobuf:"fixed64,2,opt,name=max_memory_usage_bytes,json=maxMemoryUsageBytes,proto3" json:"max_memory_usage_bytes,omitempty"`
	// Add savings related to reverse arcs when finding the nearest neighbors
	// of the nodes.
	AddReverseArcs bool `protobuf:"varint,3,opt,name=add_reverse_arcs,json=addReverseArcs,proto3" json:"add_reverse_arcs,omitempty"`
	// Coefficient of the cost of the arc for which the saving value is being
	// computed:
	// Saving(a-->b) = Cost(a-->end) + Cost(start-->b)
	//   - arc_coefficient * Cost(a-->b)
	//
	// This parameter must be greater than 0, and its default value is 1.
	ArcCoefficient float64 `protobuf:"fixed64,4,opt,name=arc_coefficient,json=arcCoefficient,proto3" json:"arc_coefficient,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SavingsParameters) Reset() {
	*x = SavingsParameters{}
	mi := &file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavingsParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavingsParameters) ProtoMessage() {}

func (x *SavingsParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavingsParameters.ProtoReflect.Descriptor instead.
func (*SavingsParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescGZIP(), []int{1}
}

func (x *SavingsParameters) GetNeighborsRatio() float64 {
	if x != nil {
		return x.NeighborsRatio
	}
	return 0
}

func (x *SavingsParameters) GetMaxMemoryUsageBytes() float64 {
	if x != nil {
		return x.MaxMemoryUsageBytes
	}
	return 0
}

func (x *SavingsParameters) GetAddReverseArcs() bool {
	if x != nil {
		return x.AddReverseArcs
	}
	return false
}

func (x *SavingsParameters) GetArcCoefficient() float64 {
	if x != nil {
		return x.ArcCoefficient
	}
	return 0
}

// Parameters used to configure global cheapest insertion heuristics.
type GlobalCheapestInsertionParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ratio (between 0 and 1) of available vehicles in the model on which
	// farthest nodes of the model are inserted as seeds.
	FarthestSeedsRatio float64 `protobuf:"fixed64,1,opt,name=farthest_seeds_ratio,json=farthestSeedsRatio,proto3" json:"farthest_seeds_ratio,omitempty"`
	// Ratio (in ]0, 1]) of closest non start/end nodes to consider as neighbors
	// for each node when creating new insertions in the parallel/sequential
	// cheapest insertion heuristic.
	// If not overridden, its default value is 1, meaning all neighbors will be
	// considered.
	// The neighborhood ratio is coupled with the corresponding min_neighbors
	// integer, indicating the minimum number of neighbors to consider for each
	// node:
	// num_closest_neighbors =
	//
	//	max(min_neighbors, neighbors_ratio * NUM_NON_START_END_NODES)
	//
	// This minimum number of neighbors must be greater or equal to 1, its
	// default value.
	NeighborsRatio float64 `protobuf:"fixed64,2,opt,name=neighbors_ratio,json=neighborsRatio,proto3" json:"neighbors_ratio,omitempty"`
	MinNeighbors   int32   `protobuf:"varint,3,opt,name=min_neighbors,json=minNeighbors,proto3" json:"min_neighbors,omitempty"`
	// Whether or not to only consider closest neighbors when initializing the
	// assignment. More precisely, if true, only closest neighbors (see
	// neighbors_ratio and min_neighbors) are considered as insertion positions
	// during initialization. Otherwise, all possible insertion positions are
	// considered.
	UseNeighborsRatioForInitialization bool `protobuf:"varint,6,opt,name=use_neighbors_ratio_for_initialization,json=useNeighborsRatioForInitialization,proto3" json:"use_neighbors_ratio_for_initialization,omitempty"`
	// Whether or not to consider entries making the nodes/pairs unperformed.
	// More precisely, if true, entries are created for making the nodes/pairs
	// unperformed, and when the cost of making a node unperformed is lower than
	// all insertions, the node/pair will be made unperformed. If false, only
	// entries making a node/pair performed are considered.
	AddUnperformedEntries bool `protobuf:"varint,7,opt,name=add_unperformed_entries,json=addUnperformedEntries,proto3" json:"add_unperformed_entries,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GlobalCheapestInsertionParameters) Reset() {
	*x = GlobalCheapestInsertionParameters{}
	mi := &file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalCheapestInsertionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalCheapestInsertionParameters) ProtoMessage() {}

func (x *GlobalCheapestInsertionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalCheapestInsertionParameters.ProtoReflect.Descriptor instead.
func (*GlobalCheapestInsertionParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalCheapestInsertionParameters) GetFarthestSeedsRatio() float64 {
	if x != nil {
		return x.FarthestSeedsRatio
	}
	return 0
}

func (x *GlobalCheapestInsertionParameters) GetNeighborsRatio() float64 {
	if x != nil {
		return x.NeighborsRatio
	}
	return 0
}

func (x *GlobalCheapestInsertionParameters) GetMinNeighbors() int32 {
	if x != nil {
		return x.MinNeighbors
	}
	return 0
}

func (x *GlobalCheapestInsertionParameters) GetUseNeighborsRatioForInitialization() bool {
	if x != nil {
		return x.UseNeighborsRatioForInitialization
	}
	return false
}

func (x *GlobalCheapestInsertionParameters) GetAddUnperformedEntries() bool {
	if x != nil {
		return x.AddUnperformedEntries
	}
	return false
}

var File_ortools_constraint_solver_routing_heuristic_parameters_proto protoreflect.FileDescriptor

const file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDesc = "" +
	"\n" +
	"<ortools/constraint_solver/routing_heuristic_parameters.proto\x12\x13operations_research\"\x9c\a\n" +
	" LocalCheapestInsertionParameters\x12\x85\x01\n" +
	"\x18pickup_delivery_strategy\x18\x01 \x01(\x0e2K.operations_research.LocalCheapestInsertionParameters.PairInsertionStrategyR\x16pickupDeliveryStrategy\x12\x90\x01\n" +
	"\x1cinsertion_sorting_properties\x18\x02 \x03(\x0e2N.operations_research.LocalCheapestInsertionParameters.InsertionSortingPropertyR\x1ainsertionSortingProperties\"\x92\x01\n" +
	"\x15PairInsertionStrategy\x12\r\n" +
	"\tAUTOMATIC\x10\x00\x12\"\n" +
	"\x1eBEST_PICKUP_THEN_BEST_DELIVERY\x10\x01\x12\x1d\n" +
	"\x19BEST_PICKUP_DELIVERY_PAIR\x10\x02\x12'\n" +
	"#BEST_PICKUP_DELIVERY_PAIR_MULTITOUR\x10\x03\"\xc7\x03\n" +
	"\x18InsertionSortingProperty\x12 \n" +
	"\x1cSORTING_PROPERTY_UNSPECIFIED\x10\x00\x12%\n" +
	"!SORTING_PROPERTY_ALLOWED_VEHICLES\x10\x01\x12\x1c\n" +
	"\x18SORTING_PROPERTY_PENALTY\x10\x02\x128\n" +
	"4SORTING_PROPERTY_PENALTY_OVER_ALLOWED_VEHICLES_RATIO\x10\x03\x12?\n" +
	";SORTING_PROPERTY_HIGHEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS\x10\x04\x12>\n" +
	":SORTING_PROPERTY_LOWEST_AVG_ARC_COST_TO_VEHICLE_START_ENDS\x10\x05\x12>\n" +
	":SORTING_PROPERTY_LOWEST_MIN_ARC_COST_TO_VEHICLE_START_ENDS\x10\x06\x12,\n" +
	"(SORTING_PROPERTY_HIGHEST_DIMENSION_USAGE\x10\a\x12\x1b\n" +
	"\x17SORTING_PROPERTY_RANDOM\x10\b\"\xc4\x01\n" +
	"\x11SavingsParameters\x12'\n" +
	"\x0fneighbors_ratio\x18\x01 \x01(\x01R\x0eneighborsRatio\x123\n" +
	"\x16max_memory_usage_bytes\x18\x02 \x01(\x01R\x13maxMemoryUsageBytes\x12(\n" +
	"\x10add_reverse_arcs\x18\x03 \x01(\bR\x0eaddReverseArcs\x12'\n" +
	"\x0farc_coefficient\x18\x04 \x01(\x01R\x0earcCoefficient\"\xaf\x02\n" +
	"!GlobalCheapestInsertionParameters\x120\n" +
	"\x14farthest_seeds_ratio\x18\x01 \x01(\x01R\x12farthestSeedsRatio\x12'\n" +
	"\x0fneighbors_ratio\x18\x02 \x01(\x01R\x0eneighborsRatio\x12#\n" +
	"\rmin_neighbors\x18\x03 \x01(\x05R\fminNeighbors\x12R\n" +
	"&use_neighbors_ratio_for_initialization\x18\x06 \x01(\bR\"useNeighborsRatioForInitialization\x126\n" +
	"\x17add_unperformed_entries\x18\a \x01(\bR\x15addUnperformedEntriesB\x8f\x01\n" +
	"#com.google.ortools.constraintsolverP\x01ZDgithub.com/airspacetechnologies/or-tools/go/ortools/constraintsolver\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3"

var (
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescOnce sync.Once
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescData []byte
)

func file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescGZIP() []byte {
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescOnce.Do(func() {
		file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDesc), len(file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDesc)))
	})
	return file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDescData
}

var file_ortools_constraint_solver_routing_heuristic_parameters_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ortools_constraint_solver_routing_heuristic_parameters_proto_goTypes = []any{
	(LocalCheapestInsertionParameters_PairInsertionStrategy)(0),    // 0: operations_research.LocalCheapestInsertionParameters.PairInsertionStrategy
	(LocalCheapestInsertionParameters_InsertionSortingProperty)(0), // 1: operations_research.LocalCheapestInsertionParameters.InsertionSortingProperty
	(*LocalCheapestInsertionParameters)(nil),                       // 2: operations_research.LocalCheapestInsertionParameters
	(*SavingsParameters)(nil),                                      // 3: operations_research.SavingsParameters
	(*GlobalCheapestInsertionParameters)(nil),                      // 4: operations_research.GlobalCheapestInsertionParameters
}
var file_ortools_constraint_solver_routing_heuristic_parameters_proto_depIdxs = []int32{
	0, // 0: operations_research.LocalCheapestInsertionParameters.pickup_delivery_strategy:type_name -> operations_research.LocalCheapestInsertionParameters.PairInsertionStrategy
	1, // 1: operations_research.LocalCheapestInsertionParameters.insertion_sorting_properties:type_name -> operations_research.LocalCheapestInsertionParameters.InsertionSortingProperty
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ortools_constraint_solver_routing_heuristic_parameters_proto_init() }
func file_ortools_constraint_solver_routing_heuristic_parameters_proto_init() {
	if File_ortools_constraint_solver_routing_heuristic_parameters_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDesc), len(file_ortools_constraint_solver_routing_heuristic_parameters_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_constraint_solver_routing_heuristic_parameters_proto_goTypes,
		DependencyIndexes: file_ortools_constraint_solver_routing_heuristic_parameters_proto_depIdxs,
		EnumInfos:         file_ortools_constraint_solver_routing_heuristic_parameters_proto_enumTypes,
		MessageInfos:      file_ortools_constraint_solver_routing_heuristic_parameters_proto_msgTypes,
	}.Build()
	File_ortools_constraint_solver_routing_heuristic_parameters_proto = out.File
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_goTypes = nil
	file_ortools_constraint_solver_routing_heuristic_parameters_proto_depIdxs = nil
}
