// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file contains a protocol buffer definition for search limits.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ortools/constraint_solver/search_limit.proto

package constraintsolver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A search limit
// The default values for int64 fields is the maxima value, i.e., 2^63-1
type RegularLimitParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO(user): Specify the time units or switch to google.Duration proto.
	Time           int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Branches       int64 `protobuf:"varint,2,opt,name=branches,proto3" json:"branches,omitempty"`
	Failures       int64 `protobuf:"varint,3,opt,name=failures,proto3" json:"failures,omitempty"`
	Solutions      int64 `protobuf:"varint,4,opt,name=solutions,proto3" json:"solutions,omitempty"`
	SmartTimeCheck bool  `protobuf:"varint,5,opt,name=smart_time_check,json=smartTimeCheck,proto3" json:"smart_time_check,omitempty"`
	Cumulative     bool  `protobuf:"varint,6,opt,name=cumulative,proto3" json:"cumulative,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegularLimitParameters) Reset() {
	*x = RegularLimitParameters{}
	mi := &file_ortools_constraint_solver_search_limit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegularLimitParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegularLimitParameters) ProtoMessage() {}

func (x *RegularLimitParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ortools_constraint_solver_search_limit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegularLimitParameters.ProtoReflect.Descriptor instead.
func (*RegularLimitParameters) Descriptor() ([]byte, []int) {
	return file_ortools_constraint_solver_search_limit_proto_rawDescGZIP(), []int{0}
}

func (x *RegularLimitParameters) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RegularLimitParameters) GetBranches() int64 {
	if x != nil {
		return x.Branches
	}
	return 0
}

func (x *RegularLimitParameters) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *RegularLimitParameters) GetSolutions() int64 {
	if x != nil {
		return x.Solutions
	}
	return 0
}

func (x *RegularLimitParameters) GetSmartTimeCheck() bool {
	if x != nil {
		return x.SmartTimeCheck
	}
	return false
}

func (x *RegularLimitParameters) GetCumulative() bool {
	if x != nil {
		return x.Cumulative
	}
	return false
}

var File_ortools_constraint_solver_search_limit_proto protoreflect.FileDescriptor

const file_ortools_constraint_solver_search_limit_proto_rawDesc = "" +
	"\n" +
	",ortools/constraint_solver/search_limit.proto\x12\x13operations_research\"\xcc\x01\n" +
	"\x16RegularLimitParameters\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x1a\n" +
	"\bbranches\x18\x02 \x01(\x03R\bbranches\x12\x1a\n" +
	"\bfailures\x18\x03 \x01(\x03R\bfailures\x12\x1c\n" +
	"\tsolutions\x18\x04 \x01(\x03R\tsolutions\x12(\n" +
	"\x10smart_time_check\x18\x05 \x01(\bR\x0esmartTimeCheck\x12\x1e\n" +
	"\n" +
	"cumulative\x18\x06 \x01(\bR\n" +
	"cumulativeB\xa4\x01\n" +
	"#com.google.ortools.constraintsolverB\x13SearchLimitProtobufP\x01ZDgithub.com/airspacetechnologies/or-tools/go/ortools/constraintsolver\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3"

var (
	file_ortools_constraint_solver_search_limit_proto_rawDescOnce sync.Once
	file_ortools_constraint_solver_search_limit_proto_rawDescData []byte
)

func file_ortools_constraint_solver_search_limit_proto_rawDescGZIP() []byte {
	file_ortools_constraint_solver_search_limit_proto_rawDescOnce.Do(func() {
		file_ortools_constraint_solver_search_limit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_search_limit_proto_rawDesc), len(file_ortools_constraint_solver_search_limit_proto_rawDesc)))
	})
	return file_ortools_constraint_solver_search_limit_proto_rawDescData
}

var file_ortools_constraint_solver_search_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ortools_constraint_solver_search_limit_proto_goTypes = []any{
	(*RegularLimitParameters)(nil), // 0: operations_research.RegularLimitParameters
}
var file_ortools_constraint_solver_search_limit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ortools_constraint_solver_search_limit_proto_init() }
func file_ortools_constraint_solver_search_limit_proto_init() {
	if File_ortools_constraint_solver_search_limit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ortools_constraint_solver_search_limit_proto_rawDesc), len(file_ortools_constraint_solver_search_limit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_constraint_solver_search_limit_proto_goTypes,
		DependencyIndexes: file_ortools_constraint_solver_search_limit_proto_depIdxs,
		MessageInfos:      file_ortools_constraint_solver_search_limit_proto_msgTypes,
	}.Build()
	File_ortools_constraint_solver_search_limit_proto = out.File
	file_ortools_constraint_solver_search_limit_proto_goTypes = nil
	file_ortools_constraint_solver_search_limit_proto_depIdxs = nil
}
