// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ortools/util/optional_boolean.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A "three-way" boolean: unspecified, false or true.
//
// We don't use the value of 1 to increase the chance to catch bugs: eg. in
// python, a user may set a proto field of this type enum to a boolean value
// without type checks, if they set it to True, the proto validity code will
// catch it (because it'll be cast to 1, which is an invalid enum value).
// Note that if the user sets if to False (i.e. 0), it will be caught by the
// routing library's parameter validity check too.
type OptionalBoolean int32

const (
	OptionalBoolean_BOOL_UNSPECIFIED OptionalBoolean = 0
	OptionalBoolean_BOOL_FALSE       OptionalBoolean = 2
	OptionalBoolean_BOOL_TRUE        OptionalBoolean = 3
)

// Enum value maps for OptionalBoolean.
var (
	OptionalBoolean_name = map[int32]string{
		0: "BOOL_UNSPECIFIED",
		2: "BOOL_FALSE",
		3: "BOOL_TRUE",
	}
	OptionalBoolean_value = map[string]int32{
		"BOOL_UNSPECIFIED": 0,
		"BOOL_FALSE":       2,
		"BOOL_TRUE":        3,
	}
)

func (x OptionalBoolean) Enum() *OptionalBoolean {
	p := new(OptionalBoolean)
	*p = x
	return p
}

func (x OptionalBoolean) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionalBoolean) Descriptor() protoreflect.EnumDescriptor {
	return file_ortools_util_optional_boolean_proto_enumTypes[0].Descriptor()
}

func (OptionalBoolean) Type() protoreflect.EnumType {
	return &file_ortools_util_optional_boolean_proto_enumTypes[0]
}

func (x OptionalBoolean) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionalBoolean.Descriptor instead.
func (OptionalBoolean) EnumDescriptor() ([]byte, []int) {
	return file_ortools_util_optional_boolean_proto_rawDescGZIP(), []int{0}
}

var File_ortools_util_optional_boolean_proto protoreflect.FileDescriptor

const file_ortools_util_optional_boolean_proto_rawDesc = "" +
	"\n" +
	"#ortools/util/optional_boolean.proto\x12\x13operations_research*F\n" +
	"\x0fOptionalBoolean\x12\x14\n" +
	"\x10BOOL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"BOOL_FALSE\x10\x02\x12\r\n" +
	"\tBOOL_TRUE\x10\x03Bk\n" +
	"\x17com.google.ortools.utilP\x01Z8github.com/airspacetechnologies/or-tools/go/ortools/util\xaa\x02\x13Google.OrTools.Utilb\x06proto3"

var (
	file_ortools_util_optional_boolean_proto_rawDescOnce sync.Once
	file_ortools_util_optional_boolean_proto_rawDescData []byte
)

func file_ortools_util_optional_boolean_proto_rawDescGZIP() []byte {
	file_ortools_util_optional_boolean_proto_rawDescOnce.Do(func() {
		file_ortools_util_optional_boolean_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ortools_util_optional_boolean_proto_rawDesc), len(file_ortools_util_optional_boolean_proto_rawDesc)))
	})
	return file_ortools_util_optional_boolean_proto_rawDescData
}

var file_ortools_util_optional_boolean_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ortools_util_optional_boolean_proto_goTypes = []any{
	(OptionalBoolean)(0), // 0: operations_research.OptionalBoolean
}
var file_ortools_util_optional_boolean_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ortools_util_optional_boolean_proto_init() }
func file_ortools_util_optional_boolean_proto_init() {
	if File_ortools_util_optional_boolean_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ortools_util_optional_boolean_proto_rawDesc), len(file_ortools_util_optional_boolean_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ortools_util_optional_boolean_proto_goTypes,
		DependencyIndexes: file_ortools_util_optional_boolean_proto_depIdxs,
		EnumInfos:         file_ortools_util_optional_boolean_proto_enumTypes,
	}.Build()
	File_ortools_util_optional_boolean_proto = out.File
	file_ortools_util_optional_boolean_proto_goTypes = nil
	file_ortools_util_optional_boolean_proto_depIdxs = nil
}
